### ISSUE TITLE
Konfiguration der OpenAIRE-Dokumenttypen

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1045]
Bislang übernimmt OPUS beim Abruf der Daten für OpenAIRE über die OAI-PMH-API die Schreibweise (Groß- und Kleinschreibung) der Dokumenttypen des Gemeinsamen Vokabulars:

Abruf: \<OPUS-URL>/oai?verb=ListRecords&metadataPrefix=oai_dc&set=openaire

application.ini:
```
documentType.article.dcType = 'article'
documentType.book.dcType = 'book'

openAireTypes[] = 'article'
openAireTypes[] = 'book'
```
Ausgabe über OAI:
```
<dc:type>info:eu-repo/semantics/article</dc:type>
<dc:type>doc-type:article</dc:type>

<dc:type>info:eu-repo/semantics/book</dc:type>
<dc:type>doc-type:book</dc:type>
```

Das hat bislang so funktioniert, weil Groß- und Kleinschreibung der Dokumenttypen in Gemeinsamem Vokabular (GemVok) und OpenAIRE identisch waren. Mit der Version 2.0 des Gemeinsamen Vokabulars funktioniert das nicht mehr. Nun müssen bei OpenAIRE die bisherigen Schreibweisen beibehalten werden (s. Format-Spezifikation: https://guidelines.openaire.eu/en/latest/literature/field_publicationtype.html#usage-instruction), während sich die Schreibweisen der Terme im GemVok 2.0 ändern. Benötigt wird als Ausgabe über OAI:

```
<dc:type>info:eu-repo/semantics/article</dc:type>
<dc:type>doc-type:Article</dc:type>

<dc:type>ino:eu-repo/semantics/book</dc:type>
<dc:type>doc-type:Book</dc:type>
```

Das kann momentan nicht konfiguriert werden. Passt man nur die Dokumenttypen gemäß GemVok an, geht die Zuordnung zu den OpenAIRE-Dokumenttypen verloren und diese werden fälschlicherweise als _other_ ausgewiesen.

application.ini:
```
documentType.article.dcType = 'Article'
documentType.book.dcType = 'Book'

openAireTypes[] = 'article'
openAireTypes[] = 'book'
```

OAI:
```
<dc:type>info:eu-repo/semantics/other</dc:type>
<dc:type>doc-type:Article</dc:type>

<dc:type>info:eu-repo/semantics/other</dc:type>
<dc:type>doc-type:Book</dc:type>
```

Verwendet man auch bei der Konfiguration der OpenAIRE-Dokumenttypen die neue Schreibweise, erfolgt die Zuordnung korrekt, aber die Groß- und Kleinschreibung entspricht nicht mehr der Spezifikation:

application.ini:
```
documentType.article.dcType = 'Article'
documentType.book.dcType = 'Book'

openAireTypes[] = 'Article'
openAireTypes[] = 'Book'
```

OAI:
```
<dc:type>info:eu-repo/semantics/Article</dc:type>
<dc:type>doc-type:Article</dc:type>

<dc:type>info:eu-repo/semantics/Book</dc:type>
<dc:type>doc-type:Book</dc:type>
```

Die Konfiguration der OpenAIRE-Dokumenttypen müsste daher stärker von den Dokumenttypen des GemVok entkoppelt werden, z.B. indem das Matching zwischen OpenAIRE- und GemVok-Dokumenttypen case-insensitive gestaltet wird.

**Comment by alw-bsz** [comment]
Nachtrag: bei einem Dokumenttyp unterscheiden sich die Terme künftig nicht nur in Groß- und Kleinschreibung, sondern die Bezeichnungen an sich. Der OPUS-Dokumenttyp "Rezension" war bislang auszugeben als
```
<dc:type>info:eu-repo/semantics/review<dc:type>
<dc:type>doc-type:review</dc:type>
```

Nun wird im GemVok aus "review" "Recension":
```
<dc:type>info:eu-repo/semantics/review<dc:type>
<dc:type>doc-type:Recension</dc:type>
```

D.h. ein nur case-insensitives Mapping der GemVok- auf die OpenAIRE-Dokumenttypen würde zumindest für die Rezension nicht funktionieren.

**Comment by j3nsch** [comment]
Aus Zeitgründen sollte der PR für die Änderungen in der Konfiguration für das Gemeinsame Vokabulars 2.0 gemacht werden bevor dieses Problem behoben ist. Dieses Problem wird erst nach den anderen, noch offenen Arbeiten für 4.8.1 behoben werden.
Außerdem würde der PR bei der Umsetzung von Tests helfen. Dafür ist das neue Mapping sinnvoll. Die Änderung werden sowieso vermutlich dafür sorgen, dass einige existierende Tests brechen.

Bislang werden die `openAireTypes` als Filter verwendet. Diese Sonderbehandlung könnte aufgelöst werden. Dann müsste für jeden Dokumenttyp der passende OpenAire-Typ konfiguriert werden.

    documentType.article.dcType = 'Article'
    documentType.article.openAire = 'article'

Bei OPUS 4 Dokumenttypen ohne `openAire` Eintrag, würde dann automatisch 'other' verwendet. Das müsste so konfiguriert werden.

   documentType.default.openAire = 'other'

Die alte `openAireTypes` Konfiguration würde wegfallen.

Ein automatisches Fallback zu `dcType` mit kleinem Anfangsbuchstaben ist nicht möglich, weil wir immer noch eine Liste mit gültigen OpenAire-Typen benötigen würden. Das Beenden der Sonderbehandlung ist einfacher umzusetzen und leichter nachzuvollziehen.

Die notwendige Konfiguration für OpenAire sollte Teil des neuen PRs sein. 

Für die Umsetzung muss dann noch der View Helper `Application_View_Helper_OpenAireType` ersetzt werden. Der DC-Type kann nicht eindeutig auf den OPUS 4 Typ zurück konvertiert werden, manche Typen verwenden den gleichen DC-Type. Das heißt der OpenAire-Typ müsste vorab aus dem OPUS 4 Typ bestimmt und mit an das XSLT übergeben werden. Sollte später OpenAire ein eigenes Format erhalten würde sich die Lösung ein wenig ändern. Die vorgeschlagene Konfiguration sollte dann immer noch sinnvoll sein.

**Comment by j3nsch** [comment]
Ich denke wir werden später diese Konfiguration in eine separate Datei auslagern, damit sie nur geladen wird, wenn sie gebraucht wird. Wenn die Konfiguration, die immer geladen wird, kleiner wird, kann das der Performanz nur helfen, auch wenn es durch diese eine Sache noch nicht messbar sein wird. Es hilft auch bei der Organisation von Verantwortlichkeiten im Code.

**Comment by alw-bsz** [comment]
Ich habe es getestet und es sieht gut aus.

**Comment by j3nsch** [comment]
Ich würde vorschlagen für die Änderungen vom BSZ, für 4.8.1, den gleichen Branch zu verwenden.

**Comment by alw-bsz** [comment]
Das bietet sich an und können wir gerne so machen. Für den Teil der Arbeiten an den Dokumenttypen, bei dem unsicher ist, ob er bis zum geplanten Release der 4.8.1 fertig wird, würden wir vermutlich am besten einen Fork von dem Branch machen, oder?

**Comment by j3nsch** [comment]
Das ist im Prinzip egal, solange ihr alles habt was Ihr braucht. Ein weiterer Branch basierend auf dem existierenden sollte funktionieren (Ich glaube ein Fork ist immer ein ganzen Repository.). Wenn Ihr dann aber auf dem ersten Branch weiter arbeitet und diese Sachen im zweiten Branch braucht, muss der immer wieder aktualisiert werden. Das ist nicht schlimm, aber kann vielleicht vermieden werden. Ihr müsst sehen wie Ihr Euch da organisiert.
