### ISSUE TITLE
Gemeinsames Vokabular 2.0: Terme für OAI-PMH-API implementieren

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1048]
Die Schreibweise der Terme wurde im Gem. Vok. 2.0 vereinheitlicht. Die Terme müssen daher für die Auslieferung über die OAI-PMH-Schnittstelle aktualisiert werden. Darüber hinaus haben sich auch Terme verändert (review -> Recension; doctoralThesis -> Unterteilung in "PhDThesis" und "Habilitation"). Dabei muss die bisherige Schreibweise der Dokumenttypen für OpenAIRE beibehalten werden.

**Comment by j3nsch** [comment]
Im Zusammenhang mit diesen Änderung wurden die XSD Dateien für XMetaDissPlus aktualisiert.

**Comment by alw-bsz** [comment]
Die Terme gem. GemVok 2.0 für die vorhandenen Dokumenttypen wurden implementiert.
