### ISSUE TITLE
Publish-Templates für weitere Dokumenttypen erstellen

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1049]
Publish-Formulare (Templates) für die Dokumenttypen erstellen, die neu aus dem Gemeinsamen Vokabular (v2.0 sowie Nachträge aus 1.0) in die OPUS-Standardauslieferung aufgenommen werden,

**Comment by j3nsch** [comment]
Durch die zusätzliche Verzögerung beim Release von 4.8.1 wäre es gut, wenn die Arbeiten für die neuen Dokumententypen auch noch mit einfließen könnten. Bei Bedarf wird 4.8.1 noch weiter geschoben. Wir sollten versuchen in Zukunft Release frühstens zwei Wochen nachdem alle externen Arbeiten abgeschlossen sind, zu machen. Das macht schon jetzt den 26. Juli für den Release unwahrscheinlich.

**Comment by j3nsch** [comment]
Die Änderungen sind nach **v4.8.1** übernommen.

**Comment by alw-bsz** [comment]
Vielen Dank!
