### ISSUE TITLE
Export der neuen Dokumenttypen über OAI-PMH

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1050]
Die neuen Dokumenttypen müssen in die Exportformate der OAI-PMH-API gemappt werden:
- OAI-DC
- XMetaDissPlus
- MARCXML

**Comment by j3nsch** [comment]
Wie sieht es mit den OAI-Sets für die neuen Dokumenttypen aus? Die Sets werden automatisch erzeugt. Die Anzahl erhöht sich dort also auch. Gibt es Besonderheiten, die beachtet werden müssen (gegebenenfalls separates Ticket)? Es wurde ja von einer Hierarchy in den Dokumenttypen gesprochen.

**Comment by j3nsch** [comment]
@alw-bsz Bei den Sets wird der DC-Type der Dokumenttypen verwendet? Gibt es mehrere Dokumenttypen, die auf den gleichen DC-Type mappen? Wenn nicht im Standard, dann könnte das natürlich lokal immer konfiguriert werden, um vielleicht zwei unterschiedliche Publish-Templates zu verwenden. Das muss bei der Ermittlung der zum Set gehörenden Dokumente berücksichtigt werden, oder? Siehe auch #769.

**Comment by alw-bsz** [comment]
@j3nsch In der application.ini steht jeweils im Parameter *.dcType der Term aus dem Gem. Vok. Dieser wird auch für die Set-Bildung verwendet. Das ist korrekt. Es gibt tatsächlich ein paar Dokumenttypen, die auf denselben DC-Type mappen, und zwar konkret die OPUS-eigenen Typen diplom, examen und magister. Dabei handelt es sich im Gem. Vok. um keine eigenständigen Dokumenttypen, sie fallen stattdessen unter MasterThesis. In der application.ini ist als dcType für diese Dokumenttpen daher "MasterThesis" konfiguriert.

Aktuell fallen mir keine Besonderheiten ein, die zu beachten sind. Es stimmt, dass es jetzt eine gewisse Hierarchisierung gibt, diese wirkt sich aber nicht auf die OAI-Sets aus. Da sind alle Dokumenttypen weiterhin ohne Hierarchie abzubilden. Eine Hierarchisierung wäre evtl. eher im Frontend im Publish-Formular und im Browsing relevant.

**Comment by alw-bsz** [comment]
Das sollte erledigt sein.
