### ISSUE TITLE
Export der neuen Dokumenttypen in BibTeX und RIS

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1051]

**Comment by alw-bsz** [comment]
Neben der Umsetzung des Mappings für die neuen Dokumenttypen wurden einige Anpassungen und Erweiterungen vorgenommen.

BibTeX:
- Utils für BibTeX in bibtex_utils.xslt zusammengeführt, Einzeldateien (bibtex_authors.xslt, bibtex_editors.xslt etc.) entfernt
- Ausgabe der Artikelnummer
- Mapping des TitleParent in Abhängigkeit vom Dokumenttyp als 'booktitle', 'journal' oder 'series' überarbeitet
- Mapping der ContributingCorporation als 'organization' ergänzt

RIS:
- Ausgabe der Artikelnummer
- Mapping des TitleParent in Abhängigkeit vom Dokumenttyp nach T3 (Serie), JF (Zeitschrift) oder T2 (sonstige, z.B. übergeordnete monografische Einheit) überarbeitet
- Mapping von CreatingCorporation und ContributingCorporation nach 'IN' ergänzt
- Einige Metadaten werden nach Rücksprache mit Citavi zusätzlich in neuere Felder ausgegeben, z.B. eine ISBN sowohl weiterhin nach SN sowie neu nach SB

**Comment by alw-bsz** [comment]
Die Dokumenttyp-spezifschen Stylesheets für Einzeltreffer beim BibTeX-Export (bibtex_article.xslt, bibtex_book.xslt etc.) wurden entfernt. Das allgemeine Stylesheet bibtex.xslt deckt alle Dokumenttypen ab.

**Comment by j3nsch** [comment]
Die Redundanz zwischen den Dateien für die einzelnen Dokumenttypen war nicht ideal und hätte irgendwann bereinigt werden müssen. Die Zusammenführung in eine Datei ist aber auch nicht ideal und muss wieder bereinigt werden. Ich muss noch überlegen, ob das jetzt oder später erfolgen sollte. 

Immer wenn wir eine Datei haben, XSLT oder PHP, die Sonderbehandlungen für einzelne Dokumenttypen umsetzt ist das nicht erweiterbar ohne in diese Dateien, Standarddateien, eingreifen zu müssen. Das haben wir an vielen anderen Stellen schon behoben. Daher ist es unschön, wenn wir es an anderen Stelle neu einführen.

**Comment by alw-bsz** [comment]
Ich plädiere für eine Klassifizierung der Dokumenttypen, vgl. dazu auch meinen Kommentar **https://github.com/OPUS4/application/pull/1171#discussion_r1434874472**

**Comment by j3nsch** [comment]
Sollte erledigt sein.
