### ISSUE TITLE
Bereinigung der XSDs zu XMetaDissPlus

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1063]
In OPUS 4 sind XSDs zu XMetaDissPlus vorhanden, die von der DNB nicht (mehr?) als Teil des XMDP-Pakets ausgeliefert werden. Es ist zu klären, ob diese XSDs aus der OPUS 4-Standardauslieferung herausgenommen werden können. 

Konkret handelt es sich um diese Dateien:
- cc.new.xsd
- ddb.new.xsd
- doi.new.xsd
- hdl.new.xsd
- iso3166.new.xsd
- iso639-2.new.xsd
- mime.new.xsd
- pc.new.xsd
- publicationTypes.xsd
- subject.new.xsd
- thesis.new.xsd
- urn.new.xsd
- xmetadissplus.new.xsd
- metadissplustype.new.xsd

Auffällig ist, dass alle Dateien nach vorhandenen Dateien benannt sind und lediglich um den Zusatz `.new` erweitert wurden.

Umgekehrt gehört die Datei xmetadiss.xsd schon seit längerem zum XMDP-Paket der DNB, sie wurde aber bislang nicht nach OPUS übernommen. Sollte man sie in OPUS 4 nachziehen? Die Formatvalidierung hat das Fehlen der xmetadiss.xsd bislang nicht beanstandet.

**Comment by j3nsch** [comment]
Okay, mir ist erst jetzt aufgefallen, dass wir hier von Dateien unter `tests/resources` reden. Diese Dateien werden im Betrieb nicht verwendet. Sie liegen für die Tests lokal vor, damit sie nicht für jeden Testlauf vom Servern der DNB geholt werden müssen, insbesondere für Validierungen. Zusammen mit `opus4-catalog.xml` sind das also lokale Kopien, eine Art Mirror, für Performanz.

Für die Tests wird das automatisch in `tests/Bootstrap.php` eingerichtet (`XML_CATALOG_FILES`).

**Comment by j3nsch** [comment]
Eine Bereinigung sollte also keine Probleme verursachen.

**Comment by alw-bsz** [comment]
Ok, danke!

Die *.new-xsd-Dateien scheinen nicht von der DNB zu kommen, sondern vor 10 Jahren für die Formatvalidierung in OPUS 4 aufgenommen worden zu sein: 
- https://tickets.zib.de/jira/browse/OPUSVIER-3165 
- https://github.com/tklein23/validate-oai-xmetadissplus/tree/master/cache

Sie werden in opus4-catalog.xml referenziert. Ich vermute, dass das als eine Art "Switch" gedacht war, um mit den Dateien unter der alten DNB-Domain d-nb.de als auch mit jenen unter dnb.de arbeiten zu können, z.B.:

<uri name="http://files.dnb.de/standards/xmetadissplus/xmetadissplus.xsd" uri="xmetadissplus/xmetadissplus.xsd"/>
<uri name="http://www.d-nb.de/standards/xmetadissplus/xmetadissplus.xsd" uri="xmetadissplus/xmetadissplus.new.xsd"/>

<uri name="http://files.dnb.de/standards/xmetadiss/thesis.xsd" uri="xmetadissplus/thesis.xsd"/>
<uri name="http://www.d-nb.de/standards/xmetadiss/thesis.xsd" uri="xmetadissplus/thesis.new.xsd"/>
