### ISSUE TITLE
Personennamen/Autoren verschwinden beim Editieren

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/application#1068]
Wenn man in der Administration ein Dokument editiert, werden die Namen der Personen wie gewohnt angezeigt. Wählt man dann "Hinzufügen" für z.B. eine Schriftenreihe oder Collection wird die Oberfläche kurz neu geladen und beim Hochscrollen werden die Namen des Autoren etc. nicht mehr angezeigt. Nach dem Speichern der Änderungen/des Dokuments ist alles wieder ok.

Dieses Verhalten tritt in Version 4.8 (PHP7) auf, in 4.7.1.2 nicht.

**Comment by j3nsch** [comment]
Bestimmt wieder eine Vergleichsoperation, die mit der neuen Version fehlschlägt. Was anderes kann es eigentlich sein, weil wir hier sonst nichts geändert haben.

**Comment by j3nsch** [comment]
Fixed. Ein `new` musste durch ein `get` ersetzt werden. Die Suche hat eine Weile gedauert. Das lässt sich an dieser Stelle schwer direkt Testen. Die PHTML Datei dazu muss überarbeitet werden, so dass dort keine Objekte mehr instanziiert werden.
