### ISSUE TITLE
Eigenes Logfile für Tasks

### ISSUE THREAD

**Issue by haogatyp** [OPUS4/application#1086]
Die Ausführung der Hintergrund-Tasks soll in einer eigenen Log-Datei protokolliert werden: Ausführung mit Zeitpunkt, Rückmeldung ob die Task erfolgreich ausgeführt wurde oder nicht (die Run-Methoden der Tasks benötigen hierfür einen Rückgabewert: 0 für erfolgreich,  > 0 im Fehlerfall). Das Run-Command soll die Ausführung von Tasks ebenfalls protokollieren.

**Comment by j3nsch** [comment]
Ich habe hier noch mal nachgedacht. Der Runner sollte in die neue Datei `tasks.log` loggen. Wenn man sich mit `LogService::getName('tasks')` einen Logger holt sollte das klappen. Evtl. sollten in der `application.ini` die Defaults für den Logger überschrieben werden. Das wird sich zeigen, wenn es mit den Defaults Probleme gibt.

Das Kommando für die Ausführung von Tasks sollte nicht diesen Logger verwenden (das ist die neue Überlegung), sondern einfach den Standard-Logger, den man über den `LoggingTrait` bekommt. Die Ausgaben sollten dann in `opus-console.log` landen. Evtl. ändern wir das später noch mal, aber das ist ja nur eine Zeile in der man sich dann den Logger über eine andere Funktion holt.

**Comment by j3nsch** [comment]
Im Runner könnte den Tasks-Logger in die Tasks injizieren, so dass die Ausgaben dort ebenfalls in `tasks.ini` und nicht in `opus-console.log` landen.

**Comment by j3nsch** [comment]
Das ist hier sicherlich nicht die wichtigste Aufgabe, aber dadurch, dass sich immer wieder andere Themen dazwischen schieben, fällt auf, dass man Wochen später nicht mehr genau weiß was der aktuelle Stand ist. Es gibt keine Verknüpfung mit einem PR und es gibt auch keinen Kommentar, der den erreichten Zustand beschreibt.
