### ISSUE TITLE
DOI-Import: ORCID wurde nicht vollständig importiert

### ISSUE THREAD

**Issue by bfalkenstein** [OPUS4/application#1091]
Die ORCID kann neben Ziffern und Bindestrichen auch den Buchstaben "X" enthalten. Dies war bisher im RegEx (in doiAssist.js) nicht berücksichtigt. Ich habe es gefixt und einen Pull Request in Branch v4.8.0.1 gestellt. (https://github.com/bfalkenstein/application/commit/06398af2aab9afcf960b7511e18ddc56a4e1058c)

**Comment by j3nsch** [comment]
Danke. Ich sehe keinen PR.

**Comment by bfalkenstein** [comment]
Bitte entschuldige, ich habe Schwierigkeiten mit dieser Github-GUI. Ich weiß nicht, was ich falsch gemacht habe, dass kein PR zustande gekommen ist. Es geht um diesen Commit: https://github.com/OPUS4/application/commit/c8cef03c7ddcb815e01fb8a9c71f4650825f3df2 
Kannst du die beiden "X" in der richtigen Version einfügen? Dieser Bugfix ist völlig unabhängig von allen anderen Änderungen am DOI-Import.

**Comment by bfalkenstein** [comment]
Vielen Dank!
