### ISSUE TITLE
Translations for conference place and conference title (DOI import)

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1095]
### Discussed in https://github.com/orgs/OPUS4/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **vgerlach** August 17, 2023</sup>
So far the translations for the enrichments needed for DOI import need to be set manually. It would be helpful if some translations would be part of OPUS standard: e.g. conference_title, conference_place

Enrichmentconference_title
    de  Konferenztitel
    en  conference title
 
header_Enrichmentconference_title
    de  Konferenztitel 
    en  conference title
 
hint_Enrichmentconference_title
    de  Tragen Sie hier bitte den Konferenztitel ein   
    en  Please enter the conference title
 
button_label_add_one_moreEnrichmentconference_title
    de  Einen weiteren Konferenztitel hinzufügen   
    en  Add another conference title
 
button_label_deleteEnrichmentconference_title
    de  Den letzten Konferenztitel entfernen   
    en  Remove the last conference title
 
groupconference_title
    de  Konferenztitel 
    en  conference title
 
hint_groupconference_title
    de  Konferenztitel 
    en  conference title
 
Enrichmentconference_place
    de  Konferenzort
    en  conference place
 
header_Enrichmentconference_place
    de  Konferenzort
    en  conference place
 
hint_Enrichmentconference_place
    de  Bitte tragen Sie den Konferenzort ein
    en  Please enter the conference place
 
button_label_add_one_moreEnrichmentconference_place
    de  Einen weiteren Konferenzort hinzufügen
    en  Add another conference place
 
button_label_deleteEnrichmentconference_place
    de  Letzten Konferenzort entfernen
    en  Remove last conference place
 
groupconference_place
    de  Konferenzort
    en  conference place
 
hint_groupconference_place
    de  Konferenzort
    en  conference place</div>

**Comment by j3nsch** [comment]
FYI @vgerlach Die Namen der Enrichments haben sich für 4.8.1 noch mal geändert. Übersetzungen für diese neuen Standard-Enrichments sollten mit ausgeliefert werden.

**Comment by alw-bsz** [comment]
Die beiden Enrichmentfelder für Konferenzen würden rückgebaut (s. #1111 ). Die Translations sind nicht mehr erforderlich.
