### ISSUE TITLE
Fehlerhafte Prüfziffervalidierung bei ISSN

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/application#1098]
Die folgende ISSN wird in OPUS 4.7.1.1 und 4.8.0.1 (unter PHP 7) als nicht korrekt eingestuft (Prüfziffer nicht korrekt): 1879-0690
Beim Nachrechnen der Prüfziffer zeigt sich aber, dass die ISSN valide ist:
0*1 + 9*2 + 6*3 + 0*4 + 9*5 + 7*6 + 8*7 + 1*8 = 187 --> Modulo 11 ohne Rest teilbar

Wenn man in OPUS nur die ersten 7 Ziffern eingibt (1879-069) und dann alle möglichen Prüfziffern durchprobiert (0-9 und X) wird nie eine gültige ISSN angezeigt. Es scheint sicher daher um einen Bug zu handeln.

Die Falschmeldung, dass die Prüfziffer ungültig ist, führt dazu, dass die ISSN nicht abgespeichert werden kann.

**Comment by j3nsch** [comment]
Okay, schaue ich mir an, aber das sollte eigentlich nicht das Speichern verhindern. Wir hatten ja eine zwingende Validierung eingeführt, nur um dann Beschwerden zu bekommen, dass auch invalide Eingaben möglich sein müssen, zumindest bei ISBNs. Mir ist im Augenblick nicht klar, ob ISSNs unterschiedlich behandelt wurden. Es sieht ja anscheinend so aus.

**Comment by j3nsch** [comment]
In den Release Notes für 4.6.3 steht drin, dass das Speichern von ungültigen ISBNs und ISSNs nicht verhindert wird. Da stimmt also etwas nicht, mal abgesehen davon, dass `1879-0690` ein gültige ISSN ist.

**Comment by j3nsch** [comment]
Der Validierungscode ist in Common.

**Comment by j3nsch** [comment]
Wir haben ja Unit Tests für die Validierung. Ich vermute, dass Problem tritt auf, weil die Prüfziffer `0` ist und das im Code nicht richtig gehandhabt wird. Eine andere ISSN mit `0` wird vermutlich auch nicht funktionieren.

**Comment by j3nsch** [comment]
Ich habe die ISSN als Testcase in Common die ISSN-Validierungsklasse hinzugefügt. Dort wird sie als gültig erkannt. Das Problem ist also noch ein anderes.

**Comment by j3nsch** [comment]
Reden wir vom Metadaten-Formular in der Administration oder vom Publish-Modul?

**Comment by vgerlach** [comment]
Metadaten-Formular in der Administration.
Wenn man die Issn im Publish-Modul verwendet (eben für DOI-Import getestet), kann man das Dokument problemlos abspeichern.

**Comment by j3nsch** [comment]
Okay, dann steckt der Bug im Javascript.

**Comment by j3nsch** [comment]
Die Javascript-Validierung von ISSNs ist gefixt auf Branch v4.8.0.2. Der Patch-Release erfolgt am kommenden Dienstag, 29. August 2023.

**Comment by j3nsch** [comment]
Der Fix kann/sollte vor dem Release mit dem Branch getestet werden. Wir haben immer noch keine Unit Tests für Javascript.
