### ISSUE TITLE
Unterstützung für aktuelle Solr Version (9.x) unter PHP 8

### ISSUE THREAD

**Issue by extracts** [OPUS4/application#1108]
OPUS 4.8.x sollte unter PHP 8 die Verwendung der aktuellen Solr Version (9.x) unterstützen. Für OPUS 4.8.x Versionen, die mit PHP 7 laufen, muss jedoch weiterhin Solr 7.7.2 unterstützt werden. Abhängig von der PHP Version müsste daher für OPUS 4.8.x mit unterschiedlichen Solr-Versionen getestet werden.

Für das opus4-search Paket behandelt [Ticket 35](https://github.com/OPUS4/opus4-search/issues/35) den Umstieg auf Solr 9.x.

**Comment by extracts** [comment]
Siehe auch [Kommentar von @j3nsch](https://github.com/OPUS4/opus4-search/pull/108#issuecomment-1750432580):

> Die 4.8.x Versionen von OPUS 4 müssen PHP 7 kompatibel sein. Erst ab OPUS 4.9 wird nur noch PHP 8 unterstützt. Das heißt abhängig von der PHP Version müsste mit unterschiedlichen Solr-Versionen getestet werden. In Vagrant können wir uns auf PHP 8 festlegen. Für GitHub geben wir die PHP Version ja in einer "Matrix" an. Da kann man auch noch weitere Parameter spezifizieren (schau mal in die Doku) und so auch die SOLR Version festlegen. Das muss dann an die entsprechenden Skripte usw. weitergereicht werden. Alternativ könnte man schauen, ob die PHP 7 Version von Search auch mit Solr 9 läuft.
> 
> Wenn es keine Lösung mit akzeptable Aufwand gibt, kommt die SOLR 9 Kompatiblität erst mit OPUS 4.9.

**Comment by j3nsch** [comment]
Die PHP 8 Version von OPUS 4 funktioniert mit Solr 9.5. Die Tests für PHP 7 und Solr 7 laufen weiterhin durch. Das sollte funktionieren. In den Release Notes muss vermerkt werden, dass die neue Version Solr 9.5 erfordert.
