### ISSUE TITLE
Flexiblere Abbildung der Sammlungsstruktur auf OAI-Sets

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1110]
Anforderungen ergänzend zu https://github.com/OPUS4/application/issues/769: 

Sets sollen nicht zwingend die Hierarchie einer Sammlung abbilden müssen; z.B. ist die bestehende Struktur für OA-Publikationen sehr unschön. Das übergeordnete Set heißt stets "open_access", auch wenn das Dokument nicht frei zugänglich ist: "open_access:closed_access". Besser wäre, auf die Ausgabe des übergeordneten Sets "open_access" zu verzichten und stattdessen nur "open_access" und "closed_access" auszugeben.

**Comment by j3nsch** [comment]
Danke. Da hier mindestens zwei Probleme beschrieben wurden, habe ich den zweiten Paragraphen ausgelagert (#1113).

**Comment by j3nsch** [comment]
Für die zukünftige Entwicklung (OPUS 4.9, neues Datenmodell) wäre es nützlich zu wissen, ob die Umsetzung von Access-Modellen über Sammlungen so sinnvoll ist. Die Sammlungen sind automatisch in OAI verfügbar und im Browsing. Gibt es noch andere Stellen, wo die Umsetzung als Sammlung nützlich ist? Je mehr Sonderbehandlungen eingefügt werden, desto geringer wird aber der Vorteil einer Umsetzung als Sammlung.

Bei den Instanzen die weitere Sammlungen für verschiedene OA-Modelle anlegen, wird die CollectionRole "open_access" ja eigentlich wie ein Select-Feld verwendet. Ich gehe davon aus, dass ein Dokument nicht gleichzeitig in zwei OA-Modellen verlinkt sein kann, sondern immer nur einem zugeordnet ist. Unter diesen Voraussetzungen gäbe es also die Möglichkeit das wirklich als neues Feld umzusetzen oder diese OA-Sammlungen als Select-Feld in den Formularen zu präsentieren. Eine solche Präsentation wäre mit einem überarbeiteten Publish-Model kein Problem bzw. wäre auch jetzt schon in der Administration machbar. Mit den geplanten Veränderungen bei der Datenmodell-Konfiguration würde so etwas noch einfacher werden. Das geht natürlich über den Rahmen dieses Issues hier hinaus, ist aber für die gewählten Beispielsammlungen relevant. 

Gibt es vielleicht noch andere Sammlungen bei denen eine flexiblere Abbildung nützlich wäre?

**Comment by alw-bsz** [comment]
Aus fachlicher Sicht finde ich die enge Verzahnung der Collections mit den OAI-Sets, d.h. dass zu jeder collection_role ein Set obligatorisch definiert werden muss, da Pflichtfeld, nicht sinnvoll. Die meisten Sammlungen, die die Nutzer für ihre Bedarfe einrichten, erfordern keine Ausgabe als OAI-Set.

**Comment by j3nsch** [comment]
> Aus fachlicher Sicht finde ich die enge Verzahnung der Collections mit den OAI-Sets, d.h. dass zu jeder collection_role ein Set obligatorisch definiert werden muss, da Pflichtfeld, nicht sinnvoll. Die meisten Sammlungen, die die Nutzer für ihre Bedarfe einrichten, erfordern keine Ausgabe als OAI-Set.

Das ist ein weiteres, unabhängiges Thema, oder?

**Comment by j3nsch** [comment]
Die neue SetType-Klasse für die Umsetzung sollte generisch sein, also nur für **opus_access** funktionieren. Sie gibt alle Dokumente einer CollectionRole in einem Set aus, wenn die Dokumente mit einer Sammlung verknüpft sind, die in OAI sichtbar ist. Die Role muss also konfigurierbar sein, damit die Klasse evtl. später auch für andere CollectionRole eingesetzt werden kann.

Bei den Sammlungen einer CollectionRole darf die Root-Collection nicht vergessen werden. Dokumente können mit der Root verknüpft sein. Die Funktion, die alle sichtbaren Sammlungen für eine Role ermittelt, sollte normalerweise die Root-Collection mitliefern. Es wäre gut, wenn das in einem Test festgehalten wird. Also ein Test bei dem mehrere Dokumente der Root und anderen Collections zugewiesen werden und dann geprüft wird, ob alle erwarteten Dokumente erwischt werden.

**Comment by alw-bsz** [comment]
> Vielleicht gibt es ja auch einen besseren Namen für die open_access CollectionRole, wenn sie auch für closed_access und andere Modelle verwendet werden soll.

Es hatten bislang noch Übersetzungen für die Benennung in den Publish-Formularen und die Anzeige in der Frontdoor gefehlt. Ich habe die Begrifflichkeiten "Zugänglichkeit" bzw. "Accessibility" gewählt.

> Gibt es externe Systeme (DNB, OpenAIRE), die von bestimmten Set-Namen abhängig sind?

BASE zieht die Zuordnung eines Datensatzes zum "open_access"-Set zur Einstufung als "im Open Access zugänglich" heran (allerdings nachrangig, d.h. wenn keine Open Access-Lizenz vorhanden ist).

> Ich gehe davon aus, dass ein Dokument nicht gleichzeitig in zwei OA-Modellen verlinkt sein kann, sondern immer nur einem zugeordnet ist.

Ja, das stimmt. Es ist entweder Open Access oder Closed Access. Wenn nach Open Access-Arten unterschieden wird (Grün, Hybrid, Gold etc.), dann wird ein Dokument ebenfalls nur einer Art zugeordnet.

> Gibt es vielleicht noch andere Sammlungen bei denen eine flexiblere Abbildung nützlich wäre?

Bei uns gibt es das in Einzelfällen. Beispielsweise wird in 10 Spezialinstanzen (nicht öffentlich zugänglich) die Ablieferung an die DNB über eine Sammlung gesteuert. Diese hat folgenden Aufbau (A ist die Collection Role, B/C die zweite und D, E, F die dritte Ebene):
```
A - B - D
      - E
      - F
  - C
```
Hier wäre es für uns hilfreich gewesen, wenn bei einer Abfrage des Sets "B" über OAI auch alle Datensätze, die mit den Collections D, E und F verknüpft sind, ausgeliefert werden. Der Fall ist aber schon 2 oder 3 Jahre alt und wir haben das dann anders gelöst. Für A und C wären keine OAI-Sets erforderlich, für D, E und F auch keine eigenen, wenn die Datensätze als Untermenge von "B" ausgegeben würden.

**Comment by alw-bsz** [comment]
> In Offenburg gibt es da auch noch eine weitere untergeordnete Sammlung "closed".

Diese Untersammlung kann ignoriert werden; sie ist m.E. nicht nötig, das übergeordnete "Closed Access" reicht aus.

> Macht es Sinn die "closed_access" Sammlung innerhalb der "open_access" CollectionRole zu haben? Warum kann dafür keine separate CollectionRole verwendet werden? 

Wie Du weiter unten schon schreibst, macht das für das Browsing durchaus Sinn. Zwei getrennte CollectionRoles wären zudem auch bei der Eingabe umständlicher bzw. bei der Einbindung beider ins Publish-Formular für manche User sicher missverständlich.

> Eine "closed_access" Sammlung innerhalb der "open_access" CollectionRole macht mit den verfügbaren Mitteln für das Browsing Sinn. In OAI wird es schwieriger, wenn wir die Sets für "open_access" vereinfachen machen wollen. "open_access" wäre alles was mit der CollectionRole verknüpft ist. Wenn "closed_access" nicht in OAI sichtbar sein soll, dann könnte die Sammlung ausgeblendet werden und alles würde immer noch allgemeinen Regeln folgen. Wenn "closed_access" auch in OAI existieren soll, müssten wir nun diese beiden Sammlung auf unterschiedliche Art und Weise abbilden, Sonderbehandlungen, die dann fest verdrahtet sind. Das wäre einfacher ohne die "closed_access" Sammlung.

Die "Closed Access"-Sammlung muss nicht als Set in OAI ausgegeben werden. Allerdings sollte sie dennoch im Browsing angezeigt werden können.

**Comment by alw-bsz** [comment]
> Letztendlich ist beides machbar, aber wollen die Nutzer wirklich manuell Dokumente zu "closed_access" hinzufügen? Oder gab es bisher einfacher nur keine andere Möglichkeit und das wichtige ist eigentlich die Präsentation im Browsing? Was sind die eigentlichen Anforderungen?

> Was ist mit den Dokumenten, die keiner OA-Prägung zugeordnet sind? Da muss man aktuell rechnen und kann sich auch nicht nur diese anzeigen lassen? Sollte das eine Sammlung "Other" sein oder sollte "Other" für das Browsing, also die Suche, dynamisch generiert werden? 

Beides kann ich nicht einschätzen. Die Nutzung in unseren Repositorien ist sehr unterschiedlich. Ich kann daraus kein Verhalten ableiten, das für alle oder zumindest den Großteil passen würde.

> Ein Präsentation der OA-Sammlungen als Select-Feld in den Formularen, würde auch verhindern, dass ein Dokument mehreren OA-Prägungen zugeordnet wird. Oder ist das eine Möglichkeit?

Es ist entweder Open Access oder Closed Access. Wenn nach Open Access-Arten unterschieden wird (Grün, Hybrid, Gold etc.), dann wird ein Dokument ebenfalls nur einer Art zugeordnet.

**Comment by alw-bsz** [comment]
Eine saubere Abbildung wäre aus meiner Sicht:

Es gibt ein Open Access-Merkmal, das bei Bedarf in die Open Access-Arten (Grün, Gold, Hybrid etc.) untergliedert werden kann (sei es nun eine Sammlung, ein Select-Feld, oder was auch immer). Alle Datensätze, die mit dem Open Access-Merkmal oder den Open Access-Arten gekennzeichnet sind, sollen im OAI-Set "open_access" ausgegeben werden. Die Arten dürfen nicht starr vorgegeben, sondern müssen anpassbar sein.

Datensätze, die nicht mit dem Open Access-Merkmal bzw. dessen Ausprägungen gekennzeichnet sind, könnten dann wahrscheinlich als "Closed Access" eingestuft werden.

Allerdings passt diese Lösung nicht auf die vorhandenen, sehr divergenten Datenbestände. Das könnte man höchstens für neue Instanzen realisieren. Die bestehenden müsste man Stück für Stück prüfen und bereinigen, sofern die Anwender damit einverstanden sind.

**Comment by alw-bsz** [comment]
Wenn es um die zukünftige Ausgestaltung geht, sollten evtl. noch zwei weitere Sachverhalte mit in die Überlegungen einfließen:
- Abbildung des Bereitstellungsrechts, das der DNB an einem abgelieferten Dokument eingeräumt wird (XMetaDissPlus-Element dcterms:accessRights)
- Bildung des dc:rights-Element mit dem info:eu-repo/semantics-Vokabular in oai_dc

**Comment by j3nsch** [comment]
Die Hinweise zur zukünftigen Ausgestaltung scheinen von den Sets wegzugehen und sollten vermutlich als separate Issues festgehalten werden. Der Titel des Issues hier ist etwas generisch, aber der Fokus ist der "open_access" Set. Wir sollten den Titel anpassen, weil wir das Ticket sonst nicht wirklich zu machen können.

**Comment by j3nsch** [comment]
Es gibt jetzt ein System mit dem Klassen für neue OAI-Sets implementiert und zur Konfiguration hinzugefügt werden können. Das System funktioniert erst einmal und damit wurde die neue Variante des **open-access** Sets umgesetzt und auch die neuen Sets für `PublicationState`. Das System muss später noch weiter ausgebaut bzw. bereinigt werden, am Besten im Zusammenhang mit der Auslagerung des OAI-Codes in ein separates Composer Package.

**Comment by alw-bsz** [comment]
Im Prinzip tut's, was es soll - es werden auch die Dokumente in untergeordneten Sammlungen als Teil des Sets "open_access" ausgegeben. Danke, @j3nsch .

Unklar ist mir noch, wie ich die Dokumente der Untersammlung "closed_access", die wir in unseren Repositorien sehr oft haben, aus dem Set "open_access" rausnehmen kann. Es hat nichts gebracht, die Untersammlung auf nicht sichtbar zu setzen; außerdem besteht dann das Problem, dass die Untersammlung auch im Browsing nicht sichtbar ist.

**Comment by j3nsch** [comment]
Hat die Sammlung einen OAI-Subset-Namen?

**Comment by alw-bsz** [comment]
Nein, den sie hat nicht. Braucht sie einen?

**Comment by j3nsch** [comment]
Danke, nein, war nur so ein Gedanke. Es macht aber keinen Sinn, wenn OAI-Namen notwendig wären. Man müsste sonst allen Sammlung einen OAI-Namen geben, um sie sichtbar in OAI zu machen, nur damit dann der Name ignoriert wird, weil alle Dokumente in einem einzigen Set abgebildet werden.

Was mich dahin zurück bringt, dass wir hier viel Aufwand im OAI Modul betreiben, um ein "Feature im Browsing" zu ermöglichen. Der Wunsch alle Sammlungen einer CollectionRole in einem Set abzubilden ist nachvollziehbar. "Closed Access" Dokumente mit der "Open Access" CollectionRole zu verknüpfen, ist nicht verständlich, bis man dahin kommt, dass man damit ein "Feature im Browsing" ermöglichen will. 

Es wäre einfacher gewesen das Feature für das Browsing auf die Wunschliste zu packen und umzusetzen ohne dafür das OAI-Modul anpassen zu müssen. Was wäre denn jetzt die "schnelle" OAI Lösung? Ein weiteres Feld, um zwischen Sichtbarkeit im Browsing und Sichtbarkeit in OAI unterscheiden zu können? Ein Feld, dass dann an den verschiedensten Stellen eingepflegt und berücksichtigt werden muss? Alles, um "Arbeit" zu sparen, indem man einfach "Closed Access" Dokumente in die "Open Access" Sammlung CollectionRole packt?

**Comment by j3nsch** [comment]
Ich kann aber bei mir Nachvollziehen, dass ein Dokument, in einer unsichtbaren Sammlung, mit im Set auftaucht. Ich schaue mir an woran das liegt und füge weitere Tests hinzu. Das Browsing "Problem" ist davon unabhängig.

**Comment by j3nsch** [comment]
Dokumente in Sammlungen, die nicht **Visible** sind, werden nun nicht mehr mit ausgegeben. Dafür gibt es jetzt auch einen Test. Da hat noch etwas gefehlt.

**Comment by j3nsch** [comment]
Noch mal als Nachtrag zu diesem Issue. Die beschriebenen Anforderungen zum **open_access** Set sind ein Ticket, das erledigt werden kann. Es gibt Kriterien für die Erfüllung. Eine "flexiblere Abbildung der Sammlungsstrukturen" hat keine konkreten Kriterien an denen fest gemacht werden kann, dass das Ziel erreicht wurde. Der Mapping-Mechanismus, der jetzt für **open_access** umgesetzt wurde, kann auch für andere CollectionRoles verwendet werden. Durch das Refactoring des OAI-Modules, lassen sich weitere Mappings durch neue Klassen umsetzen. Ist das ein ausreichender Grad an "Flexibilität". Das wird sich zeigen, wenn sich weitere Anforderungen ergeben. 

Das Browsing-Thema für die OA-Sets ist erst später, als unbeabsichtigte Konsequenz der Änderungen, hier aufgetaucht.
