### ISSUE TITLE
Behandlung von Konferenzen im DOI-basierten Metadaten-Import

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1111]
Die beiden Enrichment-Felder für Konferenzen sind versehentlich mit dem Crossref-Import in OPUS 4.8 hineingekommen. Die Enrichments sollen rückgebaut, d.h. aus der Standardauslieferung herausgenommen werden. Konferenzen sollen stattdessen analog zu den Vorgaben in bibliothekarischen Regelwerken als Körperschaften behandelt werden (ContributingCorporation). Vorteil: sie werden standardmäßig auf der Frontdoor angezeigt und bei den Exporten berücksichtigt.

**Comment by alw-bsz** [comment]
Vgl. auch https://github.com/OPUS4/opus4-bibtex/issues/43

**Comment by j3nsch** [comment]
Die Änderungen wurden in den Release übernommen.

**Comment by alw-bsz** [comment]
Das Vorgehen wurde geändert, es wurden weitere Enrichment-Felder für Konferenzen definiert und das Mapping beim DOI-basierten Metadaten-Import angepasst, s. #1196
