### ISSUE TITLE
Rückbau der Dokumenttyp-spezifischen BibTeX-Einzeltrefferexporte

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1112]
Die Dokumenttyp-spezifischen BibTeX-Einzeltrefferexporte sind aus meiner Sicht nicht nötig. Ich habe sie daher nicht für die neuen Dokumenttypen angepasst. Der Listenexport arbeitet mit _einem_ Stylesheet, das für alle Dokumenttypen gilt. Das funktioniert nach meinem Kenntnisstand problemlos. Analog kann es auch für den Einzeltrefferexport gehandhabt werden.

**Comment by alw-bsz** [comment]
Vgl. auch https://github.com/OPUS4/opus4-bibtex/issues/43

**Comment by j3nsch** [comment]
Hier wäre es ideal, wenn dazu ein PR gemacht wird. Es wäre gut, wenn Commits mit den entsprechenden Issues verknüpft wären, um leichter sehen zu können was wofür geändert wurde.

**Comment by alw-bsz** [comment]
Löschung der Dokumenttyp-spezifischen XSLTs in PR https://github.com/OPUS4/application/pull/1171 (https://github.com/OPUS4/application/pull/1171/commits/6019e04a98b2aaf5618b08347a2721f1554c15cb)

**Comment by j3nsch** [comment]
Die Änderungen wurden in den Release übernommen. Das Zusammenführen der XSLTs für die einzelnen Dokumenttypen führt dazu, dass wieder eine zentrale Datei für neue Typen angepasst werden muss. Neue Typen können nicht dezentral hinzugefügt werden. Die alte Lösung, mit redundantem XSLT, war ebenfalls nicht ideal. Die optimale Lösung muss später umgesetzt werden. Dabei müssen die Fallunterscheidung basierend auf Dokumenttypen durch eine Prüfung auf Eigenschaften bzw. Optionen eines Types umgestellt werden und/oder die optionale Verwendung einer zusätzlichen XSLT Datei für eine Dokumenttyp ermöglicht werden. Im OAI-Modul gibt es ein zentrales Basis-XSLT, dass dann für die einzelnen Formate durch zusätzliche XSLT-Dateien erweitert wird.
