### ISSUE TITLE
Ausblenden von "Nicht-Collections" im Browsing

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1115]
Collections können beim Browsing ausgeblendet werden, die zuletzt veröffentlichten Dokumente, Dokumenttypen und Jahre jedoch nicht. Das sollte konfigurierbar gemacht werden.

**Comment by j3nsch** [comment]
Das klingt wie eine klare Anforderung, die auch nicht so schwer umsetzbar sein sollte, wenn Luft ist.
