### ISSUE TITLE
Dependency caching for SOLR in GitHub Actions workflow

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1125]
Für jeden Build wird Apache Solr heruntergeladen. Das sollte vermieden werden. Es muss geprüft werden, ob es möglich ist die Downloads nur bei Bedarf durchzuführen. Dabei sollte auch klar sein, wie der Cache gelöscht werden kann. 

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by j3nsch** [comment]
Wie woanders schon gesagt, beim Umstieg auf SOLR 9, können die Download-Zeiten beträchtlich sein. Wenn das für SOLR klappt, können wir vielleicht etwas ähnliches auch für Composer, `.vendor` machen.

**Comment by j3nsch** [comment]
Mir ist egal wer sich das anschaut, aber es beeinflusst die Effektivität der Entwicklung und ist daher wichtig.

**Comment by j3nsch** [comment]
Für einen Vagrant-VM Build hat der Download jetzt gerade 30 Minuten gedauert.

**Comment by extracts** [comment]
Die Download Geschwindigkeit ließe sich wohl deutlich verbessern, wenn man https://dlcdn.apache.org/solr/solr/ verwendet (siehe dazu auch [Kommentar zu 108](https://github.com/OPUS4/opus4-search/pull/108#issuecomment-1757648746)).

**Comment by extracts** [comment]
Zeitlicher Unterschied für den GitHub Workflow Step "Install Solr 9.4.0":
mit alter Download URL: [knapp 18 Minuten](https://github.com/OPUS4/application/actions/runs/6638598436/job/18035266677)
mit neuer Download URL: [32 Sekunden](https://github.com/OPUS4/application/actions/runs/6643573478/job/18050908421)

**Comment by j3nsch** [comment]
Gut, das werden wir dann auch für Vagrant ändern. Trotzdem ist es sinnvoll das Caching zu testen und gegebenenfalls einzusetzen.

**Comment by j3nsch** [comment]
SOLR 7.7.3 wird weiterhin über die Archive-URL heruntergeladen. Die aktuelle Version wird über das CDN herunter geladen. Im CDN ist nur die aktuelle Version verfügbar. Das heißt sobald eine neue Version veröffentlicht wird, brechen unsere Builds. Das ist also noch nicht ideal. Caching würde da auch erst einmal helfen. 

Vielleicht kann das Skript auch so umgesetzt werden, dass das Archive als Fallback verwendet wird, wenn die CDN URL nicht funktioniert. Oder löst der Resolver, "closer.lua" das Problem bereits? Es funktioniert für 9.3.0.

**Comment by extracts** [comment]
> Oder löst der Resolver, "closer.lua" das Problem bereits?

Ja, soweit ich es verstehe und auch getestet habe, funktioniert der Resolver für den aktuellen Release als auch für ältere Release-Versionen. Allerdings werden ältere Release-Versionen stets über das langsamere Archiv heruntergeladen.

**Comment by j3nsch** [comment]
Erläutere hier mal bitte noch in 2 Sätzen die Funktion. Was passiert, wenn die Versionsnummer von Solr geändert wird?

**Comment by extracts** [comment]
Das `tests/bin/install_solr_docker.sh` Skript lädt die per `--version` Parameter angegebene Solr Version (falls sie noch nicht im `./downloads` Verzeichnis existiert) herunter und speichert sie im `./downloads` Verzeichnis.

Wird die Solr Version im GitHub Workflow geändert, so lädt das Skript diese Solr-Version ebenfalls in das `./downloads` Verzeichnis herunter.

Am Ende eines erfolgreich durchgelaufenen Workflows werden die Inhalte des `./downloads` Verzeichnisses (für bis zu 7 Tage) gecached. Bei einem nächsten Durchlauf des Workflows werden (falls vorhanden) die gecachten Inhalte des `./downloads` Verzeichnisses wieder hergestellt, wodurch das `tests/bin/install_solr_docker.sh` Skript den Download der aktuell verwendeten nicht erneut durchführen muss.

**Comment by j3nsch** [comment]
Zwei Sätze? :-) Danke. Ich denke, der wichtige Punkt, der fehlt, ist, ob die beiden Solr-Dateien im gleichen Cache landen und damit die alte Datei für immer aufgehoben wird oder ob für unterschiedliche Versionen unterschiedliche Caches verwendet werden.

**Comment by extracts** [comment]
Soweit ich die Doku verstehe, existiert für denselben Cache Key (im selben Branch) nur ein Cache. D.h. die beiden Solr-Dateien landen (mit unterschiedlichen Namen) im selben Cache.

**Comment by extracts** [comment]
Ja, das ist korrekt, der `Key` basiert aktuell auf der Solr Version.

**Comment by j3nsch** [comment]
Gut.
