### ISSUE TITLE
Neuer Dokumenttyp MusicalNotation / Identifier ISMN 

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1131]
Der Dokumenttyp MusicalNotation (Partituren etc.) wurde auf Kundenanforderung in einigen Instanzen implementiert. Es handelt sich um einen standardisierten Typ aus dem Gemeinsamen Vokabular, Da es eine Nachfrage danach gibt, soll er Teil des Kanons an Standard-Dokumenttypen in OPUS 4 werden.

Für diesen Dokumenttyp wird die ISMN (International Standard Musical Number) als weiterer Identifier benötigt. Sie dient der weltweiten Kennzeichnung von Musiknotationen in gedruckter oder digitaler Form.

**Comment by j3nsch** [comment]
Okay, ich mach mir mal Gedanken und dann fügen wir den Identifier-Typ **ISMN** hinzu. 

Ich bin sowieso dafür die Liste konfigurierbar zu machen. Das wird vermutlich nicht jetzt passieren, weil noch zu viel Sonderbehandlungscode vorhanden ist, für einzelne Typen. Wenn klar ist wie mit DOI, URN usw. im neuen Code umgegangen werden kann, ist auch die Konfigurierbarkeit kein Problem mehr. Das ist etwas was vor OPUS 4.9 passieren muss, aber evtl. erst nach 4.8.1. Es hängt davon, ab wie lange der ganze Rest noch braucht.

**Comment by j3nsch** [comment]
In Issue OPUS4/framework#206 geht es darum die im Datenbankschema festgelegten Identifier-Typen erweiterbar zu machen.
