### ISSUE TITLE
Benennung von ORCID und ORCID iD

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1132]
Die Standard-Texte zu ORCID bzw. ORCID iDs sind teilweise fehlerhaft. Die ORCID iD wird unterschiedlich und teilweise falsch bezeichnet. Die Angaben sollten korrigiert und die ORCID iD einheitlich und korrekt bezeichnet werden.

**Comment by j3nsch** [comment]
Danke. Da Ihr am Besten wisst was korrigiert werden sollte, macht mal bitte einen PR dafür und dann kann das mit in die 4.8.1 einfließen.

**Comment by alw-bsz** [comment]
Die Bezeichnungen wurden korrigiert und vereinheitlicht
