### ISSUE TITLE
Neuen Identifier-Typ ISMN in Application integrieren

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1134]
Es wurde ein neuer Identifier-Typ ISMN hinzugefügt. Dieser ist für ein neuen Dokumenttyp notwendig (siehe #1131). Für den neuen Typ müssen Übersetzungen usw. hinzugefügt werden.

**Comment by alw-bsz** [comment]
@j3nsch Ich kann den Identifier ins Publish-Formular einbauen, allerdings wird die Eingabe nicht in der Datenbank gespeichert. Es kommt keine Fehlermeldung, alle anderen Daten werden korrekt gespeichert. Bei der Eingabe der ISMN direkt in der Dokumentenverwaltung wird sie gespeichert. Fehlt da noch was? (S.a. https://github.com/alw-bsz/application/tree/ismn1131)

**Comment by j3nsch** [comment]
Danke, für den Hinweis @alw-bsz, vermutlich spielt und das Publish-Formular wieder Streiche. Ich schau mal, wo die erlaubten Identifier-Typen noch definiert sind. Vermutlich gibt es da keine extra Fehlerbehandlung, weil die Typen bisher fest verdrahtet waren, und es wird einfach verschluckt.

**Comment by alw-bsz** [comment]
@j3nsch Jetzt funktioniert's, danke!

**Comment by j3nsch** [comment]
Ich gehe davon aus, dass das erledigt ist.
