### ISSUE TITLE
Mapping mehrerer OPUS 4-Dokumenttypen auf einen OAI-Set (DC-Type) muss berücksichtigt werden

### ISSUE THREAD

**Issue by haogatyp** [OPUS4/application#1148]
Manche OPUS-Dokument-Typen werden dem gleichen DC-Type zugeordnet, weil in OPUS 4 eine feinere Aufteilung verwendet wird. OPUS 4-Instanzen können auch weitere, parallele Dokumenttypen definieren, um unterschiedliche Defaultwerte zu definieren. Für die OAI-Sets muss sichergestellt werden, dass hierfür ein entsprechendes Mapping bei der Ermittlung der Dokumente zu einem Set stattfindet. Entsprechend müssen die Test hierfür erweitert oder angepasst werden.

Die Standardkonfiguration von OPUS 4 mapped **diplom**, **examen** und **magister** auf den DC-Type **MasterThesis**. Das ist schon lange so. Für die Ermittlung der Dokumente im Set wurde aber, der DC-Type verwendet. Das kann also nicht richtig funktioniert haben. Die neuen Tests sollten diesen Bug zuerst nachweisen, bevor er gefixt wird.

**Comment by j3nsch** [comment]
@alw-bsz Bei der Suche in der Datenbank nach den Dokumenten eines Doc-Type-Sets wurde anscheinend bisher und damit vermutlich schon immer der DC-Type als "DocumentType" verwendet. 

    $finder->setDocumentType($setarray[1]); // subset part of OAI SetSpec aka a DC-Type

Das kann also nicht funktioniert haben, auch nicht für "einfache" Sets, wenn der DC-Type und der OPUS 4-Type unterschiedliche Namen hatten. Ich vermute diese Sets werden von niemanden verwendet, sonst hätte das doch auffallen müssen. Wir erweitern jetzt auf jeden Fall die Tests.

**Comment by j3nsch** [comment]
Wir sollten Unit-Tests für das Mapping in beide Richtungen haben, insbesondere für das oben genannte Beispiel in der Standardkonfiguration mit "MasterThesis". 

Und dann wären noch Controller-Tests gut, die prüfen, ob die gelieferten Dokumente stimmen. Evtl. kann man das auch auf der Ebene der DocumentTypeSets-Klasse testen.

**Comment by alw-bsz** [comment]
> @alw-bsz Bei der Suche in der Datenbank nach den Dokumenten eines Doc-Type-Sets wurde anscheinend bisher und damit vermutlich schon immer der DC-Type als "DocumentType" verwendet.
> 
> ```
> $finder->setDocumentType($setarray[1]); // subset part of OAI SetSpec aka a DC-Type
> ```
> 
> Das kann also nicht funktioniert haben, auch nicht für "einfache" Sets, wenn der DC-Type und der OPUS 4-Type unterschiedliche Namen hatten. Ich vermute diese Sets werden von niemanden verwendet, sonst hätte das doch auffallen müssen. Wir erweitern jetzt auf jeden Fall die Tests.

Danke für die Info! Das Einschränken auf die Dokumenttypen per Set spielt in der Praxis wohl wirklich keine große Rolle. Zumindest die "großen Harvester" wie DNB oder BASE arbeiten meines Wissens im Regelfall nicht damit.

**Comment by j3nsch** [comment]
Sollte erledigt sein.
