### ISSUE TITLE
Choose-Block für den XSLT-Mode am Ende von oai-pmh.xslt vereinfachen.

### ISSUE THREAD

**Issue by haogatyp** [OPUS4/application#1149]
In der Datei oai-pmh.xslt git es ganz am Ende einen Choose-Block, in dem entsprechend des aktuellen Metadata-Prefixes ein XSLT-Mode für <xsl:apply-templates> ausgewählt wird. Da es die Prefixes jetzt aber konfigurierbar sind dürfen an dieser Stelle keine expliziten Prefix-Namen mehr verwendet werden. Der Block sollte idealerweise durch ein einziges  <xsl:apply-templates> erstezt werden.

**Comment by j3nsch** [comment]
Der Mode soll ja zwischen den Formaten unterscheiden, damit die gleichen Elemente im OPUS-XML unterschiedlich verarbeitet werden können. Da wir nur noch das XSLT für jeweils ein Format dynamisch inkludieren, sollte der Mode nicht mehr notwendig sein. Das würde auch mehr Sinn für neue Formate machen, wenn da nicht bei jedem Template-Element auch noch der Mode für das Format angegeben werden muss.

**Comment by j3nsch** [comment]
Der Branch-Name, *'bug1149'', war von mir falsch gewählt. Es war ja kein Bug.

Damit das Mode-Attribut aus den Prefix-XSLT-Dateien entfernt werden konnte, musste im Main-XSLT, `oai-pmh.xslt`, ein Mode eingeführt werden. Dort wird das Element **Opus_Document** verarbeitet, dass auch im Prefix-XSLT auftaucht und für jedes Format unterschiedlich verarbeitet wird. Im Main-XSLT wird jetzt der Mode **oai-pmh** verwendet.

Die Änderungen sind im Branch **bug1149**.

**Comment by j3nsch** [comment]
Das XSLT für Marc21 wird auch im Export verwendet. Dort musste ebenfalls ein Konflikt für `Opus_Document` aufgelöst werden. Jetzt sollte alles durchlaufen.

**Comment by j3nsch** [comment]
Mode-Attribute im XSLT für die Prefix-Formate sind nicht mehr notwendig.
