### ISSUE TITLE
Datei "config.xml" wird überschrieben und Einstellungen gehen verloren

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1158]
Die Datei `config.xml` ist für Optionen gedacht, die in der Administration editiert werden könnten. Es gibt momentan zwei Stellen wo das geschieht, in den allgemeinen Settings und in den Einstellungen für die Sprachen. An beiden Stellen wird eine komplett neue Datei geschrieben, so dass die Einstellungen auf jeweiligen anderen Seite verloren gehen.

Setzt man die Anzahl der Suchergebnisse hoch und ändert dann die aktiven Sprachen, bleibt nur die Einstellung für die aktiven Sprachen in der Datei.

Vor dem Speichern sollte die existierende Datei gelesen und Änderungen übernommen werden.

**Comment by j3nsch** [comment]
Die Anpassungen an der Konfiguration, die in der Administration vorgenommen werden können, sollten in die Datenbank wandern, so wie das für die Übersetzungen der Fall ist. Ein Löschen der Datenbank würde dann wie "Reset" alles auf die Defaultwerte zurück setzen. 

Dafür müssen aber neue Möglichkeiten in der Datenbank geschaffen werden und dieser Bug hier ist vermutlich relativ einfach zu fixen. Daher sollte die Migration in die Datenbank erst einmal noch warten, bis andere, größere Themen, wie der Doctrine-Umstieg bewältigt sind.

**Comment by j3nsch** [comment]
Problem ist behoben. Ein Refactoring des Systems sollte auf die Einführung von Laminas warten, da sich dann die Konfigurationsmechanismen sowieso ändern werden.

**Comment by alw-bsz** [comment]
Wann wird die config.xml denn erstellt? Auf GitHub ist sie nicht im application/configs-Verzeichnis, und in den Vagrant-Maschinen fehlt sie ebenfalls.

**Comment by j3nsch** [comment]
Die Datei `config.xml` wird erzeugt, wenn in der Administration Konfigurationsoptionen verändert werden. Das Laden der Konfiguration erfolgt in der Reihenfolge `application.ini` (Defaults), `config.ini` (lokale Konfiguration), `config.xml` (Konfiguration in Admin-UI).

Die Datei `config.xml` wird evtl. später in die Datenbank verlagert, so wie es für die Übersetzungen geschehen ist.
