### ISSUE TITLE
Dokumenttyp DOI-Import bei manueller Befüllung ohne Dokumenttypzuordnung

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/application#1165]
Bei Verwendung des Dokumenttyps DOI-Import (doi.xml) ohne Nutzung der Funktion "Metadaten von Crossref holen" - d.h. wenn man die Pflichtfelder des Dokumenttyps manuell befüllt - erhält das abgespeicherte Dokument keinen Dokumenttyp.

**Comment by j3nsch** [comment]
Der Typ **DOI-Import** ist nicht dafür gedacht Dokumente manuell einzugeben. Warum wird das gemacht? Der **DOI-Import**-Typ ist ja im Prinzip der **All**-Typ, den wir zu Testzwecken haben. Die Verwendung macht eigentlich nur Sinn, wenn man etwas eingeben möchte, dass in dem richtigen Dokumenttyp fehlt. Man muss sich ja immer noch für einen Typ entscheiden. 

Wir könnten sicherlich den Save-Button sperren bis ein Import erfolgt ist. Oder man könnte dafür sorgen, dass der Typ manuell überschrieben werden kann. Ich weiß nicht, ob sich da für 4.8.1 etwas geändert hat.

Das der Import momentan ein Dokumenttyp ist, liegt daran, dass das die "einfachste" Möglichkeit der Umsetzung mit dem alten Publish-Modul war. In der (irgendwann) kommenden neuen Version wird das nicht mehr der Fall sein. Der Typ wird also wieder verschwinden. Welches andere Problem wird hier versucht mit dem **DOI-Import**-Typ zu umgehen?

@alw-bsz @bfalkenstein FYI

**Comment by j3nsch** [comment]
@alw-bsz Kommentiert hier mal bitte. Das "Problem" besteht weiter, da der CrossRef-Button ja nicht verwendet werden muss, Auch Issue #1207 befasst sich mit dem Thema. Der Redirect löst das Problem noch nicht. Für den Augenblick bin ich dafür das zu ignorieren. Der Prozess sollte später so angepasst werden, dass das Editieren der Metadaten erst nach dem Import von CrossRef möglich ist.

Das wäre ein WON'T FiX.

**Comment by j3nsch** [comment]
Eine Alternative zum WON'T FIX wäre die Möglichkeit den Dokumenttyp im Formular editierbar zu machen, so dass Nutzer das automatische Mapping überschreiben können. Damit wäre das Problem hier auch gefixt. @alw-bsz Was meint Ihr? Das müsste am BSZ umgesetzt werden. Vielen Dank!

**Comment by alw-bsz** [comment]
Boris hat eine Lösung gefunden, mit der alle Felder außer DOI und den beiden Buttons zum Importieren der Metadaten und Abbrechen des Formulars gesperrt sind, bis ein erfolgreicher Datenimport von Crossref erfolgt ist. Ich bringe das noch als PR ein.
