### ISSUE TITLE
Darstellung der Verbund-ID auf der Frontdoor

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1166]
Die Verbund-ID soll auf der Frontdoor angezeigt werden. Es soll möglich sein, in der Konfiguration die URL auf den Verbund-Katalog zu hinterlegen. Ist diese vorhanden, soll die Verbund-ID auf der Frontdoor auf die korrespondierende Aufnahme im Verbund-Katalog verlinken.

**Comment by alw-bsz** [comment]
Ich habe das schon umgesetzt. Dieses Issue ist daher vor allem als Doku für den kommenden PR gedacht.

**Comment by alw-bsz** [comment]
Die Übersetzung des Feldes wird auf "Verbundkatalog-ID" geändert, damit auch für nicht bibliothekarisch vorgebildete Anwender klar ist, dass es sich um einen Katalog-ID handelt.

**Comment by j3nsch** [comment]
Das sieht gut aus. Ich hätte `baseUrl` anstelle von `requestUrl` verwendet, weil wir das bei anderen URL Optionen so gemacht haben, z.B. `pubmed.baseUrl`. Es spielt aber nicht wirklich eine Rolle.

**Comment by j3nsch** [comment]
Ja, verstehe ich, aber das liegt ja an der URL, nicht an der Funktion aus Sicht von OPUS 4. Die URL könnte sich ändern und  wie die anderen Base-URLs aussehen. Wie bei allen anderen Base-URLs wird hinten noch was dran gehängt, um sie spezifisch zu einem Dokument zu machen. Das die Katalog-URL dabei momentan zusätzliche, feste Parameter braucht, ist egal.

Wir ändern das jetzt nicht, weil ich mir im Augenblick ziemlich sicher bin, dass sich diese Konfiguration mit OPUS 4.9 oder danach noch mal ändern wird und ich noch nicht genau sagen kann wie das aussehen wird. Wir konfigurieren hier ja einen Identifier und das sollte später nicht mehr auf der obersten Ebene passieren. Die Option wird länger werden. :-)
