### ISSUE TITLE
Löschen mehrerer Dokumente nur nach Zwischenspeichern möglich

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/application#1174]
In der OPUS-Version 4.8.0.2 unter PHP7 und in Version 4.8.1 unter PHP8 muss man, um mehrere Dateien zu einem OPUS-Metadatensatz löschen zu können, nach dem Löschen jedes Dokuments speichern, bevor man die nächste Datei entfernen kann.

Konkret: man wählt einen Datensatz in OPUS aus, der mehrere Dateien enthält. Man drückt auf Entfernen bei einer Datei und bestätigt dies mit Klick auf Ja. In der Ansicht verschwindet diese Datei - was korrekt ist. Danach wählt man die nächste Datei zum Entfernen aus und bestätigt das Löschen. Nun ist die aktuelle Datei aus der Ansicht gelöscht, aber die vorherige Datei ist wieder da.

Der Workaround, um mehrere Dateien zu löschen - aus welchen Gründen auch immer - ist: nach dem Entfernen einer Datei immer Speichern und dann erst die nächste Datei löschen. Dies ist aber nicht sehr nutzerfreundlich.

**Comment by j3nsch** [comment]
Gefixt für Patch Release OPUS 4.8.0.4.

**Comment by vgerlach** [comment]
Danke, hab's getestet - macht was es soll :-)
