### ISSUE TITLE
OPUS ändert Zugriffsrechte auf Dateien beim Freischalten über "review"

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1176]
Ändert man die Zugriffsrechte einer Datei vor dem Freischalten eines Datensatzes und entzieht das im Default belegte "Guest"-Recht, fügt OPUS das "Guest"-Recht bei der Freischaltung wieder hinzu. Andere Rechte bleiben davon nach meinen bisherigen Tests unberührt, d.h. gesetzte Rechte bleiben erhalten, nicht gesetzte Rechte werden nicht hinzugefügt.

Der Bug tritt nur beim Freischalten über das "review"-Modul auf. Freischalt-Vorgänge über "documents" sind davon nicht betroffen.

**Comment by j3nsch** [comment]
@stconradr Ich denke wir hatten das bzw. ein verwandtes Thema schon mal. Weißt Du noch was dazu? 

Ich vermute, dass dieses Verhalten damals eine bewusste Entscheidung war. Ist das etwas neues oder verhält sich OPUS 4.7 auch schon so?

**Comment by alw-bsz** [comment]
Ich habe mit 4.7.1.2 und 4.8.1 getestet. Das Verhalten ist in beiden Versionen identisch.

**Comment by j3nsch** [comment]
Ja, das ist kein Bug, der sich durch PHP 8 Änderungen eingeschlichen hat. Das Verhalten ist vermutlich so alt, wie das Review-Modul. Was hättet Ihr denn gerne für die Zukunft und passt das für alle?

**Comment by j3nsch** [comment]
Bei einer Änderung müssen wir dann auch das Verhalten für den Zugriff auf Dateien kontrollieren. Der Gedanke hier war ja anscheinend, dass "Guest"s erst mit dem Freischalten Zugriff bekommen.

**Comment by alw-bsz** [comment]
Die Rechte sollten so bleiben, wie sie sind. Falls die Bibliothek die Rechte vor dem Freischalten ändert, sollte das so übernommen werden. OPUS sollte keine Rechte entziehen oder hinzufügen.

**Comment by alw-bsz** [comment]
Es ist halt irritierend, dass sich das Freischalten über "documents" anders verhält als mittels "review".

**Comment by alw-bsz** [comment]
Falls der Aufwand übersichtlich ist, könnte man evtl. in der application.ini bzw. config.ini konfigurierbar machen, ob OPUS das "Guest"-Recht automatisiert setzt oder nicht.

Falls es Workflows in den Bibliotheken gibt, auf die das bisherige Verhalten ausgelegt ist, könnte diese das dann weiter nutzen. Unter unseren Anwendern ist mir eine solche Vorgehensweise (Dokument wird ohne "Guest"-Recht eingestellt und erst beim Freischalten vergeben) aber nicht bekannt,

**Comment by j3nsch** [comment]
Die Funktion in der Dokumentenverwaltung ändert einfach den Status eines Dokuments. Das Freischaltmodul war eine spezielle Entwicklung für eine einzelne Instanz (mehr als 12 Jahre her). Das Modul wurde später im Standard behalten. Das Modul hatte immer zusätzliche Funktionen.

Gibt es Instanzen bei denen Guest immer manuell gesetzt wird, weil nicht bekannt ist, dass das auch automatisch passiert? Wo also jetzt zusätzliche Arbeitsschritte ausgeführt werden?  

In jedem Fall können wir das Verhalten nicht einfach ändern, weil unklar ist, ob das jemand so nutzt. Wir können es konfigurierbar machen. Die technische Seite ist nicht schwer, aber das ist nur eine Zwischenlösung, die später weitere Arbeiten erfordert. Es ist nicht unwahrscheinlich, dass die Option später noch mal geändert werden, weil wir hier auf mehrere Altlasten treffen. 

@alw-bsz Leg bitte ein Ticket für ein "Einheitliches Verhalten beim Freischalten" an. Das ist ein separates Thema. Dafür müssen die Code-Teile für das Freischalten zusammengeführt werden. Alles was wir da jetzt machen, wäre Code, der später noch mal überarbeitet werden muss, weil wir ja eigentlich dabei sind das gesamte Framework zu ersetzen und sich damit die Grundlagen für eine sinnvolle Umsetzung verändern werden. 

Ich werde die Option mit in den nächsten Patch-Release 4.8.0.4 aufnehmen. Es wäre gut wenn im Issue mehr Informationen stehen würden, die helfen die Dringlichkeit zu beurteilen. Ist es eine Sache, die jetzt nebenbei aufgefallen ist, oder etwas, das für beträchtlichen Mehraufwand sorgt. Warum erst jetzt? Es ist immer sinnvoll solche Probleme zu melden, aber ich werde sie bald wieder ignorieren müssen, weil unklar ist, was morgen oder übermorgen gemeldet wird und wir mit den eigentlich anstehenden Aufgaben vorankommen müssen.

**Comment by j3nsch** [comment]
Die neue Option lautet

    workflow.stateChange.published.addGuestAccess = 1
    
und wirkt sich nur im Review-Modul aus.

**Comment by alw-bsz** [comment]
Danke @j3nsch !

> Gibt es Instanzen bei denen Guest immer manuell gesetzt wird, weil nicht bekannt ist, dass das auch automatisch passiert? Wo also jetzt zusätzliche Arbeitsschritte ausgeführt werden?

Mir ist keine solche Instanz bekannt, ich kann es aber auch nicht mit vollständiger Sicherheit ausschließen.

> Es wäre gut wenn im Issue mehr Informationen stehen würden, die helfen die Dringlichkeit zu beurteilen.

Das Verhalten ist jetzt einem Anwender aufgefallen. In der Instanz hatten rund 90 Dokumente bzw. deren Dateien die falschen Zugriffsrechte, weil nicht bekannt war, dass das "Guest"-Recht automatisiert gesetzt wird. Die Dringlichkeit ist für diesen einen Anwender sicher relativ hoch, insgesamt gesehen würde ich sie aber als mäßig einstufen. Soweit ich es den Logfiles der letzten Wochen entnehme (grep nach 'review/index/clear' | grep POST), wird die Funktion nur in zwei Instanzen genutzt, und dabei ganz überwiegend von der Instanz, wo jetzt das fehlerhafte bzw. zumindest unerwartete Verhalten aufgefallen ist.
