### ISSUE TITLE
Anzeige und Verlinkung von IDs bei Personen auf der Frontdoor

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1183]
Bislang werden ORCID iDs und GND-IDs nur bei PersonAuthor und PersonReferee auf der Frontdoor dargestellt, jedoch nicht bei den anderen Personenrollen wie PersonEditor etc (vgl. https://github.com/OPUS4/application/blob/master/modules/frontdoor/views/scripts/index/templates/metadata.xslt, Z. 237 ff.). Gibt es dafür einen triftigen Grund? Falls nicht, würde ich die Anzeige und Darstellung bei allen Personen einbringen. Ich hatte gerade eine Kundenanfrage dazu und habe das in der Instanz umgesetzt.

**Comment by j3nsch** [comment]
Der aktuelle Zustand ist auch durch einen PR reingekommen und anscheinend waren damals nur die beiden Rollen interessant. Meinetwegen kann das ausgeweitet werden. 

@stconradr Gegenstimmen?
