### ISSUE TITLE
Sammlungen der Role "institutes" in Frontdoor sortiert anzeigen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1187]
Die Sammlungen der Rolle **institutes** bilden Abteilungen, Fakultäten usw. ab. Bisher werden die Sammlungen anhand ihrer ID bzw. der zeitlichen Reihenfolge der Verknüpfung angezeigt. Die Sammlungen, die Abteilungen, sollten sortiert angezeigt werden. um die Reihenfolge nachvollziehbar zu machen.

**Comment by j3nsch** [comment]
FYI @vgerlach, @alw-bsz Die Sortierung erschien mir generell sinnvoll für Standard-OPUS 4. Es gibt keine Möglichkeit die Reihenfolge gezielt zu bestimmen. Das halte ich hier auch für unnötig. Die alphabetische Sortierung ist nachvollziehbarer als die Sortierung nach internen Datenbank-IDs.

**Comment by alw-bsz** [comment]
Falls es sich bislang so verhält, dass die institutes in der Reihenfolge der Eingabe auf der Frontdoor dargestellt werden, kann ich mir vorstellen, dass das durchaus von einigen Einrichtungen weiterhin so gewünscht wird. Falls die Reihenfolge zufällig zustande kommt, spricht aus meiner Sicht nichts gegen eine alphabetische Sortierung.

**Comment by j3nsch** [comment]
Es kann sein, dass die Reihenfolge "zufällig" der Reihenfolge entspricht, in der die Verknüpfungen angelegt wurden. Da muss aber Code an mehreren Stellen zusammen spielen, beim Speichern, beim XML-Generieren usw. Wenn die Hierarchy von **institutes** editiert wird, verändert sich die Anzeige und man müsste Verknüpfungen entfernen und wieder hinzufügen, um die Reihenfolge zu korrigieren, für alle verknüpften Dokumente. 

Ich werde dafür sorgen, dass die Reihenfolge im Standard klar nachvollziehbar und definiert ist. Bei abweichenden Vorstellungen kann die eine zusätzliche Zeile im XSLT entfernt oder editiert werden. Im Augenblick werde ich das nicht konfigurierbar machen. Es ist sinnvoll erst einmal abzuwarten, ob sich jemand mit anderen Anforderungen meldet.
