### ISSUE TITLE
Anzeige der Zugehörigkeit zur Bibliographie in der Administration

### ISSUE THREAD

**Issue by stconradr** [OPUS4/application#1190]
In der Administration wird die Zugehörigkeit zur Bibliographie nicht in der Dokumentenübersicht
angezeigt, obgleich diese vergeben wurde.
 ./admin/documents

**Comment by j3nsch** [comment]
Wurde das mal auf dem PHP 8 System getestet?

**Comment by j3nsch** [comment]
Ich kann das Problem lokal, auf meinem PHP 8 System, nicht nachvollziehen. Auf dem Hosting Test System werden vom Framework String-Values ("0" oder "1") für **BelongsToBibliography** geliefert. Dadurch schlägt der strikte Vergleich mit Int 1 fehl. Ich vermute, dass das Problem auf alten System aus einer Mischung von PHP 7 und der MySQL-Version verursacht wird. Ich habe den Code jetzt so angepasst, dass der Check auch mit Strings erfolgreich ist. In Zukunft sollte die neue Implementation der Datenbank-Anbindung dafür sorgen, dass boolesche Felder wie **BelongsToBibliography** entsprechende Werte, also **true** oder **false** zurück liefern, unabhängig von der Speicherung in der Datenbank.

**Comment by stconradr** [comment]
Jens, deine Vermutung ist richtig. Ich habe es jetzt unter PHP8 getestet, da funktioniert die Anzeige mit der 4.8.0.4 und der 4.8.1.
