### ISSUE TITLE
Keine Dublettenprüfung bei der Bandnummervergabe zur Schriftenreihe

### ISSUE THREAD

**Issue by stconradr** [OPUS4/application#1191]
Es erfolgt in der aktuellen Version 4.8.0.4 keine Dublettenprüfung bei der Bandnummervergabe zur Schriftenreihe. Somit können Bandnummern in der Schriftenreihe mehrfach vergeben werden und sind nicht mehr eindeutig.

**Comment by j3nsch** [comment]
Es geht um welches Formular?

**Comment by j3nsch** [comment]
@alw-bsz, @stconradr Das war eine Anforderung, die in folgendem Ticket umgesetzt wurde.

https://tickets.zib.de/jira/browse/OPUSVIER-3917

Klärt das bitte und sagt Bescheid.

**Comment by stconradr** [comment]
Ok, Danke.

**Comment by stconradr** [comment]
Haben das nochmal diskutiert und da es aus bibliothekarischer Sicht wohl kein Problem darstellt, soll die jetzige Lösung so bleiben. Es sind eher Ausnahmefälle, wo das zur Anwendung kommt, aber es kann vorkommen, wenn unterschiedliche Aufsätze in einem Band veröffentlicht werden. 
Die Doku muss angepasst werden, ich mach ein Issue.
Dann dieser Issue wieder geschlossen werden.
