### ISSUE TITLE
PublicationState auf COAR-Vokabular umstellen

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1192]
Im DINI-Zertifikat 2025 wird voraussichtlich vom bislang referenzierten _Version Vocabulary_ der DRIVER Guidelines (https://wiki.surfnet.nl/display/DRIVERguidelines/Version%20vocabulary) auf die _Version Types_ des  COAR-Vokabulars (https://vocabularies.coar-repositories.org/version_types/1.1/) umgestellt werden. OpenAIRE v4 verlangt für diese Angabe ebenfalls die Verwendung des COAR-Vokabulars (vgl. https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/latest/field_resourceversion.html).

| URI | Label | Bedeutung | Ungefähre Entsprechung bei DRIVER |
| -- | -- | -- | -- |
| http://purl.org/coar/version/c_b1a7d7d4d402bcce | AO | Author’s Original (Autorenversion) | |
| http://purl.org/coar/version/c_71e4c1898caa6e32 | SMUR | Submitted Manuscript Under Review (Eingereichte Version) | submittedVersion |
| http://purl.org/coar/version/c_ab4af688f83e57aa | AM | Accepted Manuscript (Akzeptiertes Manuskript) | acceptedVersion |
| http://purl.org/coar/version/c_fa2ee174bc00049f | P | Proof (Korrekturfahne) | |
| http://purl.org/coar/version/c_970fb48d4fbd8a85 | VoR | Version of Record (Erstveröffentlichung / Originale Verlagspublikation) | publishedVersion  |
| http://purl.org/coar/version/c_e19f295774971610 | CVoR | Corrected Version of Record (Korrigierte Version) | updatedVersion  |
| http://purl.org/coar/version/c_dc82b40f9837b551 | EVoR | Enhanced Version of Record (Erweiterte Version) | updatedVersion  |
| http://purl.org/coar/version/c_be7fb7dd8ff6fe43 | NA | Not Applicable (or Unknown) (Keine Angabe) |  |
| - | - | - | draft |

**Comment by j3nsch** [comment]
Kein Mapping für **draft**? 

Bin mir noch nicht sicher was hier wirklich die sinnvollste Umsetzung ist. DINI empfiehlt momentan DRIVER, OpenAIRE v4 verlangt COAR. Es ist einfacher von 8 Optionen auf 5 zu mappen, COAR zu DRIVER. Wir lassen hier aber externe Anforderungen, die sich offensichtlich ändern können, das interne Datenmodell bestimmen. Die COAR Label sind für die Datenbank gut, aber im User Interface sind sie schwerer nachvollziehbar. Die Bedeutungen müssten übersetzbar werden und mit angezeigt werden, evtl. als Tooltip.

Was macht für OPUS 4 und seine Nutzer*innen Sinn? Ich kann mir vorstellen, dass Institutionen lokal die Liste der Optionen vereinfachen wollen. Input aus dem Hosting und von Instanzen wäre gut (@stconradr).

Wenn wir das im Augenblick nicht klären können, wäre ich dafür mit der aktuellen DINI Empfehlung zu gehen, und dann COAR bei der Umsetzung von OpenAIRE v4 wieder aufzugreifen. Je früher die offenen Fragen beantwortet sind, desto eher kann man sich aber vielleicht Arbeit sparen, z.B. bei Updates mit geänderten Optionslisten. Gerade das Mapping von **updatedVersion** auf zwei mögliche Optionen in COAR könnte beim Update ein Problem sein.

**Comment by alw-bsz** [comment]
Für _draft_ gibt es keine Entsprechung bei COAR.

Ich denke, wir sollten das interne Datenmodell nicht durch die externen Vokabulare bestimmen lassen. Künftige Änderungen daran oder die Ablösung durch ein anderes Vokabular in der Zukunft lassen sich nicht ausschließen.

Wir sollten die COAR-Abkürzungen nicht in der Datenbank oder dem UI verwenden (bzw. allenfalls ergänzend zu den ausgeschriebenen Begrifflichkeiten). Sie sind nicht sprechend und ich weiß nicht, ob ein durchschnittlicher OPUS-User etwas mit den Abkürzungen anfangen kann. Mir persönlich sagen die Abkürzungen nichts und ich könnte damit nicht arbeiten.

Ausgehend von den wenigen Instanzen, die bei uns bislang mit dem Publikationsstatus arbeiten und der bevorstehenden Ablösung der DRIVER-Begrifflichkeiten durch das COAR-Vokabular schlage ich folgende Lösung vor. Sie 
- berücksichtigt das DRIVER- und das COAR-Vokabular
- ist sowohl für den Endnutzer als auch für uns sprechend (auch in der Datenbank)
- sorgt gleichzeitig für eine Unabhängigkeit der OPUS-Umsetzung von den Vokabularien.

| Status | Übersetzung deutsch | Übersetzung englisch | DB-Wert | OAI-Set gem. DINI-Zertifikat 2022 | OpenAIRE v4 |
| -- | -- | -- | -- | -- | -- |
| Entwurf | Entwurf | draft | draft | draft | `<oaire:version uri="http://purl.org/coar/version/c_be7fb7dd8ff6fe43">NA</oaire:version>` |
| Finale Fassung des Autors | Autorenversion | Author’s Original | authorsVersion | _n/a_ | `<oaire:version uri="http://purl.org/coar/version/c_b1a7d7d4d402bcce">AO</oaire:version>` |
| Eingereichte Fassung | Eingereichte Version | Submitted Manuscript Under Review | submittedVersion | submittedVersion  | `<oaire:version uri="http://purl.org/coar/version/c_71e4c1898caa6e32">SMUR</oaire:version>` |
| Akzeptierte Fassung | Akzeptiertes Manuskript | Accepted Manuscript | acceptedVersion | acceptedVersion | `<oaire:version uri="http://purl.org/coar/version/c_be7fb7dd8ff6fe43">AM</oaire:version>` |
| Korrekturabzug | Korrekturfahne | Proof | proof | _n/a_ | `<oaire:version uri="http://purl.org/coar/version/c_fa2ee174bc00049f">P</oaire:version>` |
| Veröffentliche Verlagsfassung | Originale Verlagspublikation | Version of Record | publishedVersion | publishedVersion  | `<oaire:version uri="http://purl.org/coar/version/c_970fb48d4fbd8a85">VoR</oaire:version>` |
| Korrigierte Verlagsfassung | Korrigierte Verlagsfassung | Corrected Version of Record | correctedVersion | updatedVersion | `<oaire:version uri="http://purl.org/coar/version/c_e19f295774971610">CVoR</oaire:version>` |
| Erweiterte Verlagsfassung | Erweiterte Verlagsfassung | Enhanced Version of Record | enhancedVersion | updatedVersion | `<oaire:version uri="http://purl.org/coar/version/c_dc82b40f9837b551">EVoR</oaire:version>` |

Ich denke, es macht Sinn, wenn die Liste instanzspezifisch angepasst/vereinfacht werden kann. Ich kann mir gut vorstellen, dass z.B. die Korrekturfahne in aller Regel nicht benötigt wird.

Der Publikationsstatus soll außerdem als Facette in der Trefferliste verwendet werden können.

**Comment by j3nsch** [comment]
Ich denke wir sollten erst einem bei einem ENUM in der Datenbank bleiben. Beliebige Datenbankwerte reduzieren Performanz und scheinen mir nicht notwendig. Da hängt ja auch noch mehr beim Mapping im Export usw. dran. Im Augenblick sehe ich keine guten Gründe für die zusätzliche Komplexität. Die Optionen im User Interface limitieren zu können, scheint mit sinnvoll.

Die Werte **proof**, **authorsVersion** können einfach hinzugefügt werden. 

Der alte Wert **updatedVersion** soll in Anlehnung an COAR durch **correctedVersion** und **enhancedVersion** ersetzt werden. Existierende Einträge (wenn auch unwahrscheinlich) müssten gemappt werden. Dabei wäre unklar, welcher der neuen Werte besser passt. Alternativ könnte **correctedVersion** hinzugefügt werden und **updatedVersion** anstelle von *enhancedVersion* verwendet werden. Damit wären alle alten Werte noch vertreten.

Ein Argument dafür den Wert **updatedVersion** in der Datenbank durch **enhancedVersion** zu ersetzen, wäre die Wiedererkennung des COAR-Vokabulars, aber das ist unsichtbar für Nutzer und für OpenAIRE ist sowieso Aufwand für das Mapping notwendig, um mit NULL und mit **draft** umzugegen.

In OpenAIRE müssen NULL und **draft** als **NA** mit der entsprechenden URL ausgegeben werden.

**Comment by j3nsch** [comment]
Okay, für Einheitlichkeit habe ich jetzt in der Datenbank doch `updatedVersion` durch `enhancedVersion` ersetzt.

**Comment by j3nsch** [comment]
Ich übernehme die Reihenfolge der Optionen von hier.

**Comment by j3nsch** [comment]
Die vorgeschlagenen Werte werden verwendet. Es können Werte im User Interface ausgeschlossen werden.

    model.document.fields.PublicationState.excludeValues
    
Sollte ein ausgeschlossener Wert von einem Dokument bereits verwendet werden, wird dieser Wert im Metadatenformular angezeigt und kann, muss aber nicht geändert werden.
