### ISSUE TITLE
Feld PublicationState in OAI-Formaten verwenden

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1202]
Das Feld **PublicationState** soll unter Umständen in den verschiedenen OAI-Formaten mit ausgegeben werden. 

Es geht im ersten Schritt also darum zu identifizieren in welchen Formaten das Feld verwendet werden kann. Sollte der Aufwand für einzelne Formate größer sein, sind separate Issues sinnvoll. Sollte es keinen Bedarf geben, sollte das hier festgehalten und das Ticket geschlossen werden.

Siehe auch #814

**Comment by alw-bsz** [comment]
| Format | Ausgabe | Beispiel | 
| --- | --- | -- |
| DataCite-XML 4.5 | _nicht vorgesehen_ |  |
| MARC21 | _unklar, am ehesten evtl. 245 $s (Version zur Titelangabe)_? |  |
| OAI-DC | Element `<dc:type>`<sup>[1](#gemvok1)</sup> | `<dc:type>acceptedVersion</dc:type>` |
| XMetaDissPlus 2.5 | Element `<dini:version_driver>`  | `<dini:version_driver>acceptedVersion</dini:version_driver>` |

<a class="anchor" id="gemvok1">1</a> Vgl. Gemeinsames Vokabular für Publikations- und Dokumenttypen (DINI), Version 1.0, 2010, S. 16 f.

**Comment by j3nsch** [comment]
Erledigt?

**Comment by alw-bsz** [comment]
Ja, das ist erledigt.

Der PublicationStatus wird nun in den Formaten OAI-DC und XMDP über die OAI-PMH-API ausgegeben.

In MARC21 wurde er nicht implementiert, ebenso nicht in im DataCite-XML sowie den BibTeX- und RIS-Exporten. Hier ist entweder unklar, wohin die Angabe zu mappen ist oder es gibt kein entsprechendes Feld in den Zielformaten. Bei künftigem Bedarf müsste man das nochmal prüfen.
