### ISSUE TITLE
Translations beim DOI-basierten Metadatenimport

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1206]
Die Textelemente des DOI-basierten Metadatenimports sind bislang nur einsprachig umgesetzt (deutsch, hart codiert). Sie sollen analog zu anderen Komponenten in OPUS auch auf englisch verfügbar und anpassbar sein. Die hart codierten Textelemente werden daher durch Variablen ersetzt und die Standardtextelemente in einem TMX-File hinterlegt. Die Texte können dann über die Übersetzungen in den Oberflächenanpassungen wie üblich verändert werden.

**Comment by j3nsch** [comment]
Gehe davon aus, dass das erledigt ist.
