### ISSUE TITLE
Reduzierung von unerlaubter manueller Datenerfassung beim DOI-basierten Metadatenimport

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1207]
Uns haben mehrere Rückmeldungen aus verschiedenen Bibliotheken erreicht, dass es wiederholt vorkommt, dass Anwender die Metadaten im DOI-Import-Formular händisch erfassen, wenn die gesuchte DOI bei Crossref nicht gefunden werden kann. Dass die DOI eine Pflichtangabe ist, wird entweder erst beim Abschicken des Publish-Formulars und der folgenden Fehlermeldung festgestellt, oder durch das Eintragen einer Fake-DOI umgangen. Um solche Fehler künftig auszuschließen, soll der Anwender zurück auf die Startseite des Publish-Vorgangs geleitet werden, wenn die gesuchte DOI nicht bei Crossref gefunden werden kann.

**Comment by alw-bsz** [comment]
Ich hatte zuerst auch Bedenken, den Vorgang abzubrechen und den Anwender wieder auf die Startseite des Publish-Vorgangs zurückzuschicken, aber die BibliothekarInnen, mit denen wir gesprochen haben, meinten, dass ein Typo eher ein theoretischer Fall wäre, weil die DOIs in alle Regel per Copy & Paste übernommen und nicht händisch eingetippt werden.

**Comment by j3nsch** [comment]
Wenn wir jetzt in #1228 die Eingabe ohne erfolgreichen Import unterbinden, kann die Umleitung eigentlich wieder wegfallen.

**Comment by alw-bsz** [comment]
Den Gedanken hatte ich auch schon ... dann nehmen wir die Umleitung wieder raus.

**Comment by alw-bsz** [comment]
Boris und ich haben uns das nochmal angeschaut und halten das völlige Entfernen des Redirects doch für keine gute Lösung. Es erlaubt zwar die Korrektur bei einem Typo, führt wahrscheinlich aber zu unnötigen Datensätzen im temporary-Status. Der Nutzer, der keine weitere DOI eingeben will, weiß dann ggf. nicht so recht, was er tun soll. Und dann liegt der Zurück-Pfeil im Browser deutlich näher als der Abbrechen-Button ganz unten am Ende des langen Formulars.

Wir würden daher den Workflow an dieser Stelle erweitern, so dass der Anwender auswählen kann, ob er zurück zur Startseite des Publish-Vorgangs geleitet wird oder eine weitere DOI eingeben will.

**Comment by j3nsch** [comment]
Da die aktuelle Implementation eine befristete Lösung ist, könnt Ihr das so machen.

**Comment by alw-bsz** [comment]
Die Härtung gegen fehlerhafte Nutzereingaben wird dahingehend erweitert, dass der Anwender stets ein Menü mit den zur Verfügung stehenden Optionen angezeigt bekommt, wenn der Metadatenimport nicht erfolgreich war, d.h. auch wenn es bereits einen (veröffentlichten oder unveröffentlichten) Datensatz mit der DOI in OPUS gibt.

**Comment by alw-bsz** [comment]
Wurde implementiert
