### ISSUE TITLE
Layout-Fehler: Heller Bereich im Publish-Formular

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1209]
Bei manchen Dokumenttypen kommt es im Publish-Formular zu einem hellen Bereich nach dem OPUS 4-Logo:
<img src="https://github.com/OPUS4/application/assets/49676210/2c802391-e3ec-4884-9ea6-ae6c3be3958d" width="450px">

Korrekt wäre:
<img src="https://github.com/OPUS4/application/assets/49676210/5b89eedc-ee96-43bc-a089-4d7581999814" width="450px">

Ursächlich dafür ist die Codierung der PHTML-Templates im Zeichensatz UTF-8 mit Byte Order Mark (UTF-8-BOM). Der Fehler lässt sich durch Änderung der Codierung in den Zeichensatz UTF-8 ohne Byte Order Mark beheben.

**Comment by j3nsch** [comment]
FYI @stconradr, @vgerlach

**Comment by j3nsch** [comment]
Das sollte erledigt sein.
