### ISSUE TITLE
 Feld PublicationState in OAI-DC

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1213]
Die Ausgabe erfolgt im Element `<dc:type>`, z.B.
`<dc:type>updatedVersion</dc:type>`

Der angegebene Wert unterscheidet sich zwischen "normalem" OAI-DC und OAI-DC für OpenAIRE. Bei OpenAIRE ist zusätzlich das verwendete Vokabular durch Voranstellen des Strings _info:eu-repo/semantics/_ zu kennzeichnen, z.B.:
`<dc:type>info:eu-repo/semantics/updatedVersion</dc:type>`

Bislang wurde für OpenAIRE statisch `<dc:type>info:eu-repo/semantics/publishedVersion</dc:type>` ausgegeben. Das Verhalten wird dahingehend geändert, dass der PublicationState nur noch dann statisch ergänzt wird, wenn im Datensatz kein PublicationState angegeben ist; ansonsten wird der tatsächliche Wert verwendet.

Damit es nicht zu unerwünschten Nebeneffekten kommt, sollten die im Zuge der Migration von OPUS 3 nach OPUS 4 sowie die von OPUS 4 im Default gesetzten Datenbank-Werte "published" bzw. "draft" bereinigt werden.

**Comment by j3nsch** [comment]
Erledigt?

**Comment by alw-bsz** [comment]
Ja, das ist erledigt.
