### ISSUE TITLE
Fehler beim Ausführen von bin/opus4 - mysql driver not installed

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#1229]
bin/opus4 lässt sich in 4.8.1 nicht ausführen. Es bricht unabhängig vom Befehl (index, help ...) mit dieser Fehlermeldung ab:

_PHP Fatal error:  Uncaught Zend_Db_Adapter_Exception: The mysql driver is not currently installed in /opt/work/opus/v481/vendor/opus4/zf1-future/library/Zend/Db/Adapter/Pdo/Abstract.php:112_

**Comment by j3nsch** [comment]
Ohne weitere Informationen ist es schwierig mehr zu sagen, als "es funktioniert auf anderen Systemen". 

Vor kurzem war auf einem meiner System nach Updates, PHP 8.3 aktiviert. Damit sind wir noch nicht kompatibel. Wenn auf dem System mehrere PHP Versionen installiert sind, dann sind die notwendigen PHP-Pakete manchmal nicht für alle Versionen installiert. Ein Composer `update` oder `install` oder auch  `info` können helfen.

FYI @stconradr, @vgerlach

**Comment by alw-bsz** [comment]
Danke, @j3nsch; nach `composer update` tut es jetzt.
