### ISSUE TITLE
Bug im Zusammenhang mit der Frontdoor-Navigation innerhalb von Suchergebnissen

### ISSUE THREAD

**Issue by saschaszott** [OPUS4/application#15]
Anleitung zum Reproduzieren (mit den ausgelieferten Testdokumenten):
- einfache Suche nach `test`ausführen
- Aufruf des ersten Suchtreffers (DocId 145): http://localhost:11111/opus4/frontdoor/index/index/start/0/rows/10/sortfield/score/sortorder/desc/searchtype/simple/query/test/docId/145
- Anpassung der DocId in der URL: Ersetze 145 durch 123:
  http://localhost:11111/opus4/frontdoor/index/index/start/0/rows/10/sortfield/score/sortorder/desc/searchtype/simple/query/test/docId/123

Nun erfolgt ein Redirect auf die URL:
http://localhost:11111/opus4/frontdoor/index/index/start/0/rows/10/sortfield/score/sortorder/desc/searchtype/simple/query/test/docId/145

und zusätzlich die Notice

```
Notice: Undefined index: message in /var/local/opus4/public/layouts/opus4/common.phtml on line 204
```

Es wurden zwischen dem Aufruf der beiden URLs keine Änderungen am Dokumentenbestand durchgeführt. Warum erscheint dann die Meldung (auch noch in grüner Farbe?):

> Das Suchergebnis hat sich seit Ihrer Suchanfrage verändert. Eventuell werden Dokumente in anderer Reihenfolge angezeigt.

Ich habe mir in `common.phtml`den Hash `$message`ausgeben lassen:

```
array(1) { ["notice"]=> string(121) "Das Suchergebnis hat sich seit Ihrer Suchanfrage
verändert. Eventuell werden Dokumente in anderer Reihenfolge angezeigt." } 
```

Dort gibt es keinen Schlüssel `message`, so dass der Zugriff auf `$message['message']`in Zeile 204 ein Problem verursacht:

```
<div class="<?= $message['level'] ?>"><?= htmlspecialchars($this->translate($message['message'])) ?></div>
```

**Comment by j3nsch** [comment]
Das wurde anscheinend vor langer Zeit gefixt. Für das Rendern der Ausgabe wird jetzt der View-Helper `Messages` verwendet.
