### ISSUE TITLE
php 7.2 Kompatibilität

### ISSUE THREAD

**Issue by hermann77** [OPUS4/application#153]
Ist es beabsichtigt, die Inkompatibilität von Zend Framework 1 mit php7.2 (habe das gleiche Problem: https://stackoverflow.com/questions/49072332/is-zend-framework-1-compatible-with-php-7-2) zu beheben, indem OPUS4 auf ZF2 migriert wird?

**Comment by j3nsch** [comment]
Die Absicht ist auf ZF3 zu migrieren. Obwohl Zend in vielen Dingen gleich geblieben ist, der Code für die Formulare muss vermutlich fast überhaupt nicht angepasst werden, gibt es einige größere Aufgaben, die im Rahmen des Umstiegs erledigt werden müssen. 

Unter anderem wird der Übersetzungsmechanismus, den wir momentan verwenden, in ZF3 (und ZF2) nicht mehr unterstützt. Da OPUS 4 und seine Nutzer hinsichtlich der Übersetzungen besondere Ansprüche haben können wir nicht auf die neuen Methoden wechseln. Wir haben ja nicht nur Deutsch und Englisch, sondern Deutsch in 100+ Varianten, da fast jede Instanz an den Übersetzungen schraubt. Das ist bei "normaler" Software nicht der Fall. 

Weierhin funktioniert die Konfiguration und Komposition von Applikationen in ZF3/2 anders als in ZF1. Auch damit müssen wir uns befassen und schauen wie OPUS 4 sinnvoll migrieren kann.

In anderen Worten, ZF3, wird nicht von heute auf morgen passieren und ich denke im Augenblick nicht, dass wir in den nächsten Monaten dazu kommen werden. Ich würde den Umstieg allerdings gerne in 2019 erledigt haben.

Bei Zend gibt es momentan Unklarheiten über die Zukunft des Frameworks. Trotz aller Probleme ist der Umstieg auf ZF3, aber immer noch wesentlich leichter als ein Umstieg auf ein völlig anderes Framework.  Daher werden wir in den nächsten Jahren bei Zend bleiben.

**Comment by hermann77** [comment]
Danke Dir für die Antwort!

**Comment by hermann77** [comment]
Hi,
danke Dir für die Info! Das klingt ja gut.
Dann warten wir auf den ersten Release Candidate auf ZF3-Basis. Wir haben schon gesehen, dass es im "framework"-Repositorium einen Branch "zf3" gibt. Für den ersten RC müssen wahrscheinlich auch die OPUS4-Module im "application"-Repositorium angepasst werden.
Wir (Deutsches Bildungsserver Team am DIPF Berlin) freuen uns jedenfalls auf die Weiterentwicklung dieser tollen Software. Vielleicht können wir sogar zur Weiterentwicklung etwas beitragen, sobald wir in der Lage sind :-).

**Comment by j3nsch** [comment]
Ich habe jetzt mal ein Issue #183 für den Umstieg auf ZF3 angelegt, um dort weitere Informationen festhalten zu können. Die eigentliche, detailierte Planung findet intern mit Jira statt. Besonders interessierte Nutzer/Entwickler können Zugriff auf unser Jira erhalten. Die Issues hier bieten nur einen sehr begrenzten Einblick, da sie nicht wirklich für die Entwicklung, sondern eher für die Kommunikation, genutzt werden. Für umfangreiche Kommunikation und Dokumentation sind die Entwicklungsresourcen leider häufig zu knapp.

Der Framework-ZF3-Branch ist erst einmal nur für Experimente. Für den ersten RC werden wir die "application" völlig auseinander nehmen oder wieder zusammenbauen müssen (sorgfältig). Das ist viel Arbeit, aber ich denke es wird sich wirklich lohnen.

**Comment by hermann77** [comment]
Hi,
wenn ich einen Jira-Zugang bekommen könnte, wäre toll. Wenn ich so mehr technische Informationen bekommen würde, würde ich mich freuen.
Übrigens, wenn wir technische Fragen haben, was ist der beste Weg, diese Fragen an Dich/Euch zu stellen? Hier über Issues oder doch in Jira?

Vielen Dank für die Unterstützung!

**Comment by j3nsch** [comment]
Hallo, eine direkte E-Mail an mich am ZIB wäre gut, um den Zugang zu JIRA in die Wege zu leiten.

Ansonsten Anfragen am Besten über die Mailing-Liste, weil dadurch zumindest die Chance besteht, dass jemand anderes die Frage beantwortet. 

http://listserv.zib.de/mailman/listinfo/kobv-opus-tester

Konkrete Probleme und Anforderungen gerne als Issues hier oder dann über JIRA, wenn der Zugang besteht. In Jira haben wir momentan 500+ offene Tickets. Nicht allen kann ständig Aufmerksamkeit geschenkt werden, aber bei vielen Tickets ist es hilfreich, wenn Informationen gesammelt werden, während sich die Entwicklung mit anderen Aspekten befasst.

**Comment by j3nsch** [comment]
Auf dem Branch [4.7.2-zf1f](https://github.com/OPUS4/application/tree/4.7.2-zf1f) laufen die OPUS 4 Tests jetzt mit PHP 7.1, 7.2 und 7.4 durch. Demnächst werden die Änderungen in den Branch [4.7.2](https://github.com/OPUS4/application/tree/4.7.2) für den kommenden Release übernommen. Für die Kompatibilität mit PHP 8 sind weitere Arbeiten notwendig, insbesondere um das alte Zend Testframework zum laufen zu bringen.

Das die Tests laufen ist eine Grundvoraussetzung für die Entwicklung, aber auch mit etwas 6700 Tests über alle Pakete hinweg, gibt es immer noch Lücken. Es ist also wichtig, dass die neue Version noch vor dem offiziellen Release von möglichst vielen Instanzen geprüft wird, damit Problem frühzeitig behoben werden können.
