### ISSUE TITLE
composer.lock commiten

### ISSUE THREAD

**Issue by hofrob** [OPUS4/application#19]
In der Datei `composer.lock` sind Detailinfos zu den Versionen der nachgeladenen libraries enthalten. Ist nach dem Befehl `$ composer update` eine neue Version einer library gefunden und installiert worden, wird dies in der Datei `composer.lock` festgehalten.

`$ composer update` sollte nur von den Herausgebern der Software durchgeführt werden. Sind die Tests erfolgreich und können die upgedateten libraries verwendet werden, wird `composer.lock` commited. Für eine produktive Installation wird dann `$ composer install --no-dev --optimize-autoloader` durchgeführt. `install` lädt exakt die Versionen der libraries die in `composer.lock` festgehalten wurden.

Also ich würde vorschlagen die Datei `composer.lock` aus `.gitignore` zu entfernen und zu commiten, damit es nicht passieren kann, dass bei jeder Installation von Opus andere Versionen der libraries nachgeladen werden.

liebe Grüße aus Wien!

**Comment by j3nsch** [comment]
Vielen Dank, das klingt plausibel. Ich werde vor dem 4.5 Release darauf zurück kommen. 

Wir sammeln noch Erfahrungen mit Composer und der direkten Verwendung von Git um produktive Instanzen zu installieren. Im Hosting läuft das bisher gut und macht Updates wesentlich einfacher.

**Comment by j3nsch** [comment]
`composer.lock` ist jetzt im Branch 4.5 und wird dann mit dem Release in den Master übernommen. Wenn es Probleme gibt, kann die Datei ja problemlos lokal überschrieben werden. Offen ist die Frage, wie mit optionalen Paketen umgegangen werden kann, die lokal installiert werden und dazu führen, daß die Datei von der Referenz abweicht, z.B. wenn lokal MathJax hinzugefügt wird. Einerseits mag ich den Gedanken optionale Pakete mit Composer einfach lokal hinzuzufügen, aber ich verstehe auch das composer.lock in Git dafür sorgt, daß alle Instanzen mit den selben, getesteten Version funktionieren. Mal schauen wie sich das im Laufe der Zeit entwickelt.

**Comment by j3nsch** [comment]
Unter Ubuntu 14.04 gibt es Probleme mit manchen von den "dev"-Paketen, weil sie eine neuere PHP Version benötigen. Entwicklung findet unter Ubuntu 16 statt. Evtl. müssen konkrete Versionen so gewählt werden, daß sie für Ubuntu 14 funktionieren.

**Comment by j3nsch** [comment]
Das Commiten von `composer.lock` funktioniert nur, wenn die Entwicklungssysteme und die Produktivsystem das gleiche Betriebssystem verwenden. Innerhalb des KOBV wäre das machbar. OPUS 4 wird aber auch auf anderen Systemen installiert und dort gab es immer wieder Schwierigkeiten mit einer fest vorgegebenen `composer.lock` Datei. Dadurch, dass jede Instanz ihre eigenen Pakete auflöst, kann es natürlich zu Problemen kommen, die nicht ohne weiteres nachvollziehbar sind. In den letzten Jahres ist das aber nicht passiert.
