### ISSUE TITLE
Steuerzeichen im Abstract führen beim finalen Deposit zu Application_Exception

### ISSUE THREAD

**Issue by publica-bam** [OPUS4/application#213]
Wir haben in der BAM-Instanz festgestellt, dass das Publikationsformular nicht robust mit eingeschleppten Steuerzeichen in Eingabefeldern, z.B. im Abstract-Feld, umgehen kann. 

Solche Steuerzeichen werden durch Copy&Paste von Abstracts aus PDF-Dokumenten eingeschleppt. Leider sieht der Benutzer beim Pasting auch nicht, dass er/sie gerade Steuerzeichen eingeschleppt hat, weil die Steuerzeichen nicht druckbar sind.

Hier zum Testen ein solch problematischer Beispielinhalt für das Feld Abstract, der zwei Steuerzeichen `0B` (SOH) und `01` (VT) enthält:
```
kWm􀀀2 eect
```

Der zweite Schritt des Publikationsformulars kann mit Steuerzeichen im Abstract offenbar noch robust umgehen, den man gelangt ohne Fehlermeldung zum dritten Schritt des Publikationsformulars. Folglich muss das Speichern eines OPUS-Dokuments (mit Zustand `temporary`) mit Steuerzeichen im Abstract in der DB klappen. 

Beim finalen Deposit durch Drücken des entsprechenden Buttons auf der dritten Seite des Publikationsformulars, auf dem alle Metadaten des Dokuments (inkl. der "merkwürdigen" Zeichen im Abstract) sauber angezeigt werden, kommt es dann allerdings zu einer `Application_Exception` (absolute Verzeichnisnamen wurden hier aus Sicherheitsgründen entfernt):

```
Application_Exception: publish_error_unexpected in modules/publish/controllers/DepositController.php:120
Stack trace:
#0 vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Publish_DepositController->depositAction()
#1 vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('depositAction')
#2 vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#4 vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#5 public/index.php(85): Zend_Application->run()
#6 {main}
```

Folglich muss das Speichern des Dokuments in diesem Kontext (ServerState des Dokuments wird auf `unpublished` gesetzt) einer anderen Logik folgen als das Speichern beim Übergang von Schritt 2 in 3 (ServerState ist `temporary`).

**Comment by publica-bam** [comment]
Leider kann ich im Ticket keine Steuerzeichen eingeben (im angegebenen Beispielinhalt steht jetzt ein �). Wir können den Inhalt gern per Mail bereitstellen. Alternativ mit einem Hexeditor den problematischen Beispielinhalt selbst erzeugen und dann ins Eingabeformular kopieren:

```
6b 57 01 6d f4 80 80 80 32 20 65 0b 65 63 74
```

**Comment by publica-bam** [comment]
@stconradr hat uns mitgeteilt, dass das Problem schon bekannt ist. Es gibt mehrere Jira-Tickets dazu. Und es wird mit 4.6.4 behoben sein.

**Comment by sigwei** [comment]
Das Problem wurde in den Jira-Tickets OPUSVIER-2591, OPUSVIER-3607 und OPUSVIER-3639 bearbeitet und ist in OPUS 4.6.4 behoben.

**Comment by publica-bam** [comment]
Alles klar, danke für die Rückmeldung und Behebung! Ich schließe das Ticket daher als *Duplicate*.
