### ISSUE TITLE
Add full Unicode support: switch to charset utf8mb4

### ISSUE THREAD

**Issue by publica-bam** [OPUS4/application#27]
OPUS verwendet aktuell den MySQL-Charset `utf8` beim initialen Anlegen der Datenbank im Script `createdb.sh`:

```
mysql="${mysql_bin} --default-character-set=utf8 --user=`printf %q "${user}"` --host=`printf %q "${host}"` --port=`printf %q "${port}"`"
```

Auf einer bestehenden Datenbank kann das mit folgendem MySQL-Befehl überprüft werden:

```
mysql> show variables like "character_set_database";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| character_set_database | utf8  |
+------------------------+-------+
```

Der Charset `utf8` kann aber nur Unicode-Zeichen speichern, deren UTF8-Codierung zwischen 1 bis 3 Bytes benötigt. Unicode-Zeichen, die eine UTF8-Codierung haben, die aus 4 Zeichen besteht, kann OPUS nicht speichern. Der in der Klasse `Opus_Model_AbstractDb` eingebaute Mechanismus, um zu erkennen, ob ein Feldinhalt abgeschnitten wurde, springt in diesem Fall an, weil der Vergleich

```
if (strlen($backupValues[$key]) > strlen($new_value)) {
```

ein `true`zurückliefert, da der Feldinhalt `$newValue`, ab dem 4-Byte-Zeichen beim Speichern in der Datenbank abgeschnitten wird und damit kürzer ist, als der Feldinhalt `$backupValues[$key]`, der von der Applikation in den DB-Layer übergeben wurde.

Die restliche Applikation (z.B. das Publish-Formular) kann mit 4-Byte-Zeichen umgehen. Erst beim Persistieren des Wertes in die Datenbank kommt es zum Fehler.

Mit MySQL 5.5 wurde das Charset `utf8mb4` eingefügt. Mit diesem können  nun auch Unicode-Zeichen gespeichert werden, deren UTF8-Codierung 4 Bytes benötigt. Daher sollte OPUS darauf umgestellt werden, um eine vollständige Unicode-Unterstützung zu gewährleisten. Bestehende Datenbanken müssen im Rahmen des Update-Vorgangs vom Charset `utf8` auf `utf8mb4` umgestellt werden.

Der Fehler kann z.B. nachvollzogen werden, wenn man im Publish-Formular in das TitleMain-Feld das Zeichen "𝛽" (_MATHEMATICAL ITALIC SMALL BETA_ mit der hexadezimalen UTF8-Codierung: f0 9d 9b bd) eingibt. Auf der Bestätigungsseite wird das Zeichen 𝛽 noch korrekt angezeigt. Beim Versuch des Speicherns kommt es dann aber zu einer Fehlermeldung, die leider dazu führt, dass der gesamte Formularinhalt verloren geht und der Benutzer bei 0 angefangen kann.

Weitere Infos zu `utf8mb4` habe ich hier gefunden: https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by j3nsch** [comment]
Vielen Dank. Da müssen wir mal drüber nachdenken. Wenn MySQL mit `STRICT_TRANS_TABLES` betrieben wird, wie das unter Ubuntu 16 normalerweise der Fall ist und was Sinn macht, dann greift der eingebaute Mechanismus, der auf abgeschnittene Feldinhalte prüft nicht mehr, da die Datenbank selbst eine Exception produziert. Um sämtliche Zeichen speichern zu können macht der Wechsel natürlich trotzdem Sinn.

**Comment by j3nsch** [comment]
Die Umstellung auf den neuen Charset scheint ein sehr umfangreiches Update-Skript zu benötigen, bei dem jede Spalte aller Tabellen behandelt wird.

https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html

Es wäre möglich erst einmal dafür zu sorgen, dass neue Instanzen gleich mit dem neuen Charset arbeiten.

**Comment by publica-bam** [comment]
Vielleicht ist der Aufwand aber gar nicht so groß. Wordpress (ebenfalls in PHP geschrieben) hat in der Version 4.2 ebenfalls von `utf8` auf `utf8mb4` umgestellt. Die haben ebenfalls ein Update-Skript entwickelt, das sich um dieMigration der Datenbankinhalte kümmert. Die entsprechende Funktion, die über die Objekte der Datenbank iteriert, findest Du hier:

https://github.com/WordPress/WordPress/blob/2d07c3196e473bc2fb5f83e036e09aeb53968776/wp-admin/includes/upgrade.php#L2003

Die Funktion muss in einer Schleife für alle Tabellen des DB-Schemas aufgerufen werden.

**Comment by publica-bam** [comment]
Dieses Ticket ist für die Version 4.7 geplant. Gibt es schon Planungen, wann OPUS 4.7 in 2019 veröffentlicht werden soll? Ich gehe davon aus, dass es die nächste Version nach 4.6.3 ist.

**Comment by j3nsch** [comment]
Es gibt keinen genauen Zeitplan. Nach der 4.6.3 muss der Code erst einmal wieder mit dem 4.7 Entwicklungsstand verschmolzen werden. Dann geht es mit der 4.7 weiter. Da diese aber sehr umfangreich ist, kann es sein, das auch noch eine 4.6.4 notwendig ist. Wir werden darüber nachdenken, ob dieses Thema vor der 4.7 behandelt werden kann.

@BioFreak95 Mach mal bitte für diese Ticket ein koorespondierendes in Jira auf. Die Inhalte müssen nicht komplett kopiert werden, sondern nur kurz die Grundidee und ein Link zu dem Issue hier. Es ist schwierig alles im Auge zu behalten, wenn es auf zwei Ticket-Systeme verteilt ist. Danke!

**Comment by publica-bam** [comment]
Danke @j3nsch für das schnelle Feedback.

**Comment by j3nsch** [comment]
Der aktuelle Plan ist es das mit der 4.6.4 noch in 2018 umzusetzen und danach wieder an der Suche für OPUS 4.7 weiterzuarbeiten. Es besteht die Gefahr, dass mein Verständnis der Datenbank unzureichend ist, um alle Details im Blick zu haben. Daher sollte OPUS 4.6.4 gründlich getestet werden, bevor es freigegeben wird.

**Comment by j3nsch** [comment]
Im Rahmen dieser Arbeiten sollen dann gleich alle Tickets, die mit dem Zeichensatz zu tun haben abgearbeitet werden.

**Comment by j3nsch** [comment]
Die Konvertierung von Tabelle funktioniert anscheinend. Bei der gesamten Datenbank gibt es noch das Problem, dass die Tabellen nicht einfach alle abgearbeitet werden können. An manchen Stellen werden VARCHAR-Spalten als Foreign-Key verwendet. Hier muss die richtige Reihenfolge bei der Konvertierung eingehalten werden.

Weiterhin muss noch berücksichtigt werden, dass für indizierte Spalten sich die maximale Länge des Index ändert, da nun 4 Bytes pro Zeichen verwendet werden. Das steht in der Dokumentation usw., aber es ist noch unklar ob und wie sich das auf die OPUS 4 Datenbank auswirkt. Mehr Informationen stehen im Jira-Ticket OPUSVIER-3930.

**Comment by j3nsch** [comment]
Mit OPUS 4.7 verwendet die Datenbank den Zeichensatz **utf8mb4**. Dadurch sollte es jetzt möglich sein sämtliche Zeichen abzuspeichern.
