### ISSUE TITLE
debug.phtml mit Fehler "Undefined offset" beim Zugriff auf nicht vorhandene Elemente von $profiler_query_profiles

### ISSUE THREAD

**Issue by saschaszott** [OPUS4/application#373]
Mir ist aufgefallen, dass im Falle einer DB-Operation, die zu einem Rollback führt, die Einträge in `$profiler_query_profiles` nicht fortlaufend indexiert sind.

Gerade habe ich einen Fehler durch das Absenden des Formulars für das Anlegen eines neuen Accounts ohne Passwort provoziert. In diesem Fall hat `$profiler_query_profiles` folgende Indices: 0...11, 13 (siehe Screenshot)

![image](https://user-images.githubusercontent.com/952735/101358189-c966ab00-389a-11eb-95b5-b3e20f02579c.png)

Beim Versuch auf `$profiler_query_profiles[12]` zuzugreifen, gibt es dann einen Fehler:

```
[Mon Dec 07 14:37:20.474241 2020] [php7:notice] [pid 56] [client 172.19.1.1:40100] PHP Notice:  Undefined offset: 12 in /var/local/opus4/public/layouts/opus4/debug.phtml on line 22, referer: http://localhost/opus4/admin/account/new
…
PHP Fatal error:  Uncaught Error: Call to a member function getQuery() on null in /var/local/opus4/public/layouts/opus4/debug.phtml:22
```

Ich würde gleich einen PR einreichen, der eine andere Schleifenvariante nutzt.

**Comment by j3nsch** [comment]
Klingt gut. Danke.

**Comment by j3nsch** [comment]
I assume this is done.

**Comment by j3nsch** [comment]
Die neue Formatierung der Ausgabe erzeugt leider eine Ausgabe, die nicht XHTML entspricht.

`Element pre is not declared in dt list of possible children`

Ich fix das.

**Comment by j3nsch** [comment]
Hab den Coding Style Check jetzt ans Ende des Builds verschobe. Es ist wichtiger zu wissen, ob alle Tests durchlaufen. In der Vergangenheit hat für mich der Check am Anfang mehr Sinn gemacht, um unnötige Läufe zu vermeiden. In der Regel lassen sich die Coding Style Probleme ja auch automatisch lösen. Die Länge der Builds wird aber abnehmen, weil mehr Code in separate Pakete wandern wird.
