### ISSUE TITLE
Nach erfolgreicher Änderung eines Passworts erscheint Fehlermeldung und keine Bestätigungsmeldung

### ISSUE THREAD

**Issue by saschaszott** [OPUS4/application#377]
Besitzt ein Benutzer das Recht sein/ihr Passwort selbst zu ändern (Zugriffsrecht für das Modul `account`), so erfolgt nach dem erfolgreichen Ändern des Passworts (auf der Seite http://localhost/opus4/account/index/index) ein automatischer Logout.

Nach dem POST auf `account/index/save` erfolgen zwei Redirects:

1. GET auf `/account`
2. GET auf `/auth/index/rmodule/account/rcontroller/index/raction/index`

Nach dem 2. Redirect landet man auf der Login-Seite. Dort erscheint allerdings nicht der Hinweis, dass das Passwort erfolgreich geändert wurde, sondern stattdessen eine Fehlermeldung (weil man nicht mehr angemeldet ist):

![image](https://user-images.githubusercontent.com/952735/101384871-4f92e980-38bb-11eb-8948-362861470494.png)

**Comment by j3nsch** [comment]
Es wird jetzt direkt zur Login-Seite umgeleitet und eine grüne Nachricht für die erfolgreiche Änderung ausgeben.
