### ISSUE TITLE
OAI: Namespace-Deklarierung:   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" im Metadata Wurzel Element

### ISSUE THREAD

**Issue by Kaboomki** [OPUS4/application#412]
Hallo, 
wir erhalten von einem Dienst (LeibnizOpen) die Meldung, dass die Indizierung unserer über die Opus4 OAI-Schnittstelle abgerufenen Daten scheitert, weil Opus4 keine explizite Namespace Deklaration für xsi " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" im Wurzel-Element des Metadata Abschnitt ausgibt. Diese erfolgt bei Opus4 übergeordnet als Attribut des OAI-PMH Elements. Die OAI Definition sagt tatsächlich: "every metadata part must include the attribute xmlns:xsi, the value of which must always be the URI shown in the example, which is the namespace URI for XML schema." s. https://www.openarchives.org/OAI/2.0/openarchivesprotocol.2008-12-07.htm#Record

Ich hab versucht, die Wiederholung der xsi Namespace Deklaration in der entsprechenden xsl Prefix Vorlage anzpassen, aber der String wird in der Ausgabe geschluckt. Ich vermute ein Feature der xsl Transformation. 

Das Problem tritt offenbar auch beim harvesten anderer Leibniz Einrichtungen mit Opus4 Installationen auf. Was kann ich antworten? 

Beispiel:
https://zeitgeschichte-digital.de/doks/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:doks.zeitgeschichte-digital.de:78

Vielen Dank!

**Comment by j3nsch** [comment]
Hallo,

ich habe mir das Problem mal angeschaut und habe leider noch keine gute Lösung gefunden. Die Spezifikation verlangt, dass jeder Metadaten-Eintrag die Namespace-Deklaration hat. Das verstehe ich, weil dadurch jeder Eintrag unabhängig vom Container verarbeitet werden kann. Wenn wir in PHP aber das Gesamtdokument erzeugen, wird das anscheinend als redundant betrachtet und automatisch entfernt.

Im Augenblick sehe ich keine Lösung im XSLT. Ich habe bisher nichts gefunden, um das Verhalten des Processors zu verändern. Vielleicht hat jemand anderes eine Idee? 

Ich werde mal schauen, ob wir das Attribut im Post-Processing nachträglich hinzufügen können.

Viele Grüße!

**Comment by j3nsch** [comment]
Ich habe eine Lösung gefunden, auch wenn sie nicht schön ist. Sie wird Teil von OPUS 4.7.1 werden.
