### ISSUE TITLE
Fehler bei XMetaDissPlus-Ausgabe bei Personen ohne Vornamen

### ISSUE THREAD

**Issue by mneufing** [OPUS4/application#420]
In unserem Repo wurde ein Dokument eingestellt, bei dem eine Autor:in keinen Vornamen hat. Wir erhielten dann eine Mail von der DNB mit folgendem Hinweis und der Bitte um korrektur:

> Ein Name im <dc:creator> wird nicht mit richtigen Unterelementen geliefert :
>  
> <dc:creator xsi:type="pc:MetaPers">
> <pc:person>
> <pc:name type="nameUsedByThePerson">
> <pc:surName>Nachname</pc:surName>
> </pc:name>
> </pc:person>
> </dc:creator>
>  
> Wenn ein Name nicht aus Vorname, Nachname besteht, soll in <pc:personEnteredUnderGivenName> angegeben werden :
> <dc:creator xsi:type=“pc:MetaPers“>
> <pc:person>
> <pc:personEnteredUnderGivenName>Nachname</pc:personEnteredUnderGivenName>
> </pc:name> 
> </pc:person>
> </dc:creator>
>

**Comment by mneufing** [comment]
Im der Korrektur fehlt das öffnende <pc:name>-Element. So wäre es richtig:
`<dc:creator xsi:type=“pc:MetaPers“>
<pc:person>
<pc:name type="otherName">
<pc:personEnteredUnderGivenName>Nachname</pc:personEnteredUnderGivenName>
</pc:name> 
</pc:person>
</dc:creator>´

**Comment by j3nsch** [comment]
Vielen Dank! Wir werden die Änderung in den nächsten Patch-Release aufnehmen.

Ein Test muss aktualisiert werden. Darum kümmere ich mich noch vor dem Release.

**Comment by alw-bsz** [comment]
Prinzipiell ist das in Ordnung. Allerdings sollte beachtet werden, dass die primäre Intention von <pc:personEnteredUnderGivenName> ist, Namen, die nicht der Form "Nachname, Vorname" folgen, abbilden zu können. Daher auch der Name des Elements ("under given name"). Insbesondere sind das außereuropäische Namen sowie Pseudonyme. Man sollte dann in der Doku explizit erwähnen, dass solche Namen als Nachname zu erfassen sind und dass bei Erfassung nur des Nachnamens die Übermittlung als sog. persönlicher Name erfolgt. Eigentlich muss man das auch in anderen Formaten nachziehen. In MARC gibt z.B. der erste Indikator bei den Personenfeldern an, um welche Art von Namen es sich handelt.

**Comment by j3nsch** [comment]
Für die Korrektur in anderen Formaten sollten weitere Issues angelegt werden, gerne wieder gleich mit Pull Requests.

Für XMetaDissPlus müsste eigentlich auch noch die Behandlung anderer Personen entsprechend umgebaut werden, oder? Wir haben noch Templates für *PersonAdvisor*, *PersonRefereer* und *PersonEditor*.

**Comment by alw-bsz** [comment]
Ja, die anderen Personen sollten analog behandelt, d.h. also auch <pc:personEnteredUnderGivenName> zusätzlich implementiert werden.

**Comment by j3nsch** [comment]
Änderungen sind im Patch Branch `4.7.0.6` und werden mit dem Release auf den `master` Branch übertragen, voraussichtlich morgen, am 28. September 2021.
