### ISSUE TITLE
Replace echo statements from new Job classes

### ISSUE THREAD

**Issue by kaustabhbarman** [OPUS4/application#442]
In #416, we will have new classes in `library/Job` where the cron job functionalities will be moved into. Since those functionalities were in CRON scripts, the use of `echo` statements were enough. However, after completion of #416, the jobs will end up having `echo` statements which are not appropriate in a class. So we need to figure out something else to deliver the same information while also replacing the `echo` statements.

**Comment by j3nsch** [comment]
Habe gerade gesehen, dass `UpdateDocumentCacheJob` in den Tests mit `echo` Ausgaben macht. Das sollte verhindert werden. Es sollte ein "output"-Objekt verwendet werden, dass dann für die Tests in einen String schreibt und im Betrieb auf die Konsole. Ein Beispiel dafür wäre das `OutputInterface` von Symfony Console, das auch in den OPUS 4 Command-Klassen verwendet wird.

Es muss geprüft werden, ob man `OutputInterface` hier direkt verwenden kann. Außerdem sollte darüber nachgedacht werden, ob es Sinn macht den Job in eine Command-Klasse umzuwandeln und so auch direkt auf der Konsole verfügbar zu machen. Das wäre aber ein separates Ticket. Hier geht es darum die Ausgaben kontrollieren zu können.

**Comment by j3nsch** [comment]
Die folgende Klasse könnte dann als Fallback verwendet werden, damit sich die Job-Klassen, wenn kein Output explizit gesetzt wird, wie bisher verhalten.

https://peridot-php.github.io/docs/class-Symfony.Component.Console.Output.ConsoleOutput.html

**Comment by j3nsch** [comment]
Die Klasse  `CheckWorkspaceFilesJob` gibt während der Tests auf die Konsole aus. Das muss behoben werden.

**Comment by j3nsch** [comment]
Ich gehe davon aus, dass das erledigt ist. Es Änderungen waren Teil eines anderen PRs. Wenn es Probleme gibt, wird das später auffallen.
