### ISSUE TITLE
PDF-Seite generieren

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#452]
Wie kann man mit PHP am Besten eine PDF-Seite generieren, die dann als Deckblatt zum Original-PDF hinzugefügt werden kann? Welche (freien) Tools könnten genutzt werden? 

Man könnten die Seite komplett dynamisch generieren, vielleicht die Metadaten mit XSLT in ein Format umwandeln, z.B. Latex, das dann in ein PDF umgewandelt werden kann. 

Evlt. kann man auch ein Template-PDF mit Platzhaltern verwenden, in dass dann die passenden Metadaten eingefügt werden. Das würde sehr aufwendig gestaltete Deckblätter ermöglichen. 

Wie könnte man damit umgehen, wenn die Platzhalter zu klein sind? Wir haben gerade an anderen Stellen Probleme mit Dokumenten, die 900 Autoren haben (Issue #447).

**Comment by extracts** [comment]
Pandoc kann zur [PDF-Generierung](https://pandoc.org/MANUAL.html#creating-a-pdf) statt LaTeX auch andere Tools benutzen, z.B. [wkhtmltopdf](https://wkhtmltopdf.org/) (über eine intermediäre HTML Datei). Dies könnte event. eine Alternative zur Abhängigkeit von LaTeX sein. Sollte wkhtmltopdf stattdessen direkt genutzt werden, gäbe es dafür auch PHP Wrapper (z.B. [terah/wkhtml-wrapper](https://packagist.org/packages/terah/wkhtml-wrapper)).

**Comment by extracts** [comment]
Das Generieren von [PDF/A](https://en.wikipedia.org/wiki/PDF/A)-kompatiblen PDFs ist potentiell möglich:
1. mittels einer Pandoc/TeX-basierten Engine:
   - PDF/A wird unterstützt wenn Pandoc mit der ConTeXt Engine genutzt wird (siehe `pdfa` Option in Pandoc [Doku](https://pandoc.org/MANUAL.html#variables-for-context) & [Ticket 3215](https://github.com/jgm/pandoc/issues/3215)).
   - für die Engines pdfTEX, LuaTEX & XETEX bietet das [pdfx package](https://www.ctan.org/pkg/pdfx) Unterstützung für PDF/X und PDF/A (siehe dazu auch die tex.stackexchange.com issues [hier](https://tex.stackexchange.com/questions/268923/xelatex-hyperref-and-pdf-a), [hier](https://tex.stackexchange.com/questions/576/how-to-generate-pdf-a-and-pdf-x) & [hier](https://tex.stackexchange.com/questions/255480/producing-pdf-x-compliant-document-with-xelatex)).
2. nicht jedoch mittels einer HTML/CSS-basierten Engine:
   - mir ist momentan zumindest keine Möglichkeit zur Generierung von PDF/A bekannt, für wkhtmltopdf wird es wohl auf absehbare Zeit keine PDF/A-Unterstützung geben (siehe [wkhtmltopdf Ticket 1605](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1605))

**Comment by mpdude** [comment]
Muss das komplett in PHP realisiert sein, oder sind Java-Komponenten eine Option?

**Comment by j3nsch** [comment]
Gibt es Empfehlungen für Java Lösungen? PDF-Box? 

Ich habe dazu Issue OPUS4/opus4-pdf#11 im **opus4-pdf** Repository angelegt. Die Umsetzung, Entwicklung, sollte im gleichen Repository dokumentiert werden. Die Issue hier, dienen mehr der Kommunikation und der allgemeinen Planung. Den richtigen Workflow (Kompromiss) haben wir hier auf GitHub für uns noch nicht gefunden.
