### ISSUE TITLE
Deckblatt Integration in die OPUS 4 Application

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#453]
Die Code für die Handhabung von PDF Dateien sollte in einem neuen Paket **opus4-pdf** gebündelt werden. Nach dem Umstieg auf Laminas sollte aus dem Paket ein richtiges Modul werden, dass zur Application hingefügt werden kann. OPUS 4 sollte daher auch normal funktionieren, wenn das Paket nicht vorhanden oder deaktiviert ist. Nicht jede OPUS 4 Instanz benötigt automatisch generierte Deckblätter. 

Die Integration im die Application sollte vor dem Umbau für Laminas auf so wenig Code wie möglich reduziert werden. Die Deckblatten müssen evtl. in die Download-Mechanismen und/oder den Workflow für Änderungen an Dokumenten integriert werden. 

Später kann **opus4-pdf** vielleicht erweitert werden, so dass auch Prüfungen von PDFs oder das Generieren von Thumbnails möglich sind.

**Comment by extracts** [comment]
siehe auch die Ergänzungen in #563:
* zusätzliche Konfigurationseinstellungen
* beispielhafte Deckblatt-Vorlage zur Demo
* Installation der für die PDF-Generierung momentan nötigen Abhängigkeiten
