### ISSUE TITLE
Setting up the database with MySQL 8.0 using install.sh script doesn't work

### ISSUE THREAD

**Issue by kaustabhbarman** [OPUS4/application#483]
It seems like PHP7.1 doesn't have the support for `caching_SHA2` for MySQL 8. I was getting the following error:

`PHP Fatal error:  Uncaught PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in application/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:128`

I had to downgrade MySQL to 5.7 to resolve this error. I did read somewhere though that PHP7.4 has the support for the same. So we should probably update the userdoc/devdoc of OPUS4 mentioning that MySQL 8 shouldn't be used for the installation.

**Comment by j3nsch** [comment]
A downgrade of MySQL should not be necessary. The authentication method can be configured. It is possible to use the old method with the new database version. Check the MySQL documentation for more information.

**Comment by j3nsch** [comment]
The following commit contains changes of the setup for the database when running the tests with GitHub actions.

https://github.com/OPUS4/application/commit/f63151419a6ad3805a096827bcaf077f0a0864af

The `mysql_native_password` part is responsible for using the old, compatible authentication method.

The SQL part of the installation script and the documentation need to be updated.
