### ISSUE TITLE
URL für die  Pubmed-Id (IdentifierPubmed) in der Frontdoor anpassen

### ISSUE THREAD

**Issue by sigwei** [OPUS4/application#484]
Die URL zur Auflösung der Pubmed-Id (IdentifierPubmed) in der Frontdoor hat sich geändert.

alt: http://www.ncbi.nlm.nih.gov/pubmed?term=

neu: https://pubmed.ncbi.nlm.nih.gov/

**Comment by j3nsch** [comment]
Die URL muss bei dieser Gelegenheit aus den XSLT-Dateien herausgeholt und in die Konfiguration verlagert werden. Das haben wir auch schon für andere Werte gemacht. Dafür gibt es bereits View Helper, die im XSLT eingesetzt werden können.

Wie stark sind die Instanzen im Hosting betroffen? Kann der Patch-Release eine oder zwei Wochen warten, ohne das die Instanzen einzeln angepasst werden müssen oder sollte der Patch morgen veröffentlicht werden?

**Comment by sigwei** [comment]
Da die alte URL noch funktioniert, weil sie weitergeleitet wird, ist das nicht zeitkritisch.

**Comment by j3nsch** [comment]
Gut zu wissen. Dann kommt die Änderung erst mit dem nächsten Patch-Release in zwei Wochen.

**Comment by j3nsch** [comment]
Die URL ist jetzt konfiguriertbar, unter `pubmed.baseUrl`. Die neue URl ist der Defaultwert. Da durch die Änderung, kein Test gebrochen wurde, gehe ich davon aus, dass die Funktionalität nicht getestet ist und werde noch Tests hinzufügen.

**Comment by j3nsch** [comment]
Man könnte natürlich auch einen Tests hinzufügen, der prüft, ob die externe URL noch funktioniert.

**Comment by j3nsch** [comment]
Die URL wird nicht nur in der Frontdoor, sondern auch im Export verwendet.

**Comment by j3nsch** [comment]
Die Änderung ist im Branch 4.7.0.8 für den nächsten Patch-Release.
