### ISSUE TITLE
Skript OPUSHOSTING-481.php entfernen oder überarbeiten?

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#488]
Das Skript `OPUSHOSTING-481.php` verwendet den `DocumentFinder` mit Anpassungen am Zend_DB-Select, um die Datenbank abzufragen. Das Skript muss entweder entfernt werden oder die Abfrage in das Framework ausgelagert werden, da die Application nicht direkt von der Datenbank-Implementation abhängig sein sollte.

**Comment by stconradr** [comment]
Das Script  unter ./scripts/snippets/OPUSHOSTING-481.php wird von uns nicht mehr verwendet. Es wurde mal für das Hosting geschrieben. Aus unserer Sicht kann es weg.

**Comment by j3nsch** [comment]
Datei ist entfernt. Eine Abhängigkeit auf das Datenbankschema weniger.
