### ISSUE TITLE
Original IP-Address für Opus\IpRange im Betrieb mit Proxy

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#504]
Wenn OPUS 4 hinter einem Proxy betrieben wird, muss die originale IP-Adresse für die Zugriffskontrolle mit `Opus\IpRange` verwendet werden.

**Comment by j3nsch** [comment]
Momentan wird im Code noch direkt `$_SERVER` verwendet. In Zend Framework 1 existiert aber die Funktion `getClientIp`. Innerhalb dieser Funktion wird der Header **x-forwarded-for** berücksichtigt. Eine Umstellung des Codes auf die Zend-Funktion sollte ausreichend sein. Die Funktion gehört zur Klasse `Zend_Controller_Request_Http`.

**Comment by j3nsch** [comment]
@alw-bsz, @sigwei, @stconradr Tests müssen dann im Hosting ausgeführt werden. Generell kann ein Client einfach den Header **x-forwarded-for** mitschicken und so seine eigene IP spoofen. Darüber sollte mit den System Admins gesprochen werden, um die Proxies sicher zu konfigurieren. Dazu sollte Dokumentation geschrieben werden (bitte Issue anlegen).

Wir werden den Betrieb mit Proxy in der OPUS 4 Konfiguration explizit aktivieren müssen, damit ohne Proxy die Heade r für das Forwarding komplett ignoriert werden und kein Spoofing möglich ist.

**Comment by j3nsch** [comment]
Die Ermittlung der Client-IP-Adresse liegt jetzt im Zend Framework. Dort werden die verschiedenen möglichen HTTP Header berücksichtigt. Für den Betrieb hinter einem Proxy, muss die Option **proxy.enabled = 1** gesetzt werden. Ansonsten werden "Forwarding" Header ignoriert, um IP Spoofing zu verhindern.

**Comment by sigwei** [comment]
Nach dem Update von Branch 4.7.1 funktioniert die Zugriffskontrolle innerhalb OPUS über IP-Adressbereiche nicht mehr, weder mit noch ohne Proxy (und dem ein-/ausgeschalteten Parameter **proxy.enabled**).

**Comment by j3nsch** [comment]
Wir versuchen die existierende Zend (später Lamina) Funktionalität zu nutzen, um mit Proxies umzugehen. Das wurde ursprünglich nicht gemacht. Unser Code ist daher an den Frameworks "vorbei" implementiert. Bisher wurden die ACLs bereits im Bootstrap initialisiert. Das muss nun später erfolgen, da das Framework (Zend) sonst das Request-Objekt noch nicht existiert in dem die HTTP-Header ausgelesen werden können.

**Comment by j3nsch** [comment]
Der Branch **proxy504** kann jetzt getestet werden. Ich musste einige Anpassungen vornehmen, aber dadurch ist zumindest auch einiger redundanter Code wieder verschwunden. Die Tests sind etwas unübersichtlicher geworden. Das muss beim Umstieg auf Laminas noch mal überprüft werden.

**Comment by sigwei** [comment]
Meine Tests waren nicht erfolgreich, weder mit noch ohne Proxy.

Ob ich Benachrichtigungen bekommen, wenn du mich einmal erwähnt hast, kann ich gerade nicht genau sagen, da ich hier ja auch schon kommentiert habe. Ich habe jedenfalls automatische Benachrichtigungen erhalten, allerdings zeitverzögert (ca. +30 Minuten).

**Comment by j3nsch** [comment]
Danke, dann brauche ich jetzt aber genauere Informationen. Was funktioniert nicht, nur die IP-basierte Zugriffskontrolle oder noch mehr?

**Comment by sigwei** [comment]
Jetzt funktioniert die Zugriffskontrolle über IP-Adressbereiche, sowohl mit, als auch ohne Proxy. 

Der Parameter **proxy.enabled = 1** scheint keine sichtbaren Auswirkungen zu haben. Im Apache-Log landet die Client-IP-Adresse, seitdem wir auf der Seite des Proxys "X-Forwarded-For-Header" aktiviert haben. Aber eben auch, wenn ich **proxy.enabled = 0** konfiguriere. Oder übersehe ich da etwas?

Mit Debug-Logging, **log.level = DEBUG**, sehe ich die Client-IP-Adresse im opus.log. Es ist bei mir eine IPv4-Adresse. Deshalb klappte die Zugriffskontrolle über IP-Adressbereiche bisher (OPUS 4.7.0.7).

**Comment by j3nsch** [comment]
Wenn Proxy ausgeschaltet ist, dann sollte der Forwarded-Header ignoriert werden. Das folgende ist der Code für die Auswertung.

```
       if ($checkProxy && $this->getServer('HTTP_CLIENT_IP') != null) {
            $ip = $this->getServer('HTTP_CLIENT_IP');
        } else if ($checkProxy && $this->getServer('HTTP_X_FORWARDED_FOR') != null) {
            $ip = $this->getServer('HTTP_X_FORWARDED_FOR');
        } else {
            $ip = $this->getServer('REMOTE_ADDR');
        }
```

**Comment by j3nsch** [comment]
Die IPv6 Prüfung war nach den Änderungen fehlerhaft, aber wie gesagt, es gab keine Tests, die das geprüft hätten.

**Comment by j3nsch** [comment]
Ich habe jetzt noch einen Test hinzugefügt, der prüft, welches Feld ausgewertet wird, wenn Proxy enabled/disabled ist. Das Verhalten ist wie erwartet. Der Forwarded-Header wird nur verwendet, wenn Proxy enabled ist. Was ich nicht sagen kann, ist was bei Eurem Setup an Headern bei OPUS 4 ankommt. Die Client-IP landet im Debug-Modus momentan immer im Log. Das ist unabhängig von der Proxy Einstellung.

**Comment by stconradr** [comment]
Die Zugriffskontrolle über IP-Adressbereiche funktioniert bei mir nun ebenfalls, sowohl mit, als auch ohne Proxy.

Der Parameter proxy.enabled = 0 zeigt kein anderes Verhalten.
Wir protokollieren im Apache-Log aber auch nur die Client-IP-Adresse.

**Comment by stconradr** [comment]
Im opus.log wird die Client-Adresse protokolliert. Aber es scheint so, dass die Einstellung  proxy.enabled = 0/1 keinen Einfluss hat, da es sowohl mit der Einstellung proxy.enabled = 1 und auch mit proxy.enabled = 0 funktioniert.

**Comment by sigwei** [comment]
Im opus.log ist jetzt zu sehen `Check-Proxy: false` bzw. `Check-Proxy: true` , aber es kommt weiterhin in beiden Fällen die Client-IP-Adresse mit, nicht die Adresse des Proxy-Servers.

**Comment by j3nsch** [comment]
Ich habe noch eine Zeile hinzufügt, um alle HTTP-Header ins Log zu schreiben. Das nehmen wir hinterher wieder raus oder führen dafür noch eine extra Option ein.

**Comment by j3nsch** [comment]
Wenn die Ursache nicht im Proxy-Server liegt, dann gibt es in PHP/Zend/OPUS4 irgendwo noch anderen Code, der den Forward-Header auswertet. In diesem Fall müssen wir schauen wie das deaktiviert werden kann bzw. prüfen, ob damit ein IP-Faking möglich ist. Ihr tut dann im Prinzip so als wärt Ihr ein Proxy.

**Comment by stconradr** [comment]
Folgender Forward-Header ist im opus.log zu sehen:

2022-02-15T13:18:14+01:00 DEBUG (ID 620b9a06cd2dd): <pre>HTTP-Headers array(11) {
  [&quot;Host&quot;] =&gt; string(12) &quot;<Zielhostname>&quot;
  [&quot;User-Agent&quot;] =&gt; string(78) &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/
20100101 Firefox/78.0&quot;
  [&quot;Accept&quot;] =&gt; string(74) &quot;text/html,application/xhtml+xml,application/xml;q=0.9,image/w
ebp,*/*;q=0.8&quot;
  [&quot;Accept-Language&quot;] =&gt; string(23) &quot;de,en-US;q=0.7,en;q=0.3&quot;
  [&quot;Accept-Encoding&quot;] =&gt; string(17) &quot;gzip, deflate, br&quot;
  [&quot;Referer&quot;] =&gt; string(43) &quot;https://<Proxyhostname>/opus4-xxxx/home&quot;
  [&quot;Cookie&quot;] =&gt; string(66) &quot;PHPSESSID=q6kcgtk94mhj8o0kldq6be4fp4; cookieconsent_status=di
smiss&quot;
  [&quot;Upgrade-Insecure-Requests&quot;] =&gt; string(1) &quot;1&quot;
  [&quot;X-Forwarded-Host&quot;] =&gt; string(16) &quot;<Proxyhostname>&quot;
  [&quot;X-Forwarded-Server&quot;] =&gt; string(16) &quot;<Proxyhostname>&quot;
  [&quot;Connection&quot;] =&gt; string(10) &quot;Keep-Alive&quot;
}
</pre>

**Comment by j3nsch** [comment]
Die notwendigen Änderungen sind in 4.7.1
