### ISSUE TITLE
OPUS 4 mit Vagrant unter Windows

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#529]
Das `Vagrantfile` im Hauptverzeichnis der OPUS 4 Application erlaubt es ein komplettes OPUS 4 mit wenigen Kommandos zu starten. Das ist vor allem für Tests hilfreich. Dafür sind Vagrant und Virtual Box notwendig. Unter Linux und Mac OS-X konnte das schon erfolgreich getestet werden, aber unter Windows gibt es noch Schwierigkeiten. 

Eine kurze Anleitung findet sich im Wiki.

https://github.com/OPUS4/application/wiki/Vagrant

**Comment by j3nsch** [comment]
Bei mir, mit Windows 11 und aktuellen Versionen von Virtual Box und Vagrant, ohne weitere Konfiguration, bleibt `vagrant up` beim Hochfahren bei "SSH auth method: private key" hängen.

**Comment by j3nsch** [comment]
@alw-bsz Bis jetzt konnte ich bei mir die VM noch nicht hochfahren. Eine andere Ubuntu VM hat funktioniert. Bei mir sind WSL und auch die "offiziellen" Git Tools installiert. Den Clone habe ich mit der Git Bash gemacht.

Vagrant ist unter Linux auf jeden Fall ein wertvolles Tool, weil man wie gesagt ohne Aufwand eine VM für einen anderen Branch hochfahren und testen kann. Es wäre aber natürlich gut, wenn das auch unter Windows funktionieren würden. Allerdings zeigt sich doch, dass das nicht so einfach ist.

**Comment by alw-bsz** [comment]
@j3nsch Bei mir hängt er auch an dieser Stelle, umschifft sie dann aber durch Erzeugen eines neuen Keys:

```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
```

Die VM fährt dann hoch und ich kann mich auch mit vagrant ssh verbinden. 

Ich verwende Windows 10, ebenfalls mit aktuellen Versionen von Virtual Box und Vagrant, WSL sowie Git sind auch installiert. Ich arbeite in der PowerShell. Hyper-V habe ich gem. Anleitung deaktiviert (https://www.vagrantup.com/docs/installation).

**Comment by j3nsch** [comment]
Den kurzen "Hänger" an dieser Stelle (SSH) gibt es auch unter Linux. Das sehe ich als normal. Bei mir geht es überhaupt nicht weiter und nach einer Weile kommt ein Timeout. Ich musste bei mit das Windows Feature **Virtual Machine Platform** abschalten. Damit bin ich jetzt zumindest bis zu dem Problem beim Aufruf von **composer** während des Setups gekommen. Ich schaue mir das weiter an.

**Comment by j3nsch** [comment]
Das nächste Problem, dass ich habe, ist anscheinend, dass mein Clone Dateien mit Windows Zeilenenden erzeugt hat. Jetzt in der VM läuft aber eine Linux-Umgebung und die stört sich daran. Deshalb hat das `bin/install-composer.sh` Skript gerade **bash** nicht gefunden.

**Comment by j3nsch** [comment]
Ich komme jetzt bis zum Permission-Problem, bei der Ausführung von Composer. Wenn ich dann in die VM gehe mit `vagrant ssh` und `bin/composer update` manuell ausführe, funktioniert das. Man könnte jetzt also vermutlich die restlichen Schritte manuell ausführen, um zu einem lauffähigen Windows zu kommen. Das wäre natürlich wieder sehr umständlich. Mal sehen, was sich machen lässt.

**Comment by j3nsch** [comment]
Ich experimentiere noch mit den Problem, aber ich denke es wäre eine gute Idee die Setup-Schritte aus der `Vagrantfile`-Datei herauszuziehen, damit sie auch nach dem Hochfahren der VM noch manuell gestartet werden können. Es macht sowieso Sinn die Redundanz zwischen Installationsskripten und `Vagrantfile` zu beseitigen.

**Comment by j3nsch** [comment]
Während des "Provisioning" in Vagrant wird die Composer-Datei nicht als ausführbar angezeigt, im Gegensatz zum Zustand, wenn man mit SSH in der VM unterwegs ist. Das wäre die Ursache für das Problem.

Composer wird jetzt mit `php bin/compose` ausgeführt. Das hilft. Die Änderungen sind jetzt auf dem 4.7.1 Branch. Ich bin noch dabei das vollständige Setup zu prüfen. Der Prozess dauert unter Windows 11 auf meinem System etwas länger.

**Comment by j3nsch** [comment]
Mit der Änderung komme ich jetzt bis zur Initialisierung der Datenbank, genauer gesagt das Cleanup der Verzeichnisse danach. 

```
rm: cannot remove '/vagrant/tests/../workspace/log/error.log': Text file busy
```

Auch das Problem tritt nicht mit Linux oder Mac OS-X als Host-System auf. Ich werde schauen, wie man das umschiffen kann.

**Comment by j3nsch** [comment]
Wenn man nach diesem Fehler, die VM mit `vagrant halt` und dann mit `vagrant up` neu startet, kann man sich anschließend mit `vagrant ssh` eingeloggen. Der Index muss noch initialisiert werden mit `opus4 index:index`. Anschließend hat man eine vollständige Testinstallation von OPUS 4.

Das Kommando `ant reset-testdata` , das auch während des Provisioning ausgeführt wird, führt zu der gleichen Fehlermeldung. Die Datei wird von Apache2 geschrieben. Unter Windows als Host, lässt sich die Datei nicht einfach löschen. Durch dieses Problem lässt sich unter Windows mit Vagrant momentan kein komplettes Cleanup der Instanz mit einem Kommando ausführen, sondern der Reset der Datenbank und die Neuindexierung müssen separat ausgeführt werden. 

Es können vielleicht Änderungen an den Skripten vorgenommen werden, die dieses Problem nicht lösen, aber umgehen. Das muss ich noch mal drüber nachdenke. Als ersten Schritt könnte man die verschiedenen Schritt, Datenbank, Workspace und Indexierung unabhängig voneinander machen und dann beim Workspace-Cleanup gezielt dieses Problem vermeiden, indem man die `error.log` Datei in Ruhe lässt. Es sollte auch geklärt werden, warum die Datei dorthin geschrieben wird. Das ist ohne Vagrant, in einem normalen Setup mit Ubuntu 20.04 nicht der Fall.

**Comment by j3nsch** [comment]
@sigwei, @stconradr Es gibt noch Schwierigkeiten mit dem Cleanup-Skript, aber mit Branch 4.7.1 habe ich ein lauffähiges OPUS 4 unter Windows 11 erzeugen können. Die notwendigen Schritte waren.

- Installation VirtualBox
- Installation Vagrant
- Installation von WSL mit Git (@alw-bsz ?) oder Git für Windows von https://git-scm.org
- Clone von Branch 4.7.1 (`git clone --branch 4.7.1 https://github.com/OPUS4/application.git opus4`), wobei darauf geachtet werden muss, das die Zeilenendezeichen UNIT konform bleiben und nicht für Windows umgewandelt werden.
- Windows Feature **Virtual Machine Platform** musste bei mir abgeschaltet werden (@alw-bsz ?)
- `vagrant up` bis zum Fehler mit `error.log`
- `vagrant halt`
- `vagrant up`
- `vagrant ssh` und dann `opus4 index:index` für das Befüllen des Search-Index

Anschließend ist OPUS 4 unter `http://localhost:8080/opus4` verfügbar.

**Comment by j3nsch** [comment]
Der Ort für die Log-Datei wird in `apacheconf/apache.conf` definiert. Auf dem Entwicklungssystem wird nie etwas in diese Datei geschrieben, sonst gäbe es das Problem vielleicht dort auch.

**Comment by alw-bsz** [comment]
Besten Dank, jetzt hat es auch bei mir funktioniert, OPUS 4 mit Vagrant zum Laufen zu bringen.

WSL habe ich nicht mit Git installiert, sondern entweder über die Systemsteuerung aktiviert (Windows 10: "Systemsteuerung" > "Programme" > "Windows-Features aktivieren oder deaktivieren") oder über die Kommandozeile installiert (vgl. https://docs.microsoft.com/en-us/windows/wsl/install).  Ich weiß nicht mehr, welchen Weg ich gegangen bin, da ich WSL schon seit längerer Zeit nutze.

Ich nehme an, dass der "Virtual Machine Platform" unter der deutschen Oberfläche die "Plattform für virtuelle Computer" entspricht. Die ist bei mir aktiviert.

**Comment by j3nsch** [comment]
Gut, dass es funktioniert. Ich versuche es heute noch zu vereinfachen. "WSL mit Git" war so gemeint, dass Git mit WSL verwendet wurde (meine Vermutung), statt Git separat zu installieren. 

Ja, bei mir musste die "VM Plattform" deaktiviert werden, vielleicht ein Unterschied zwischen Windows 10 und 11. Keine Ahnung! :)

**Comment by j3nsch** [comment]
Am Besten Git und Composer Updates, sowie Wechsel zu einem anderen Branch mit `vagrant ssh` innerhalb der laufenden VM machen. Das scheint mir im Augenblick einfacher als für aktuelles Testing eine neue VM zu erzeugen.

**Comment by j3nsch** [comment]
Ich verhindere jetzt, dass `workspace/log` komplett gelöscht wird. Dadurch kommt es nicht mehr zum Fehler bei der Initialisierung der Testdaten mit Vagrant unter Windows. Damit konnte ich jetzt die VM mit `vagrant up` in einem Schritt erzeugen und hatte am Ende ein laufendes OPUS 4.

**Comment by j3nsch** [comment]
@alw-bsz, @sigwei, @stconradr Ich würde das Ticket erst einmal für erledigt halten. Das wichtigste wären noch Hinweise zu Windows in der Dokumentation. Das gehört nicht ins OPUS 4 Handbuch, sondern in das Wiki hier für Application. Darum werde ich mich im Augenblick nicht kümmern können. Das Handbuch könnte einen Verweis auf die "Entwickler/Tester" Dokumentation enthalten.
