### ISSUE TITLE
Installationsskript bricht ab nach Eingabe des OPUS 'admin' Passwords

### ISSUE THREAD

**Issue by sigwei** [OPUS4/application#538]
Das Installationsskript `bin/install.sh` bricht nach der Eingabe des OPUS 'admin' Password ab.

```
Please enter password for OPUS 'admin' account:
Please enter password again:
PHP Warning:  require_once(autoload.php): failed to open stream: No such file or directory in /home/opus/opus4/scripts/common/bootstrap.php on line 60
PHP Fatal error:  require_once(): Failed opening required 'autoload.php' (include_path='.:/home/opus/opus4/scripts/common:/home/opus/opus4/library:/home/opus/opus4/vendor:.:/usr/share/php') in /home/opus/opus4/scripts/common/bootstrap.php on line 60
```

**Comment by j3nsch** [comment]
Branch *install* sollte das fixen. Die Fehlermeldung deutet darauf hin, dass `composer install` vom Skript nicht ausgeführt wurde und das liegt an Änderungen im Installationsskript für Composer, `install-composer.sh`. Das Skript hat vorher automatisch die Composer Packages installiert und dafür sollte es nicht verantwortlich sein.

**Comment by j3nsch** [comment]
Ich habe #540 angelegt, um die "Installation" und das "Setup" in Zukunft von einander zu trennen.

**Comment by j3nsch** [comment]
Der Aufruf von `composer install` funktioniert noch nicht richtig mit den Änderungen. Composer kann nicht einfach direkt aufgerufen werden, wenn das Installationsskript mit "sudo" ausgeführt wird.

**Comment by sigwei** [comment]
Jetzt bekomme ich folgenden Fehler:

```
Installing Composer and dependencies ...

sudo: /home/opus/opus4/bin/composer install: command not found
```

Und ohne "sudo":

```
Installing Composer and dependencies ...

bin/install.sh: line 123: php /home/opus/opus4/bin/composer install: No such file or directory
```

Außerhalb des Installationsskripts funktioniert "bin/composer install".

**Comment by j3nsch** [comment]
Ja, das meine ich. Deshalb macht das neue Ticket Sinn, die Installation und das Setup zu trennen, aber ich werde das jetzt nicht angehen. Für "sudo" ist die Umgebung anders und deshalb funktioniert dort nicht alles genauso wie ohne. Ich schau mal.

**Comment by j3nsch** [comment]
Ich habe die Installation der Packages, jetzt erst einmal wieder als Option in das `install-composer.sh` Skript eingebaut. Das war einfacher als ein zweites Skript anzulegen, nur um ein Kommando aufzurufen. Den direkten Aufruf in `install.sh` Skript habe ich im Augenblick nicht hinbekommen.

**Comment by sigwei** [comment]
Danke, das funktioniert jetzt.

**Comment by j3nsch** [comment]
Danke für die Tests. Ich pack das auf den MASTER als "heimlichen" Patch.
