### ISSUE TITLE
Library/Application/import nach "opus4-import" auslagern

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#544]
Der Code im Import-Verzeichnis sollte nach "opus4-import" ausgelagert werden und dort auf passende Namespaces verteilt werden. 

Das ist eine Teilaufgabe von #363 und #543.

**Comment by j3nsch** [comment]
In **opus4-common** muss auch ein Issue dafür angelegt werden.

**Comment by j3nsch** [comment]
Intern: https://tickets.zib.de/jira/browse/OPUSVIER-4470

Das Import-XSD existiert doppelt. Durch die Verschiebung kann das bereinigt werden. Es muss geprüft werden, welche Unterschiede zwischen den Dateien existieren. Die Datei in Application scheint die neuere zu sein. Am Ende sollte es nur noch eine XSD-Datei geben.

**Comment by j3nsch** [comment]
Die Klassen können erst einmal alle in den Namespace `Opus\Import` gehen.

**Comment by j3nsch** [comment]
Es kann sein, dass für den Import Code Teile der Konfiguration aus `application.ini` mit übertragen werden müssen bzw. das zusätzliche Ressourcen initialisiert werden müssen. Das Framework braucht ja wesentlich weniger und der bisherige Code in **opus4-import** kam aus dem Framework, während der neue Code aus der Application kommt. 

Wenn es Probleme gibt hier festhalten, so dass das dann auch gleich dokumentiert ist und wir überlegen können wie man damit am Besten umgehen kann.

**Comment by haogatyp** [comment]
Durch das Verschieben nach opus4-import ergab sich eine Abhängigkeit zur Klasse FileTypes in application. Für den Abschluss des Issues muss diese erst aufgelöst werden. Hierzu gibt es in opus4-commen das Issue [#56](https://github.com/OPUS4/opus4-common/issues/56)

**Comment by j3nsch** [comment]
Für die Konsolidierung der beiden XSD Dateien habe ich Issue OPUS4/opus4-import#11 angelegt.
