### ISSUE TITLE
Composer Paket für Pandoc austauschen

### ISSUE THREAD

**Issue by extracts** [OPUS4/application#549]
Das in opus4-bibtex verwendete Paket [ryakad/pandoc-php](https://packagist.org/packages/ryakad/pandoc-php) zum Aufruf von Pandoc wird anscheinend nicht mehr weiterentwickelt.

Stattdessen könnte man das Paket [ueberdosis/pandoc](https://packagist.org/packages/ueberdosis/pandoc) verwenden, welches besser "maintained" scheint und auch mehr Möglichkeiten bietet. Letzteres wird auch bereits in opus4-pdf verwendet.

**Comment by j3nsch** [comment]
Ich glaube das Problem ist, dass wir **pandoc-php** gar nicht direkt verwenden, sondern es für **renanbr/bibtex-parser** notwendig. Es kann also nicht ausgetauscht werden, ohne den BibTeX-Parser auszutauschen. Die Packages sollten aber koexistieren können, oder?

**Comment by extracts** [comment]
Ja, korrekt, das war mir zwischenzeitlich entfallen, sorry. Ich denke, dass die Pakete koexistieren können.

**Comment by j3nsch** [comment]
Ich denke das hat sich erledigt. Die beiden Abhängigkeiten können parallel existieren.
