### ISSUE TITLE
Ändern des Dokumenttyps beim automatischen Befüllen des Veröffentlichungsformulars

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#551]
Der Dokumenttyp soll während des Veröffentlichungsvorgangs automatisiert geändert werden können. Benötigt wird diese Funktionalität für die Population des Metadatenformulars per DOI.  Für eine einfachere Implementation und Wartbarkeit sowie bessere Usability wollen wir den DOI-basierten Import nicht in die dokumenttypspezifischen Metadatenformulare einpassen. Unser Ansatz ist stattdessen, einen Pseudo-Dokumenttyp einzurichten mit allen Feldern, die Crossref liefern kann (ähnlich dem Typ ‚All‘). Der Pseudo-Dokumenttyp soll dann anhand des von Crossref übermittelten Publikationstyps automatisiert auf den entsprechenden OPUS-Dokumenttyp geändert werden. Die Änderung des Dokumenttyps müsste auf der 2. Seite des Veröffentlichungsformulars möglich sein, mittels eines eigenen Formularfeldes mit eigener ID (damit es von JS ansprechbar ist).

**Comment by j3nsch** [comment]
Das Publish-Formular soll ja überarbeitet werden, aber temporär im alten Formular, wäre es vermutlich relativ einfach ein weiteres unsichtbares (HIDDEN) Formularfeld für den Dokumenttyp hinzuzufügen und beim Speichern im Dokument zu setzen. Das könnte vermutlich mit relativ wenig Aufwand integriert werden ohne das Verhalten des alten Codes für das Publish-Formular stark ändern zu müssen.

**Comment by j3nsch** [comment]
Ich habe mir den Code angeschaut. Durch den Template-Mechanismus, der unbedingt mit dem neuen Publish-Formular ersetzt werden sollte, ist es schwierig das Problem im Code zu alleine zu lösen. In dem Template für den DOI-Typ muss ein `<input type="hidden">`-Element hinzugefügt werden. Der Name könnte "DocumentType" lauten. Es spielt hier im Augenblick nicht wirklich eine Rolle. Ich werde den Code, der den POST vom Formular für dieses Feld erweitern, so dass der Typ gesetzt wird. Das sollte dann eigentlich reichen. Es sei denn der Typ soll auch noch editierbar gemacht werden. Das wäre aber auch nicht schwer.

**Comment by j3nsch** [comment]
Das Setzen des Dokumenttyp muss an dem normalen Code für das Formular vorbei passieren und kann erst beim endgültigen Abspeichern gesetzt werden. Die Anzeige des Typs als Überschrift im letzten Formular muss angepasst werden, damit sie stimmt. Ansonsten muss der Typ ignoriert werden, da ansonsten das Formular entsprechend dem Typ generiert und validiert wird, also nicht mehr nach dem DOI-Import-Typ. 

Das heißt aber auch, dass Dokumente angelegt werden können, die nicht den Anforderungen für ihren Typ entsprechen. Vielleicht ist es möglich die Validierung entsprechend dem gewählten Typ durchzuführen, aber das Formular für den DOI-Import-Typ zu generieren, auch nach der Validierung.

**Comment by j3nsch** [comment]
Anpassung ist im Branch **issue551** (passend zum Issue). Zum Template für den DOI-Typ muss ein verstecktes Feld hinzugefügt werden.

```
<input type="hidden" name="DocumentType" value="" />
```

Auf der Check-Seite wird der gesetzte Dokumenttyp angezeigt und beim Speichern berücksichtigt. Eine Validierung entsprechend dem Dokumenttyp ist nicht möglich. Das kann im neuen Publish-Modul umgesetzt werden, aber der Aufwand im aktuellen Code wäre beträchtlich und der Code müsste später weggeworfen werden.

Es muss noch geprüft werden, im Zusammenhang mit dem Javascript Code zum Befüllen des Formulars, wie das Verhalten ist, wenn vom Check-Formular für Änderungen zum Metadaten-Formular, dem zweiten, zurück gewechselt wird.

**Comment by alw-bsz** [comment]
Vielen Dank für die schnelle Bearbeitung @j3nsch ! Wir testen das und geben eine Rückmeldung.

**Comment by alw-bsz** [comment]
Wir haben es getestet und das Ändern des Dokumenttyps funktioniert - besten Dank!

Allerdings gibt es folgende Fehlermeldung im error.log des Apache, wenn auf der Seite publish/form/upload im Feld DOI etwas eingetragen ist und man auf den "Weiter"-Button klickt (im Browser erscheint eine leere Seite):

`
[Fri Apr 08 13:41:36.927343 2022] [php7:error] [pid 2810] [client 10.0.2.2:61604] PHP Fatal error:  Uncaught Error: Class 'Repository' not found in /vagrant/modules/publish/models/ExtendedValidation.php:828\nStack trace:\n#0 /vagrant/modules/publish/models/ExtendedValidation.php(94): Publish_Model_ExtendedValidation->_validateDoi()\n#1 /vagrant/modules/publish/forms/PublishingSecond.php(65): Publish_Model_ExtendedValidation->validate()\n#2 /vagrant/modules/publish/controllers/FormController.php(312): Publish_Form_PublishingSecond->isValid(Array)\n#3 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Publish_FormController->checkAction()\n#4 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('checkAction')\n#5 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))\n#6 /vagrant/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Boots in /vagrant/modules/publish/models/ExtendedValidation.php on line 828, referer: http://localhost:8080/opus4/publish/form/upload
`

**Comment by j3nsch** [comment]
Ist die Vagrant-VM neu? Wenn nicht, müsst Ihr vielleicht ein Update der Composer Packages durchführen. DIe `Repository` Klasse existiert in **opus4-common**.

**Comment by j3nsch** [comment]
Ich habe gerade gesehen, da ist ein Typo im `use` Statement für die Klasse. Das ist dann ein Bug in 4.7.1, der durch keinen automatischen oder manuellen Test erwischt wurde. Ich muss das auf dem MASTER-Branch fixen.

**Comment by alw-bsz** [comment]
Ok, das passt dann; die Vagrant-VM hatte ich erst gestern erstellt.

**Comment by j3nsch** [comment]
Ich habe es in **master** und **issue551** gefixt. Ich weiß nicht was diese Validierung auslöst. Ich habe in den letzten Tagen ja auch mit dem Publish-Formular getestet und keine Probleme gehabt. Es macht mir Sorgen, dass der Typo unbemerkt geblieben ist.

**Comment by alw-bsz** [comment]
Vielen Dank für den schnellen Fix - jetzt funktioniert es fehlerfrei :-)
