### ISSUE TITLE
Verwenden von FileTypes aus opus4-common

### ISSUE THREAD

**Issue by haogatyp** [OPUS4/application#552]
Der nach opus4-common ausgelagerte Code in Form der neuen FileTypes-Klasse, siehe auch Issue OPUS4/opus4-common#56, muss in der entsprechenden FileTypes-Klasse in application verwendet werden, so dass die Methoden an die neue Klassen delegieren.

**Comment by j3nsch** [comment]
Das ist erledigt, oder?
