### ISSUE TITLE
Verlinkung der GND-Schlagwörter mit dem zugehörigen "ExternalKey"  im XSLT der Frontdoor einbauen

### ISSUE THREAD

**Issue by stconradr** [OPUS4/application#562]
Derzeit werden die GND-Schlagworte,  nur als normale Schlagworte ausgegeben. Es fehlt eine Verlinkung des GND-Eintrags zur Seite 
mit den zugehörigen Infos.  Bei der Erfassung z.B. als Admin/Reviewer kann die GND-ID im Feld "external_key" aufgenommen werden. Sie ist vorhanden, wird aber nicht mit den XSLTs, welche für die Frontdoor bisher verwendet werden, ausgelesen und verwendet. 
Es müsste eine Abfrage im  PHP/XSLT für die GND-ID eingebaut werden, die eine Verlinkung zu dem zugehörigen ExternalKey durchführt.

**Comment by j3nsch** [comment]
Hier ist mindestens noch die Information notwendig, wie die Links aussehen müssen, was die Base-URL ist.

**Comment by alw-bsz** [comment]
Die URL zur GND in "herkömmlicher" Visualisierung lautet:
`https://d-nb.info/gnd/<GND-ID>`
Beispiel: https://d-nb.info/gnd/11907575X

Als Beta-Version liegt der "GND-Explorer" vor, der das neue Anzeige- und Recherchetool für die Gemeinsame Normdatei werden soll. Hier lautet die URL:
`https://explore.gnd.network/gnd/<GND-ID>`
Beispiel: https://explore.gnd.network/gnd/11907575X

**Comment by j3nsch** [comment]
In der Konfiguration gibt es bereits `gnd.baseUrl`. Der Defaultwert ist momentan `http://d-nb.info/gnd/`. Das sollte gleich auf `HTTPS` geändert werden.
