### ISSUE TITLE
Deckblätter: PDF Cover Demo

### ISSUE THREAD

**Issue by extracts** [OPUS4/application#563]
Zur Demonstration der PDF Deckblatt Funktionalität wird ein Branch bereitgestellt, welcher nach dem [Setup mit Vagrant](https://github.com/OPUS4/application/wiki/Vagrant) in der `testing` environment[1] automatisch jeder heruntergeladenen Datei ein beispielhaftes PDF-Deckblatt voranstellt.

Die verwendete Deckblatt-Vorlage befindet sich unter `tests/resources/covers/demo/demo-cover-template.md`. Diese wird in `application/configs/config.ini` wie folgt verwendet:

```
; PDF COVER SETTINGS
; if set to `1` PDF cover pages may be added in front of downloaded PDF files
pdf.covers.generate = 1
; path to the covers directory that stores PDF cover templates
pdf.covers.path = APPLICATION_PATH "/tests/resources/covers"
; path relative to the covers directory pointing to a default cover template
pdf.covers.default = 'demo/demo-cover-template.md'
```

[1] Für die Aktivierung der `testing` environment sollte in Datei `apacheconf/apache.conf` die folgende Zeile verfügbar gemacht und Apache neugestartet werden:
```
SetEnv APPLICATION_ENV testing
```

### Testhinweise

Die mit einem Deckblatt versehenen, heruntergeladenen Dateien werden im `workspace/filecache` Verzeichnis gecached. Solange eine gecachte Version existiert und sich das Dokument der Datei nicht ändert, wird diese gecachte Version bei darauf folgenden Download-Anfragen ausgeliefert. Um beim Testen ein erneutes Erstellen des Deckblattes zu Erzwingen muss daher die gecachte Version gelöscht werden.

**Comment by j3nsch** [comment]
Ich denke das sollte mit dem **demo-cover.md** Template erledigt sein.
