### ISSUE TITLE
Abbruch des Publishprozesses beim Speichern bei Vorhandensein einer DOI

### ISSUE THREAD

**Issue by stconradr** [OPUS4/application#565]
Version 4.7.1
Wird beim Publishprozess eine DOI im Feld IdentfierDoi erfasst, dann kommt es beim Speichern zu einem Fehler und zum Abbruch des Publishprozesses.

Folgende Fehlermeldung:
`Fatal error: Uncaught Error: Class 'Repository' not found in /home/opus/opus4-demo-intern/modules/publish/models/ExtendedValidation.php:828 Stack trace: #0 /home/opus/opus4-demo-intern/modules/publish/models/ExtendedValidation.php(94): Publish_Model_ExtendedValidation->_validateDoi() #1 /home/opus/opus4-demo-intern/modules/publish/forms/PublishingSecond.php(65): Publish_Model_ExtendedValidation->validate() #2 /home/opus/opus4-demo-intern/modules/publish/controllers/FormController.php(299): Publish_Form_PublishingSecond->isValid(Array) #3 /home/opus/opus4-demo-intern/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Publish_FormController->checkAction() #4 /home/opus/opus4-demo-intern/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('checkAction') #5 /home/opus/opus4-demo-intern/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Re in /home/opus/opus4-demo-intern/modules/publish/models/ExtendedValidation.php on line 828`

**Comment by j3nsch** [comment]
Das wurde bereits nach dem Release gefixt. Die Änderung ist auf dem MASTER-Branch und muss mit `git pull` übernommen werden. Sonst ist nichts weiter notwendig.

**Comment by j3nsch** [comment]
Das Problem wurde in #553 behandelt.
