### ISSUE TITLE
Download von PDFs in der Administration ohne Deckblatt

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#569]
Beim Download von PDFs in der Frontdoor können automatisch Deckblätter hinzugefügt werden. Dabei wird das Original-PDF nicht verändert, sondern das Deckblatt vor dem Download generiert und mit dem Original-PDFs als neues PDF im Cache gespeichert. Die Download-Links in der Administration laufen über die gleiche URL und werden daher genauso behandelt. In der Administration sollte es möglich sein, dass Original-PDF herunterzuladen. 

Die Erzeugung des Deckblattes sollte nicht über Parameter gesteuert werden, da das die Idee unterwandern würde. Auch kann nicht automatisch auf Deckblätter verzichtet werden, wenn ein Administrator eingeloggt ist. Die Downloads in der Administration sollten daher eine andere URL verwenden, die keine Deckblätter generiert und nur für Admins zugänglich ist.

**Comment by j3nsch** [comment]
@alw-bsz Es kann natürlich sein, dass manche Instanzen damit einverstanden wären die Deckblatt-Generierung über einen Parameter steuerbar und damit auch für Nutzer optional zu machen, aber eine separate URL sollte alle Anwendungsfälle abdecken.

Für diese Änderung müssen wir den Download-Code aus dem `DeliverController` herausziehen, sowieso eine gute Idee, so dass wir ihn in zwei Controllern für die unterschiedlichen URLs wiederverwenden können. Evlt. werden es auch einfach zwei unterschiedliche Actions im gleichen Controller. Auch dann ist eine Auslagerung des eigentlichen Codes in eine separate Klasse sinnvoll.

Es gibt eine kurze URL für Downloads, die in der Apache Konfiguration für OPUS 4 gewandelt wird. Ich denke das sollte keine Probleme verursachen, aber wir müssen das nach den Änderungen prüfen.

**Comment by alw-bsz** [comment]
Ich denke auch, dass eine separate URL besser ist. Parameter lassen sich ggf. leichter erraten und aufrufen, auch wenn das nicht intendiert ist.

**Comment by j3nsch** [comment]
Ein Parameter ist auch kein Problem, weil der Parameter nur für Administratoren verfügbar wäre. In der Administration sollten Download-Links die Originaldatei liefern. Das könnte über einen Parameter passieren, der für Nicht-Admins ignoriert wird, oder über eine separate URL, bei der der Parameter dann nicht notwendig ist. Es geht also eigentlich auch mit nur einer URL. 

In beiden Fällen sollte es möglichst wenig redundanten Code geben. Falls zwei Controller/URLs umgesetzt werden, könnte es eine Basisklasse geben, die für die andere URL/Anwendung erweitert wird, also z.B. "Download" und "Download mit Deckblatt".

Admin-Links für den Download mit Deckblatt könnten in der Administration hinzugefügt werden, sind aber nicht dringend, da der Download mit Deckblatt ja auf jeden Fall über die Frontdoor möglich ist.

**Comment by j3nsch** [comment]
Für die Umsetzung lohnt es sich wie immer über das Software-Design nachzudenken, aber wir haben viele andere Aufgaben. Eine Lösung, die funktioniert und sich bei Bedarf später leicht ausbauen bzw. ändern lässt reicht.
