### ISSUE TITLE
Konsolenkommando für Verknüpfungen mit Sammlungen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#576]
Es soll ein Kommando geben, mit dem die Verknüpfungen für mehrere Dokumente manipuliert werden können. Das kann z.B. für Anpassungen verwendet werden, die durch Änderungen in der Abteilungsstruktur von Instituten notwendig werden. Folgende Operationen sind denkbar

- Dokumenten einer Sammlung soll eine weitere Sammlung hinzugefügt werden
- Dokumente sollen von einer Sammlung in eine andere verschoben werden
- Eine Sammlung soll von allen Dokumenten entfernt (aber nicht gelöscht) werden
- Eine Sammlung soll von allen Dokumenten einer Sammlung entfernt werden

Eine Sammlung könnte über ihre ID identifiziert werden oder auch über die CollectionRole und dann Name oder Number.

Die Operationen oben wären erst einmal ein Anfang. Es ist vorstellbar, dass aus Nutzersicht eine Suchabfrage konstruiert werden könnte, die bestimmt welche Dokumente berücksichtigt werden sollten. Später könnte man die manuell Auswahl von mehreren Dokumenten in einem Suchergebnis ermöglichen. Hier geht es erst einmal nur, um ein einfaches Kommandozeilen Tool. Der eigentliche Code für die Operationen muss so geschrieben werden, dass er auch für die GUI wiederverwendet werden kann, also nicht direkt im Code des Kommandos steht.

**Comment by j3nsch** [comment]
@alw-bsz Gedanken dazu? Gibt es am BSZ Anfragen für Operationen dieser Art? Es geht hier vor allem darum das Hosting zu entlasten. Die Komandozeilen-Funktionen wären mit wenig Aufwand umsetzbar. Eine einfache Integration in die GUI für komplette Sammlungen oder Suchergebnisse wäre auch nicht so schwer. Die fummeligste Arbeit dabei ist immer das Styling in der UI. Am wichtigsten ist aber erst einmal zu klären welche Operationen am nützlichsten wären.

**Comment by alw-bsz** [comment]
Derartige Anfragen erhalten wir tatsächlich immer wieder und nehmen die Operationen dann bislang direkt auf Datenbank-Ebene vor. Ein Kommando wäre also sinnvoll. Die von Dir aufgelisteten Anwendungsfälle decken nach meiner spontanen Einschätzung das Wesentliche ab.

**Comment by j3nsch** [comment]
Kommandos Copy/Move/Remove für die Dokumente in Sammlungen funktionieren.
