### ISSUE TITLE
DINI-Vorgaben (Groß-/Kleinschreibung) der Sets für Dokument- und Publikationstypen umsetzen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#767]
Im DINI-Zertifikat 2016 http://nbn-resolving.de/urn:nbn:de:kobv:11-100239432 gibt es die Mindestanforderung:

M.6-4 Allen Dokumenten sind Dokument- bzw. Publikationstypen aus dem Vokabular der DINI-Empfehlungen Gemeinsames Vokabular für Publikations- und Dokumenttypen zugeordnet.
-> Siehe dazu http://nbn-resolving.de/urn:nbn:de:kobv:11-100109998 sowie Abschnitt A.2.3.

In Abschnitt A.2.3 steht die Mindestanforderung:

M.A.2-3 Es existiert eine Set-Struktur wie in Tabelle 2 abgebildet, in die alle Metadatensätze gemäß der Zuordnung zu Dokument- und Publikationstypen der dazugehörigen Dokumente eingeordnet sind.

Die Vorgaben der Tabelle 2 sollen umgesetzt werden, d.h. die Schreibweise (groß/klein) der Sets müssen angepasst werden (momentan wird alles klein geschrieben).

**Comment by alw-bsz** [comment]
Soweit ich sehen kann, ist das schon längst umgesetzt. Auch bei der Umstellung auf die Schreibweisen im Gemeinsamen Vokabulars 2.0 sollte es zu keinen Problemen mit den Schreibweisen der Sets kommen. Das Issue kann m.E. geschlossen werden.
