### ISSUE TITLE
Identifier für Personen in OAI-DC ausgeben

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#807]
Personen-Identifier sollen über die OAI-API im Format oai_dc ausgegeben werden, wie im DINI-Zertifikat 2019 empfohlen (s. https://doi.org/10.18452/20545, S.66, E.A.3-10):

> E.A.3-10 Für das Element creator werden Identifier für Autor*innen (z. B. ORCID iD) in folgende Binnenstruktur integriert: Carberry, Josiah; https://orcid.org/0000-0002-1825-0097; https://myauthoridentifer/xyz.
> ⇒ Analog gilt diese Empfehlung auch für das Element contributor, sofern darin ein Personenname genannt wird und ein oder mehrere Identifier für Autor*innen vorliegen (s. auch M.A.3-2 und Beispiele unter A.4).

Konkret sind GND-ID und ORCID iD in den Elementen <creator> und <contributor> zu ergänzen, wenn sie vorhanden sind. Jede ID wird durch einen vorangestellten URI eindeutig definiert und an den Namen in Textform mit ;˽ (Semikolon Blank) angeschlossen.

URI für GND: http://d-nb.info/gnd/
URI für ORCID: https://orcid.org/

Syntax:

    <creator>Nachname, Vornamen; https://identifieruri1/ID1; http://identifieruri2/ID2</creator>

Beispiel:

    <creator>Adam, Marcus; https://orcid.org/0000-0002-0678-9749; http://d-nb.info/gnd/1186098007</creator>

**Comment by j3nsch** [comment]
Wir sollten uns anschauen, ob das jetzt noch mit in OPUS 4.8.1 einfließen kann. Gibt es hier Probleme, die bei der Umsetzung berücksichtigt werden müssen?

**Comment by alw-bsz** [comment]
Ich denke, das ist unproblematisch und ich kann die ORCID iD und die GND-ID noch einbauen.

Die GND kann jetzt auch mit https referenziert werden, daher verwende ich die https-URL.
https://d-nb.info/gnd/1186098007

**Comment by alw-bsz** [comment]
Mit Commit https://github.com/alw-bsz/application/commit/14a60f01b8e520e983b6417317c851b25d071e0e eingbracht

**Comment by j3nsch** [comment]
Sollte erledigt sein.
