### ISSUE TITLE
Identifier-Typ für Verbund-ID hinzufügen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#869]
Da wir standardmäßig nach der Übertragung der Daten aus OPUS in die Verbund-Datenbank die Verbund-ID zurückspielen, würden wir dies gerne in ein Standard-Identifier-Feld speichern.

Werte sind aktuell:

    'doi','handle','urn','std-doi','url','cris-link','splash-url','isbn','issn','opus3-id','opac-id','uuid','serial','old','pmid','arxiv'

opac-id wird bei uns schon für die ID des lokalen Opacs verwenden. Es fehlt ein Wert für die Verbund-ID. Kann ein neuer Wert eingeführt werden, z.B. union-catalogue-id (oder auch kürzer)?

**Comment by j3nsch** [comment]
Das sollte prinzipiell kein Problem sein. Wahrscheinlich werden wir auch einfach erst einmal nur einen neuen Typ hinzufügen. Trotzdem lohnt es sich mal kurz darüber nachzudenken.

Es könnte natürlich auch noch weitere IDs für das Dokument in anderen Verbundkatalogen geben, z.B. dem B3Kat. Zum einen sind die möglichen Werte einfach Identifier-Typen, aber zum anderen geben wir ihnen mehr Bedeutung, weil wir einen Typ für Identifier aus einem bestimmten Katalog verwenden. Ein weiteres Feld könnte dann die "b3kat-id" sein. Das ist alles kein Problem, solange mit diesen Werten nichts besonderes gemacht werden soll. Momentan müssten für einen neuen Identifier-Typ verschiedenste XSLT Skripte angepasst werden.

Wir können auch mehrere "opac-ids" eintragen, aber die lassen sich dann vielleicht nicht unterscheiden. Man kann natürlich mit einem Präfix arbeiten oder die IDs sind sowieso schon eindeutig. Für einen maschinelle Verarbeitung müsste man dann irgendwie zwischen den IDs unterscheiden können.

Es gibt weitere Tickets, die sich mit Identifiern, befassen. Das Design im Framework hat ein paar Schwachstellen, die überarbeitet werden sollten. Im Prinzip gibt es keinen Grund die Liste der Identifier überhaupt einzuschränken. Wirklich wichtig sind nur URN und DOI. Der Rest wird meines wissens in OPUS 4 nicht weiter verarbeitet. Ich würde sagen, die Einschränkung im Datenbankschema sollte entfernt werden. In OPUS 4 selbst sollte es eine Liste mit definierten Typen geben. Die Liste kann für einzelne Instanzen gekürzt bzw. erweitert werden. Die Hauptarbeit dabei wäre es den Code, der jetzt direkt von konkreten Typen abhängt flexibler zu gestalten.

"union-catalogue-id" ist in jedem Fall etwas unhandlich. Wie sollten die Übersetzungen für den Typ bzw. das Feld aussehen?

**Comment by j3nsch** [comment]
> Mit "union-catalogue-id" wählte ich bewusst eine Bezeichnung, die unabhängig vom Verbund-Katalog ist. Wie man das abkürzt,  das überlasse ich Euch. Die opac-id können wir tatsächlich nicht nehmen, da diese bereits verwendet und wir kein Präfix davorsetzen möchten, um zu unterscheiden.
> 
> Das Feld heisst "Verbund-ID"  , bzw. "Union Catalogue ID".
> 
> Wir benötigen dieses, um einen Link zum Lokalsystem bzw. zum Verbund-System erzeugen, welcher natürlich auch wieder individuell in der index_custom.xslt bzw. inkludierter template-Dateien erzeugt wird.
> 
> Ansonsten wir dieser aktuell auch nicht über andere Schnittstellen ausgegeben.

**Comment by j3nsch** [comment]
Ich denke mittlerweile, dass im Rahmen von Frameworkveränderungen in Zukunft beliebige Identifier erlaubt werden sollten. Ähnlich wie bei den Enrichments könnte dann ein Name und ein Typ festgelegt werden. Die Beschränkung auf eine feste Liste in der Datenbank scheint auf jeden Fall unnötig. Genaueres, wenn diese Änderungen umgesetzt werden.

**Comment by j3nsch** [comment]
Im Prinzip könnte man jetzt sehr schnell die Möglichkeit hinzufügen, die Liste der Identifier-Typen zu erweitern bzw. zu editieren. Daraus ergeben sich dann aber wieder neue Anforderungen.

Identifier wie URN und DOI werden an vielen Stellen im Code erwartet und sollten daher nicht ohne weiteres entfernbar sein. Auf jeden Fall müsste der existierende Code damit klar kommen.

Momentan sind Name und Typ vermischt. Es gibt URN-Identifier und die werden als URNs behandelt. Die existierenden Typen stehen auch für den Namen. Typen wie old und opac3-id gehen aber schon in die Richtung eines Names der den Inhalt und nicht den Typ beschreibt.

Die opac-id ist momentan nur ein String, aber auch hier könnte man sich eine Verlinkung vorstellen. Man müsste dann für diesen Typ/Namen einen Handler definieren, der sich darum kümmert. Das würde bisher direkt in der Frontdoor passieren, aber wir können nicht anfangen für jeden neuen Identifier den Code in mehreren Modulen anzupassen.

Ein neuer Identifiertyp muss sich hinzufügen lassen, ohne das existierender Code angefasst wird. Dazu braucht er einen Namen, einen Typ und evtl. noch weitere Parameter, um Sichtbarkeit u.a. zu steuern.

**Comment by j3nsch** [comment]
Wir brauchen eine Klasse, die als „IdentifierManager“ auftritt. Die verfügbaren Identifier kommen aus der Konfiguration. Es ist nicht notwendig dies wie bei den EnrichmentKeys in der Datenbank zu speichern. In der Konfiguration könnte das so aussehen.

    identifier.union-catalog-id.type = string
    identifier.issn.type = issn
    identifier.opus3id.name = opus3-id

Das ist erst einmal nur ein Entwurf. Es wären weitere Optionen denkbar, z.B. um zu steuern, ob mehrere Identifier eingegeben werden dürfen. In erster Linie geht es aber erste einmal nur darum die Liste (siehe oben in der Beschreibung) konfigurierbar zu machen. Die Type-Option kann die Validierung steuern und für DOI und URN könnten z.B. die zusätzlichen Workflow-Plugins konfiguriert werden.

Es sollte dann eine „Identifier“ Seite im Setup-Bereich von OPUS geben. Dort sollte man dann auch die Übersetzungen für Identifier editieren können, sowie vielleicht eine zusätzliche Beschreibung. Ein neuen Identifier könnte man dann einfach in der Administration hinzufügen. Vielleicht sollten wir Identifier auch deaktivierbar machen, so dass sie in den Formularen nicht als Option angeboten werden. Unbekannte Werte, die bereits in der Datenbank gespeichert sind, müssten toleriert werden.

Es sollte eine Klasse für den IdentifierType geben. Das sollte als Teil der OPUS-API in das Common-Package gehen.

Im allerersten Schritt ist aber wirklich denkbar einfache nur eine konfigurierbare Liste der möglichen „Namen“ zu schaffen.

**Comment by j3nsch** [comment]
@alw-bsz Die Identifier-Typen werden für 4.8.1 nicht konfigurierbar gemacht. Was hier im Ticket steht ist mittlerweile auch schon wieder mindestens ein Jahr alt und muss von mir noch mal reviewed werden. Die Konzepte haben sich weiter entwickelt und müssen noch warten bis wir die alte Implementation losgeworden sind. 

Abgesehen davon, sehe ich aber kein Problem damit, jetzt einen weiteren Identifier-Typ hinzuzufügen, vor allem wenn der Wert in diesem "Feld" das Dokument identifiziert und keine Referenz zu etwas "anderem" ist. Die Länge von Typen ist im Augenblick auf 10 Zeichen begrenzt. Das könnte natürlich erweitert werden, aber 10 Zeichen sollten reichen, um alle Identifierttypen, die wir jemals brauchen auseinander zu halten. Es ist klar, dass es eine ID ist. Den Suffix "-id" könnte man also schon mal weglassen. :-)

**Comment by alw-bsz** [comment]
@j3nsch Dank! Statt "union-catalog-id" könnte man z.B. "union-cat" verwenden. Das wären unter 10 Zeichen :-).

**Comment by j3nsch** [comment]
Ich habe das minimal notwendige erledigt. Der Typ `union-cat` wurde hinzugefügt und die Übersetzungen für das Feld und den Wert. Das Feld heißt `IdentifierUnionCat`. Damit laufen die Tests. Alles weitere überlasse ich dem BSZ.

Ich muss später mal überlegen, wie man die Ressourcen für einen Identifier-Typ bündeln kann, so dass nicht alles über mehrere Dateien verteilt ist. Das kann aber erst mit einem neuen Publish-Modul angegangen werden.

**Comment by alw-bsz** [comment]
@j3nsch Danke, das passt! Wir würden uns dann noch um die Darstellung auf der Frontdoor kümmern.

**Comment by j3nsch** [comment]
Ich gehe davon aus, dass das erledigt ist.
