### ISSUE TITLE
proxy-Betrieb: Problem bei Zugriffssteuerung

### ISSUE THREAD

**Issue by CAWinter** [OPUS4/application#919]
Mit der Version 4.7.1.1 haben wir Opus über einen Proxy so konfiguriert, dass folgendes im HTTP-Header geliefert wird:

$_SERVER["REMOTE_ADDR"] enthält die Proxy-IP
$_SERVER["HTTP_X_FORWARDED_FOR"] enthält die IP des zugreifenden Clients

Der Parameter 
url = user-proxy-server.de
ist in der config.ini gesetzt, weitere Anpassungen in der Konfigurationen wurden nicht gemacht.

Die IP-basierte Zugriffssteuerung funktioniert mit dieser Konfiguration nicht. Getestet haben wir den Zugriff auf einen geschützten Volltext und den Zugriff auf ein geschütztes Modul.
Verwendet wird offensichtlich  die IP-Adresse des Proxy-Servers und nicht des Clients.

getClientIp sollte den X-Forwarded-For -Header auswerten, wenn der Proxy aktiviert ist.

**Comment by j3nsch** [comment]
Das Thema hatten wir hier im Hosting auch schon. Das hat einiges an Zeit gekostet und am Ende wurde die Änderungen wieder entfernt.  Das Problem muss über die Konfiguration des Webservers bzw. des Proxies gelöst werden. Das funktioniert beim KOBV, aber ich kann Euch da nicht die Details geben. 

Die Auswertung des Headers wird im OPUS 4 Code nicht erfolgen, weil der Header gespoofed werden kann und es für OPUS 4 keine Möglichkeit gibt das zu erkennen.

**Comment by j3nsch** [comment]
Am besten das Hosting vom KOBV kontaktieren. Es gab anscheinend noch keine Zeit das mit ins Handbuch aufzunehmen (OPUS4/userdoc#114).

**Comment by mluta** [comment]
Wir haben In Frankfurt a. M. ein ähnliches Problem. Unser OPUS-Server kann nur Proxy-IP und nicht die IP des abrufenden Nutzers sehen.  Wie können wir umkonfigurieren bzw. wer könnte helfen?

Vielen Dank und schöne Grüße
Marius Luta

m.luta@ub.uni-frankfurt.de

**Comment by mluta** [comment]
Vielen Dank, leite es an die Kollegen weiter, hoffentlich kommen sie 
damit zurecht.


Schöne Grüße

Marius Luta

Am 02.09.2022 um 11:05 schrieb cawin:
