### ISSUE TITLE
Schriftgrößen im CSS nicht mit Pixeln angeben

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#968]
Die Angabe der Schriftgrößen im CSS mit Pixelwerten (px) erschwert die skalierte Anzeige auf iPads und anderen kleineren Bildschirmen.

**Comment by j3nsch** [comment]
In `doi-import.css` wird eine Fontgröße in Pixeln angegeben, für `#DoiButton`. Ich habe das jetzt auf `1em` geändert. Allerdings konnte ich nicht finden wo bzw. ob die ID `DoiButton` überhaupt verwendet wird. @alw-bsz, @bfalkenstein Bitte klären und Bescheid sagen. Danke!

**Comment by j3nsch** [comment]
Schriftgrößen werden nicht mehr mit Pixeln angegeben, auch nicht im alten Design. Evtl. müssen noch mal Anpassungen an den Größen vorgenommen werden. Es muss noch geklärt werden, ob `#DoiButton` notwendig ist.

**Comment by bfalkenstein** [comment]
Lieber Jens, 

 

ich habe dir in Github auf diesen Commit geantwortet ( https://github.com/OPUS4/application/commit/43897e94084069770f0d4597bd3b21a282600165 ).

 

Bitte schau es dir nochmal an. Wenn der Commit so in die 4.8.1 geht, gäbe es m.E. ein Problem mit den unsichtbaren Formularfeldern. 

Diese Mail schreibe ich dir nur zur Sicherheit, damit diese Meldung wirklich bei dir ankommt. 

 

Danke und Grüße

Boris

 

Von: Jens Schwidder ***@***.***> 
Gesendet: Donnerstag, 3. August 2023 10:41
An: OPUS4/application ***@***.***>
Cc: Boris ***@***.***>; Mention ***@***.***>
Betreff: Re: [OPUS4/application] Schriftgrößen im CSS nicht mit Pixeln angeben (Issue #968)

 

In doi-import.css wird eine Fontgröße in Pixeln angegeben, für #DoiButton. Ich habe das jetzt auf 1em geändert. Allerdings konnte ich nicht finden wo bzw. ob die ID DoiButton überhaupt verwendet wird. @alw-bsz <https://github.com/alw-bsz> , @bfalkenstein <https://github.com/bfalkenstein>  Bitte klären und Bescheid sagen. Danke!

**Comment by j3nsch** [comment]
Danke, für den Hinweis. Ich habe das jetzt aus dem Branch **css996** herausgenommen.
