### ISSUE TITLE
Ausgabe von GND-ID und ORCID iD in XMetaDissPlus

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/application#978]
**GND-ID (GND-Nr)** und **ORCID iD** sollen bei Personen in XMetaDissPlus ausgegeben werden.

Die **GND-Nr** als neues Attribut ddb:GND-Nr zu Element pc:person in XMetDissPlus hinzufügen.
Betrifft folgende Personenfelder in XMetaDissPlus im Element pc:person mit parents dc:creator oder dc:contributor:
PersonAuthor
PersonReferee
PersonEditor
PersonAdvisor

Beispiel der DNB:
`<pc:person gender="f" ddb:GND-Nr="2345678X">`

Neues fakultatives Element für Personen: **ddb:ORCID**
 (die weiteren fakultativen Elemente  ddb:ISNI und ddb:OtherID in XMDP 2.3 sollen erst mal nicht umgesetzt werden, bis es einen definierten Bedarf gibt)

Es ist das erste child von pc:person mit parents dc:creator und dc:contributor für die Personenfelder:
PersonAuthor
PersonAdvisor
PersonReferee
PersonEditor

Der Identifier wird im Elementinhalt geliefert.

Die ORCID iD kann bereits in OPUS zu den Personenfeldern hinterlegt werden und könnte entsprechend ausgelesen werden.

Beispiel der DNB:
`<pc:person gender="f" PND-Nr="123456789">`  
` ddb:ORCID>0000-0002-3988-7839</ddb:ORCID>`
`<pc:name type="nameUsedByThePerson">`

**Comment by alw-bsz** [comment]
Intern OPUSVIER-4207 und OPUSVIER-4208

**Comment by j3nsch** [comment]
Ich werde noch Unit Tests für die Ausgabe der GND-ID und ORCID schreiben, damit die Funktionalität später nicht unbemerkt gebrochen werden kann und außerdem zu signalisieren, das die Ausgabe so gewollt ist.

**Comment by j3nsch** [comment]
ORCID und GND-ID werden in xMetaDissPlus für die vier Rollen, Author, Advisor, Referee und Editor ausgegeben und das wird durch Unit Tests geprüft.
