### ISSUE TITLE
Auf verfügbare Dokumenttypen prüfen für DOI-Import

### ISSUE THREAD

**Issue by bfalkenstein** [OPUS4/application#980]
Für die Prüfung, welche Dokumenttypen in einer Installation aktiviert sind, nutzt der DOI-Import z.Zt. das Script /public/getDoctypes.php. Hier wird in der config.ini nachgeschaut, welche Werte in documentTypes.include bzw. documentTypes.exclude eingetragen sind. Der Aufruf erfolgt in public/layouts/opus/js/getDoi.js.
(Hintergrund: Falls der korrekte Dokumenttyp gemäß Crossref nicht angelegt ist, wird das importierte Dokument mit dem Dokumenttyp 'other' abgespeichert, da es sonst eine Fehlermeldung gibt.)
Rückgabewert ist ein kommaseparierter String der aktivierten Dokumenttypen.

**Comment by j3nsch** [comment]
@bfalkenstein Die Funktion ist unter `api/doctypes` und liefert JSON mit den Dokumententypen als Array und dem Property `doctypes` zurück. Die Code liegt im Default-Module. Ich denke das wird sich später noch mal ändern, wenn wir besser wissen wie eine REST-API für OPUS 4 aussehen könnte.

**Comment by j3nsch** [comment]
Wenn das für den Javascript Code funktioniert, würde ich `public/getDoctypes.php` entfernen.

**Comment by j3nsch** [comment]
Der Branch **4.7.2-doi-import** ist jetzt wieder auf dem neuesten Stand.

**Comment by j3nsch** [comment]
Die neue Function `api/doctypes` wird verwendet. Das Skript `public/getDoctypes.php` wurde entfernt.
