### ISSUE TITLE
Export von Suchtreffern ab 100 liefert leere Datei

### ISSUE THREAD

**Issue by ViciOuo** [OPUS4/application#983]
Der Export einer Trefferliste (csv, bibtex, MARC usw.),ist nur für die ersten 100 Datensätze möglich.
Nach dem Weiterbrowsen zu den nächsten 100 Datensätzen wird bei einem Export eine leere Datei erzeugt.

**Comment by j3nsch** [comment]
In einer Entwicklungsinstanz mit Standard-Einstellungen wird der Export nur für den Admin angezeigt. Damit funktioniert auch der Export für weitere Seiten mit Suchtreffern. Wird einfach nur der Zugriff auf das Export-Modul für die **guest**-Rolle ermöglicht, kann man auch als normaler Nutzer auf den Export zugreifen und es funktioniert immer noch. Wir müssen also mal bei der konkreten Instanz mit den Problemen schauen woran es liegen könnte.

**Comment by j3nsch** [comment]
Das Problem tritt auf, wenn die Treffer ab 100 exportiert werden sollen, unabhängig davon wie viele Treffer auf einer Seite angezeigt werden. Wenn man 25 Ergebnisse exportiert und bei 99 startet, bekommt man ein Dokument im Export, auch wenn mehr angezeigt werden. Setzt man für die gleiche Suche den Parameter **start** auf 100, enthält der Export kein Dokument mehr.

**Comment by j3nsch** [comment]
Es muss ein Test hinzugefügt werden, der prüft, dass alles funktioniert, wenn der **start** Parameter größer als die maximale Anzahl an **rows**. Die beiden Parameter sollten nichts miteinander zu tun haben, aber im alten Code gab es eine Verbindung. Die wurde jetzt entfernt.

**Comment by j3nsch** [comment]
Das Problem war der Code, der Verhindern sollte, dass Parameter **start** und **rows** zusammen den Maximalwert für Integer-Variablen in Solr (Java) überschreiten, also 2147483647. Dabei wurde versehentlich der konfigurierbare Maximalwert für Exports als Grenze genommen, also 100 für Guest-User. Mit einem Start-Wert von 100 musste der Rows-Wert dann 0 sein, um diese Grenze nicht zu überschreiten. Das ist jetzt gefixt.

**Comment by j3nsch** [comment]
Der neue Code hat jetzt Kommentare, die erläutern warum er so kompliziert aussieht.

**Comment by ViciOuo** [comment]
Danke dir!

**Comment by j3nsch** [comment]
Bug gefixt und neuen Test hinzugefügt, aber ansonsten altes Verhalten beibehalten.
