### ISSUE TITLE
REST-API Funktion für Javascript, um vorhanden sein einer DOI in OPUS 4 zu prüfen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#989]
Wir verwenden Javascript, um anhand einer DOI das Publish-Formular automatisch zu befüllen. Vorab soll geprüft werden, ob die DOI bereits in der Datenbank vorliegt, das Dokument also schon in OPUS 4 existiert. 

Hier sollte vielleicht nicht nur gemeldet werden, ob eine DOI bereits bekannt ist, sondern auch mit welchem Dokument sie assoziiert ist. Dadurch wäre es möglich dem Nutzer einen Link zum Dokument anzuzeigen.

**Comment by j3nsch** [comment]
@bfalkenstein, @alw-bsz Wenn wir in der Datenbank nach eine DOI suchen, kann diese zu einem Dokument gehören, das noch nicht freigeschaltet ist. Das wären Informationen, die anonymen Nutzern bisher nicht verfügbar wäre.

Für freigeschaltete Dokumente würde die Antwort im Augenblick in etwa so aussehen. Es könnten natürlich auch noch weitere Metadaten zurückgegeben werden.

```
{
    "found":true,
    "docId":146
}
```

Für nicht freigeschaltete Dokumente würde ich die **docId** nicht mit zurück geben. Wie seht Ihr, dass so geprüft werden kann, ob eine DOI für ein noch nicht freigeschaltetes Dokument im System ist?

**Comment by j3nsch** [comment]
Für einen Link, sollte gleich die passende URI mitgeliefert werden, damit im Javascript nicht der Code für eine Frontdoor-URL dupliziert wird. Titel, Jahr und Autoren könnten vielleicht auch für die Anzeige des Links nützlich sein.

**Comment by j3nsch** [comment]
Bei der bereits eingebauten DOI-Prüfung im Metadaten-Formular werden nur lokale DOIs geprüft, also DOIs mit dem lokalen Präfix. Für alle anderen wird automatisch keine Kollision gemeldet.  Kann es sein, dass wir da noch eine Lücke bei den Anforderungen haben? Kann sich der Präfix im Laufe der Zeit ändern?

**Comment by j3nsch** [comment]
Die Funktion gibt Anworten wie folgende zurück.

``` JSON
{
    "doi": "ÜBERGEBENE DOI",
    "docId": "DOCUMENT ID WENN DOCUMENT IM SERVERSTATE PUBLISHED",
    "doiExists": true
}      
```

**Comment by alw-bsz** [comment]
> Bei der bereits eingebauten DOI-Prüfung im Metadaten-Formular werden nur lokale DOIs geprüft, also DOIs mit dem lokalen Präfix. Für alle anderen wird automatisch keine Kollision gemeldet. Kann es sein, dass wir da noch eine Lücke bei den Anforderungen haben? Kann sich der Präfix im Laufe der Zeit ändern?
> 
> **Nachtrag:** Die Prüfung erfolgt wohl doch für alle DOIs, egal ob mit lokalem Präfix oder nicht.

Es wäre tatsächlich wichtig, dass die Prüfung alle DOIs im Repositorium berücksichtigt und nicht nur jene mit lokalem Präfix.

**Comment by alw-bsz** [comment]
Danke für die Funktion! Boris schaut sich das an und kümmert sich um die Integration in den DOI-Import.

Für Anwender schwebt uns eine Ausgabe in der Form "Es ist bereits ein Datensatz mit dieser DOI im Repositorium vorhanden. Der Datensatz ist derzeit nicht zugänglich." für Dokumente, die nicht freigeschaltet sind, vor.

**Comment by j3nsch** [comment]
Funktion existiert.
